### ISSUE TITLE
[CHECKLIST] Requirements for Tangle webbsite 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1010]
## Overview 

The purpose of this checklist is to outline the requirements to implement Tangle Network landing page. The below tasks are broken down and should be worked on in small chunks followed by a review from the design team. The expected deliverable includes both **desktop** and **mobile** implementations. All design elements are linked below and categorized by section.

Any design questions please reach out to @monaiuu , for implementation questions ping @dutterbutter. 

### Section Breakdown

The landing page can be broken down into the following sections:

- [ ] [TASK] Implement Hero section
- [ ] [TASK] Implement Introducing Tangle Network section
- [ ] [TASK] Implement What makes Tangle Unique section
- [ ] [TASK] Implement Governance System section
- [ ] [TASK] Implement Join the Tangle Ecosystem section
- [ ] [TASK] Implement Launch Phases section
- [ ] [TASK] Implement Use cases section
- [ ] [TASK] Implement Supported By section
- [ ] [TASK] Implement FAQ section
- [ ] [TASK] Implement Tangle Community section
- [ ] [TASK] Implement Email section
- [ ] [TASK] Implement Footer section
