### ISSUE TITLE
[FEAT] DKG Stats Data Source Selection Improvement

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1015]
## Overview

This issue addresses the improvement of DKG Stats URL inputs/selection (https://github.com/webb-tools/webb-experiences/issues/98) The updated design makes it easier for users to select existing known deployments, as well as, input custom URLs. With the use of radio buttons, user can quickly update what data they would like to be displayed. While also allowing users to put a custom URL for local development or other backends.

The updated design also enables users to easily toggle between `Development`, `Testnets`, and `Live` networks (when it is available). Please note that we will disable the `Live` radio button for now. 

<img width="1569" alt="Screenshot 2023-02-18 at 11 36 13 AM" src="https://user-images.githubusercontent.com/109539270/219827375-4f9cd332-b81c-4e63-af32-77b570865b66.png">

The finalized version of the DKG stats prototype has been updated to the latest change. Please feel free to access it to see how the change is reflected. Click [HERE](https://www.figma.com/proto/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?page-id=1152%3A113488&node-id=1167%3A152573&viewport=3058%2C-1335%2C0.26&scaling=scale-down&starting-point-node-id=1167%3A152573&show-proto-sidebar=1) for the latest prototype.

https://user-images.githubusercontent.com/109539270/219826321-80c05f18-0c63-43c2-b8e3-331dcd4ceb13.mp4

Above showcases how the updated design should operate. For reference for the inputting & saving custom node behaviour, feel free to reference Polkadot-JS as well.

<img width="432" alt="Screenshot 2023-02-18 at 11 22 20 AM" src="https://user-images.githubusercontent.com/109539270/219826838-a613018b-eed0-49ca-9378-490daa7edda6.png">

## Tasks

- [ ] Add separation for `Development`, `Testnets`, and `Live` networks using radio buttons
- [ ] Add preset endpoints for Testnet using radio buttons
- [ ] Add chain avatar image to preset endpoints (tangle alpha & rococo)
- [ ] Add local endpoint to development network using radio button
- [ ] Place custom endpoint input field within the development network 
- [ ] Remove reset utility link
- [ ] Add `save` icon button to enable user to click and save the custom endpoint for future usage (see polkadot JS for reference) (see figma file for different states of icon buttons and input field)
- [ ] Add `remove` icon button to enable user to click and delete the custom endpoint
- [ ] Add tooltips where applicable (see figma file)

## File Access
https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?node-id=1152%3A113488&t=Z0H1f06UrhU3MPzC-1
<img width="1431" alt="Screenshot 2023-02-18 at 11 01 07 AM" src="https://user-images.githubusercontent.com/109539270/219825953-d5942d53-a57b-4b8a-af79-801acae44931.png">

Please review and let me know if the above-proposed change looks reasonable. @dutterbutter

**Comment by dutterbutter** [comment]
Closing in favour of original issue: https://github.com/webb-tools/webb-dapp/issues/1009
