### ISSUE TITLE
[TASK] Implement testnet Webb Faucet

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1030]
## Overview 

For more in-depth discussion, please refer to the initial PRD [here](https://www.notion.so/hicommonwealth/READY-Hubble-Bridge-Faucet-PRD-a8aec6160a684931b45c6d0dc7bf2cc0).

To enhance the testing process and ensure a better user experience, we need a more efficient method for obtaining testnet tokens that would allow us to test larger asset balances and streamline the onboarding process.

By creating a dedicated faucet for the Hubble Bridge, we can ensure that users have easy access to the test tokens they need, that we control, without having to navigate multiple faucets. This would also allow us to generate larger asset balances on each network, making it easier to test the bridge's capabilities on each side of the bridge.

This task will involve @AtelyPham @shekohex @monaiuu to deliver. 

### Implementation Details

User Steps

1. Users would go to `https://faucet.webb.tools`  - this would navigable from Hubble Bridge 
2. Login with Twitter (similar flow as https://faucet.paradigm.xyz/) for social authentication 
3. Select the network they wish to mint a token from (e.g. Mumbai, Goerli, Sepolia, Moonbase, Arbitrum, Optimism), 
4. Enter recipient address, 
5. Click **Mint.** The user would then receive 1000 test tokens for the given network in their provided address. The mint button should remain disabled until user is authenticated and follows webbprotocol.

## Authentication Requirements

In order to receive minted tokens, users would be required to authenticate themselves using their Twitter social profile and follow `@webbprotocol`. 

**Potential Steps**

1. Present login with Twitter button
2. Provides a callback with login Twitter username
3. Check to see if they follow webbprotocol 
    1. If not, present a button to follow webbprotocol 
4. If following, allow the minting of tokens

**More in-depth:**

1. Go to the Twitter Developer Platform and create a new application. This will give you the necessary keys and tokens to access the Twitter API.
2. There are many third-party libraries available that you can use to make API requests. Some popular options include **`twit`**, **`twitter`**, and **`twitter-lite`**.
3. Use the keys and tokens from your Twitter application to authenticate your API requests. You'll typically need a consumer key, a consumer secret, an access token, and an access token secret.
4. Use the client library to make API requests

**Example implementation:**
```
const Twit = require('twit');

// Set up your authentication credentials
const T = new Twit({
  consumer_key:         'YOUR_CONSUMER_KEY',
  consumer_secret:      'YOUR_CONSUMER_SECRET',
  access_token:         'USER_ACCESS_TOKEN',
  access_token_secret:  'USER_ACCESS_TOKEN_SECRET',
});

// Authenticate the user with Twitter
T.get('account/verify_credentials', {}, function(err, data, response) {
  if (err) {
    console.error(err);
  } else {
    // Check if the user follows @webbprotocol
    T.get('friends/ids', { screen_name: 'webbprotocol' }, function(err, data, response) {
      if (err) {
        console.error(err);
      } else {
        const userFollowsWebbprotocol = data.ids.includes(data.id);
        console.log('User follows @webbprotocol:', userFollowsWebbprotocol);
      }
    });
  }
});
```

## Task Checklist 

- [ ] Create a new app in `apps/` directory for Webb Faucet 
- [ ] Implement the proposed design linked above using components from `webb-ui-components` 
- [ ] Validation of recipient address (evm, substrate address) 
- [ ] Set 24hr drip limit to protect from over usage 
- [ ] Create a new repo for social authentication server 
- [ ] Implement Twitter authentication logic and store recipient address in KV database 
- [ ] Deploy, connect backend and minting contracts to faucet front-end
- [ ] Test implementation 
- [ ] Add Faucet navigation to Hubble Bridge

**Comment by monaiuu** [comment]
### Notes

To access the handoff Wireframes in Figma; please visit the below link:
https://www.figma.com/file/t0bIz5vsiN48ZdwoeBJUge/%E2%9B%B2%EF%B8%8F-Faucet?node-id=1%3A58&t=wDPZrHSOeX8Op3e9-1

I have added comments within the above Figma file for more detailed instructions. Should you have any questions, please reach out!
