### ISSUE TITLE
[BUG] Note table displays notes that are already spent and deleted

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1034]
## Issue Description

The delete option in the notes table should delete the given note from storage. I am assuming since we have made changes to how we are storing things in localStorage that we did not reflect that change in the deletion of notes. Currently if you delete a note, it does NOT get deleted from localStorage. 

In addition, when a note gets spent we need to remove it from localStorage. I am assuming this error is caused by the same reason mentioned above. 

### Task Checklist

- [ ] Debug notes table deletion function 
- [ ] Provide a fix to resolve deletion issue
- [ ] Debug notes table displaying notes that are spent
- [ ] Provide a fix to resolve notes table displaying notes that are spent

### Video of note not being deleted, and removing notes that are already spent
https://user-images.githubusercontent.com/29983536/222742222-fa51ca69-1203-408a-9a90-0597015c1999.mp4
