### ISSUE TITLE
[CHECKLIST] High priority items for `Hubble v.0.1.0-alpha` release

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1043]
## Overview

The following checklist outlines the required tasks to be completed for a `Hubble v.0.1.0-alpha` release. This is the highest priority milestone and should be worked on first and foremost. 

### Task Checklist 

- [x] https://github.com/webb-tools/webb-dapp/issues/1039
- [x] https://github.com/webb-tools/webb-dapp/issues/1030
- [x] https://github.com/webb-tools/webb-dapp/issues/1027
- [x] #1044
- [x] #1045
