### ISSUE TITLE
[TASK] Support for additional bridges with different backend

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1044]
## Overview

This task outlines the requirements to support three distinct bridges on the Hubble bridge. Those bridges each have a different backend. 

**Note:** This task is dependent on the deployments of each proposed bridge.

### Task Checklist

- [x] Add anchor address support for `webbWETHStandalone` bridge
- [x] Add anchor address support for `webbWETHParachain` bridge
- [ ] Test each user operation
- [x] Update Hubble bridge docs to reflect changes

**Comment by AtelyPham** [comment]
I will index bridges by the fungible currency, so we need to ensure that all fungible currencies have different names and symbols. Additionally, we have to change the structure of the anchor config from `Record<typedChainId, anchorAddress>` to `Record<typedChainId, anchorAddresses>`, which allows for an array of supported anchor addresses.
