### ISSUE TITLE
[CHECKLIST] Implement Hubble Overview stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1058]
## Overview 

This task outlines the requirements to implement the hubble bridge statistics overview page. This will act as the landing page for the bridge stats. 

### Task Checklist 

- [x] [TASK] Implement the top level navigation that links to docs, github, tangle statistics page, and environment toggle
- [x] #1307
- [x] [TASK] Add TVL and Volume chips in the navigation pane 
- [x] [TASK] Use the chart component in webb-ui-components to create the TVL, and Volume charts
- [x] #1309
- [x] [TASK] Create the key metrics table (Total txs, TVL, volume, fees) 
- [x] [TASK] Create the Shielded Tokens table with filter functionality
- [x] #1306
- [x] #1308
- [x] https://github.com/webb-tools/webb-dapp/issues/1444

**Comment by vutuanlinh2k2** [comment]
@monaiuu I think there's one component is missing (mentioned [here](https://github.com/webb-tools/webb-dapp/issues/1487))

**Comment by monaiuu** [comment]
I believe this epic is now in completion. 

I will be conducting a round of UI review once we have all the dummy data integrated for a more accurate view and create a checklist for minor UI improvements.
