### ISSUE TITLE
[TASK] Update bridge deployments and development chain support 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1109]
## Overview

The goal of this task is to update the bridge deployments supported by the dApp and update the development chain support for the hosted Hermes, Athena, and Demeter networks.

#### Production Environment
In the production environment, the dApp should support the following deployment:

- [`webbAlpha`](https://www.notion.so/hicommonwealth/Bridge-Deployments-54496ac2c29d4a7f9867bb9fa3ed1b2a?pvs=4#a990220e722248cc88d6d26f9cd19ec2): a mocked backend that supports 7 EVM-based chains. This deployment will be supported by relayers 2 and 3.

#### Development Environment
In the development environment, the dApp should support the following deployments:

- `webbTNT-standalone`: Currently being redeployed, this deployment will be supported by relayers 4 and 5 on the development chains Athena, Demeter, and Hermes. This deployment will serve as the initial testing grounds for the DKG backend and Tangle <> EVM transactions.
    - Once tested and considered stable, we will deploy to EVM testnets and roll it out to the production environment.
- By default, `webbAlpha` will be supported.

#### Deprecation
We will be deprecating the [`webbETH`](https://www.notion.so/hicommonwealth/Bridge-Deployments-54496ac2c29d4a7f9867bb9fa3ed1b2a?pvs=4#4c6cd26fc40e4bfaae84c592194a27b9) mocked backend deployment in favor of `webbAlpha`. Since the relayer network will only support one mocked backend deployment with refunds, and `webbAlpha` supports more chains, we will remove `webbETH` mocked backend.

### Development Chain Support

We need to update the dApp to support the hosted Hermes, Athena, and Demeter chains at their respected domains and available RPCs. These chains will be used to test new features and bridge deployments in the development environment. We will update the dApp to support these hosted networks while keeping these chains for local development setup that currently resides in the dApp.

## Task Checklist

- [x] Remove `webbETH` mocked backend deployment.
- [x] Ensure relayer support is available for `webbAlpha` deployment.
- [ ] Cut a release for Hubble bridge
- [x] Update the dApp to support the hosted development chains Athena, Demeter, and Hermes. Please refer [here](https://github.com/webb-tools/orbit#-getting-started---) for the required domains and RPCs.
- [ ] Add new `webbTNT-standalone` deployments once ready, ensure relayer support, and test with the DKG as a backend.
