### ISSUE TITLE
[TASK] Add SEO, plausible, and favicon to Tangle webbsite

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1112]
## Overview

As we have done on the marketing site, we need to include the SEO tags, plausible script, and favicon to the Tangle webbsite. 

### Task Checklist

- [x] Add SEO tags for Tangle website, for reference please review [here](https://github.com/webb-tools/webb-dapp/blob/597feb8f41f6969d7054438c102eb3c110ad923e/apps/webbsite/src/pages/index.tsx#L17) and [here](https://github.com/webb-tools/webb-dapp/blob/597feb8f41f6969d7054438c102eb3c110ad923e/apps/webbsite/src/pages/_app.tsx#L26).
- [x] Add Plausible scripts for `tangle.webb.tools`,  for reference please review [here](https://github.com/webb-tools/webb-dapp/blob/597feb8f41f6969d7054438c102eb3c110ad923e/apps/webbsite/src/pages/_app.tsx#L66)
- [x] Update favicon to make use of Tangle logo
