### ISSUE TITLE
[CHECKLIST] Update footer component for Webbsite

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1128]
## Description

Please see below for the latest updates to the footer component for Webbsite

- [ ] Update footer component to include navigation links and site map on Webbsite
- [ ] Add Linkedin & YouTube social icons to footer component
- [ ] Remove the requirement for users to enter their name for subscribing to email list
- [ ] Update mobile footer component with above changes

![Image](https://user-images.githubusercontent.com/109539270/233748435-0d16f6f9-7494-4ae9-9d16-6e84524b91d2.png)

Figma Access:
https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1028%3A32475&t=efsptjtm5FlBowH5-1
