### ISSUE TITLE
[CHECKLIST] Implement Webb Brand Kit on Webbsite

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1129]
## Webb Brand Kit Handoff

Please see below for the requirements for Webb's Brand Kit. 

![Image](https://user-images.githubusercontent.com/109539270/233758986-627cbce4-9d77-4cb8-95df-b009ff343d07.png)

- [x] Implement Webb Brand Kit in desktop view
- [x] Implement Webb Brand Kit in mobile view
- [x] Gather all assets appropriately to be downloaded  (will provide notion doc)
- [ ] #1165

Figma Link:
https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=2391%3A83280&t=efsptjtm5FlBowH5-1

**Comment by monaiuu** [comment]
### File Access

See all required assets to be downloaded from Webb Brand Kit here:
https://www.notion.so/hicommonwealth/Webb-Brand-Kit-7ba65237a47640edb13dee499ae28a30?pvs=4

Please reference [Polkadot's Brand Hub](**url**) in organizing the assets for download.

**Comment by vutuanlinh2k2** [comment]
@dutterbutter since the Footer now doesn't have Resources column, what should the solution for [this task](https://github.com/webb-tools/webb-dapp/issues/1165). 

Also this is the task that I accidentally created from the last check box above, and I'm not sure how to remove it, can you help me with that also ^^

**Comment by dutterbutter** [comment]
Please put it under Company.

**Comment by dutterbutter** [comment]
Closed in #1167
