### ISSUE TITLE
[CHECKLIST] Implement Webb Brand Kit on Webbsite

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1130]
## Webb Brand Kit Handoff

Please see below for the requirements for Webb's Brand Kit. 

![Image](https://user-images.githubusercontent.com/109539270/233758986-627cbce4-9d77-4cb8-95df-b009ff343d07.png)

- [ ] Implement Webb Brand Kit in desktop view
- [ ] Implement Webb Brand Kit in mobile view
- [ ] Gather all assets appropriately to be downloaded  (will provide notion doc)
- [ ] Add link to footer component for `Brand Kit` below Resources section

Figma Link:
https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=2391%3A83280&t=efsptjtm5FlBowH5-1

**Comment by dutterbutter** [comment]
Closing in favour of #1129
