### ISSUE TITLE
[CHECKLIST] Review/audit Tangle website UI and copy

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1137]
## Overview

This task will outline a series of smaller tasks focusing on improvements, fixes, and additions to the Tangle website. The dApp team implemented each section of the Tangle site last sprint, and require a thorough review of the UI components and we require some copy in specific sections. 

#### Development Link
- [Tangle Dev ](https://tangle-webbsite.netlify.app/)

**Comment by monaiuu** [comment]
## Task Checklist

- [ ] Implement hover tooltips for Introduction Section's Tangle Network diagram
<img width="1390" alt="Screenshot 2023-04-28 at 4 49 34 PM" src="https://user-images.githubusercontent.com/109539270/235270957-6237c007-77ed-446c-a2c0-3f827ddfea7a.png">


- [ ] Implement hover states for below `Card` components 
- [ ] Improve image resolution for Feature Section's `Cards`
<img width="1529" alt="Screenshot 2023-04-28 at 4 36 28 PM" src="https://user-images.githubusercontent.com/109539270/235271059-4d729b99-4ba4-4dcc-b78b-7f7ed9792ba0.png">


- [ ] Fix Accordion Components' width between expanded/collapsed states
<img width="1319" alt="Screenshot 2023-04-28 at 4 31 39 PM" src="https://user-images.githubusercontent.com/109539270/235271368-fb91084e-4c5b-45a9-85f4-50064955b9e6.png">


- [ ] Improve image display in Governance Section to ensure it is scaled properly. 
<img width="1256" alt="Screenshot 2023-04-28 at 4 58 46 PM" src="https://user-images.githubusercontent.com/109539270/235271469-6db90fdc-ad27-4d87-9cc4-6e45b5c85065.png">


- [ ] Ensure spacing between content & hero image is consistent as going into larger screen sizes 
<img width="1996" alt="Screenshot 2023-04-28 at 4 56 26 PM" src="https://user-images.githubusercontent.com/109539270/235271340-b7bc116a-b336-4702-b105-5f74a0260874.png">

**Comment by dutterbutter** [comment]
@vutuanlinh2k2 can you please address the above tasks ^^

**Comment by thomivy** [comment]
<img width="1085" alt="Screenshot 2023-05-04 at 6 57 11 PM" src="https://user-images.githubusercontent.com/38070512/236353994-848ae857-9979-43fa-94c3-3466b3ac8de1.png">
`The next-generation blockchain for seamless and private cross-chain messaging and applications.`
Technical jargon is inaccessible, and describes the how but not the what. 

<img width="1015" alt="Screenshot 2023-05-04 at 7 05 19 PM" src="https://user-images.githubusercontent.com/38070512/236354795-48713285-0ac1-446b-b613-faa2942694d4.png">
`The Tangle network serves as a hub for secure communication and private interactions across different blockchains.`

<img width="1111" alt="Screenshot 2023-05-04 at 7 06 50 PM" src="https://user-images.githubusercontent.com/38070512/236354942-476822db-0749-4f53-94da-516e29fc064f.png">
```
Proof-of-Stake Authority Selection
The Tangle Network uses a cutting-edge selection system based on Proof-of-Stake, allowing anyone to participate in securing private cross-chain applications.
Learn More
2. Multi-Stage Governance for Signing
Tangle Network's governance system signs private data using a collaborative approach, ensuring both privacy and security.

Learn More
3. Efficient and Trustless Validation
The Tangle Network relies on a lightweight validation protocol that guarantees every message is securely verified without the need for trust between participants.
```
<img width="631" alt="Screenshot 2023-05-04 at 7 10 52 PM" src="https://user-images.githubusercontent.com/38070512/236355303-40ffc14f-b58a-468a-baa4-efbeb80c0d19.png">
`Relayers suggest changes to the network via the governance system by providing proof that the updates are based on accurate information from their corresponding blockchains. These updates are verified and placed in a queue, waiting for Tangle Network's private and decentralized authorities to review and approve them.`

<img width="279" alt="Screenshot 2023-05-04 at 7 14 32 PM" src="https://user-images.githubusercontent.com/38070512/236355599-e55c4d24-4900-4725-a57e-4da6fa651e97.png">
`General Messaging Passing & Public Bridges: Enables public and transparent cross-chain interactions, ensuring efficiency and security by using a frequently rotating TSS-based system that involves multiple participants working together.`

<img width="1057" alt="Screenshot 2023-05-04 at 7 15 06 PM" src="https://user-images.githubusercontent.com/38070512/236355644-fdc749fc-9ac5-4082-be99-79ff50e360a1.png">
Remove Kusama and Crowdloan items. We'll probs need to add to this.

**Comment by thomivy** [comment]
Need a section for the incentive campaign, or a separate page:

**Tangle Testnet Incentive Campaign**
As we prepare for the launch of the Tangle Network, we're excited to announce our Testnet Incentive Campaign! This program is designed to encourage users to explore, utilize, and improve the Tangle Network, contributing to the development of cutting-edge privacy tooling. By participating in various activities, users can earn points that will entitle them to a percentage of the Tangle Network's airdrop.

**Points Scheme**

| Activity                                           | Points    |
|----------------------------------------------------|-----------|
| Relay 1 tx/day for 1 week/month                    | 0         |
| Make 1 deposit over X amount                       | 0         |
| Make 1 withdraw                                    | 0         |
| Run a validator                                    | 1         |
| DKG Authority (get voted in)                       | 5         |
| Bug Bounty with PR Fix Submission                  | 50        |
| Deposit → Transfer → Withdraw                      | 10        |
| Vote in Governance                                 | 1         |
| Propose and Pass in Governance                     | 1         |
| Author a Protocol Extension                        | 3         |
| Scripts to make Transactions                       | 10        |
| Publish a video or tutorial on Tangle or Webb.     | 20        |
| Tweet about Webb                                   | 3         |
| Tweet a Semaphore identity w/ Webb                 | 20        |
| Tweet an ETH address or ENS domain                 | 15        |
| Tweet a hash of your address + a secret number     | 20        |
| Bug Report                                         | 10        |
| Use Case Concepts (Asset protocols, Maps, Identity, Social) | 10   |
| Creative Contribution — Have an idea for something that doesnt fit here? Show us! We’ll assign points based on merit. | Variable |

CTA: Join our Discord's Testnet channel to participate, report your contributions, and more. (JOIN)

**Comment by dutterbutter** [comment]
@vutuanlinh2k2 can you go through and update the COPY with the suggested updates [here](https://github.com/webb-tools/webb-dapp/issues/1137#issuecomment-1535550355).

**Comment by monaiuu** [comment]
I have updated the copy in figma wireframes in accordance to @thomivy comment above. Feel free to reference Figma for the updated copy: https://www.figma.com/file/jrtQ1Gvvb1kJdt7HXAkUX4/%F0%9F%AA%A2-Tangle-Website?node-id=794%3A215775&t=DNZ7vGUTOd4ztQWB-1

@vutuanlinh2k2

**Comment by thomivy** [comment]
<img width="2075" alt="Screenshot 2023-05-05 at 11 34 06 AM" src="https://user-images.githubusercontent.com/38070512/236515717-ea832750-140d-4302-a952-ae58238936b5.png">


This section has strange margins to the rest of the sections. Compare:
<img width="1668" alt="Screenshot 2023-05-05 at 11 39 45 AM" src="https://user-images.githubusercontent.com/38070512/236516749-dcfa0a46-fe59-4a70-bd6a-c333bd107790.png">

**Comment by monaiuu** [comment]
### Participation Mechanics Section Update

Please note that the Participation Mechanics section copy has been updated, please see to Figma for reference.
https://www.figma.com/file/jrtQ1Gvvb1kJdt7HXAkUX4/%F0%9F%AA%A2-Tangle-Website?node-id=643%3A178979&t=DNZ7vGUTOd4ztQWB-1

**Screenshot**
<img width="1218" alt="Screenshot 2023-05-05 at 1 13 18 PM" src="https://user-images.githubusercontent.com/109539270/236560022-0b11e309-01c4-4ad2-8833-bfe5e87dbe9e.png">

**Tasks**

- [ ] Update copy of Participation Mechanics Section to match with Figma
- [ ] Fix `Item` component to match with design (see below for current component)
<img width="364" alt="Screenshot 2023-05-05 at 1 15 56 PM" src="https://user-images.githubusercontent.com/109539270/236560970-5e39d309-41a1-4441-afef-5a9d2dd7bd9a.png">

**Comment by monaiuu** [comment]
I agree with @thomivy 's comment above regarding to the margins of the hero section. Can we ensure that when the website hits larger screen dimensions (i.e., above 1440px), the hero section is scaled appropriately so that the margins of the section remain consistent? 

Below is a view of how the hero section should behave when the screen hits larger screen dimensions. The example below is 2000px.

### Screenshot
<img width="1399" alt="Screenshot 2023-05-05 at 4 51 29 PM" src="https://user-images.githubusercontent.com/109539270/236586317-5f3f7e74-34e6-40eb-89c1-6cc87986d614.png">

Don't hesitate to reach out for any questions!

**Comment by thomivy** [comment]
I guess I don't understand why we're putting white margins on that hero section but not any other section.

**Comment by monaiuu** [comment]
Yes, we can certainly do without the white margins too. 

> I guess I don't understand why we're putting white margins on that hero section but not any other section.

**Comment by vutuanlinh2k2** [comment]
@dutterbutter @thomivy @monaiuu can you guys also check back with all the urls in buttons and links on the website so I can update them accordingly. 

My latest PR is to fix all those design issues mentioned above.
