### ISSUE TITLE
[TASK] Update/fix stats-dapp UI discrepancies 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1141]
## Overview

The below are a collection of issues that need to be address on the stats-dapp.

### Task Checklist

- [x] Remove tx hash column and reference to everywhere until implemented
- [x] Fix next, prev button in proposal detail drawer
- [x] Remove "Open Governance" chip
- [ ] Investigate / address math error on threshold voting (e.g. pass, abstain etc) 
- [x] Investigate why RefreshVote is never considered "SIGNED" 
- [x] Investigate why proposer details are not shown in the proposer table under proposal details drawer (see last screenshot)
- [x] Fix the proposal timeline component to improve/fix "IN ABOUT AN HR" display
- [x] Update proposal chart to conditionally render the time frame at the first data point (e.g. if no proposals in month 1, display chart from month 2)

### Screenshots
![CleanShot 2023-04-25 at 12 22 01](https://user-images.githubusercontent.com/29983536/234354795-f4916857-6756-4094-8578-b02b6dd7d00c.png)

![CleanShot 2023-04-25 at 12 24 34](https://user-images.githubusercontent.com/29983536/234355015-dcaa96f4-1f7e-4bac-a1dc-7e1d62e9e19d.png)

![CleanShot 2023-04-25 at 12 27 10](https://user-images.githubusercontent.com/29983536/234355520-eebd0c13-1749-4844-9631-53ac998a1cd8.png)

![CleanShot 2023-04-26 at 14 01 15](https://user-images.githubusercontent.com/29983536/234682147-5e4f7ab6-1ea3-45e8-8913-38ae7b57929f.png)

![CleanShot 2023-04-26 at 14 01 09](https://user-images.githubusercontent.com/29983536/234682157-4e34a02f-5931-40fa-8c00-3600aa34d55e.png)

**Comment by devpavan04** [comment]
Closing this in favour of

- #1144 
- #1145 
- #1149 
- #1154
