### ISSUE TITLE
[TASK] Stats Improvements and Fixes

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1169]
### Overview

The below are a collection of issues/requirements that need to be addressed on the stats dapp.

### Task Checklist

- [x] #1253
- [x] #1254

https://github.com/webb-tools/webb-dapp/assets/53374218/921151e6-89db-4868-a4ed-7d74f69496b7
- [x] If in light mode, clicking “View History” goes to dark mode and makes going back and forth buggier.

https://github.com/webb-tools/webb-dapp/assets/53374218/2a03f69c-2f36-492d-bdb3-940b4b8d1543
- [x] Network threshold history chart should be fixed. It should have no decimal values. The thresholds are integers, we should fix that so its purely 1,2,3,4,5,6… Clicking "All Time" messes up graph x-axis coordinates too.
![CleanShot 2023-05-11 at 13 28 11](https://github.com/webb-tools/webb-dapp/assets/53374218/190dbc81-7cc5-41d9-9d8c-2d796f192376)
- [x] Update the font size of details in proposal details page.
![CleanShot 2023-05-11 at 13 31 08](https://github.com/webb-tools/webb-dapp/assets/53374218/4396f433-fdab-4397-9e16-1f73f2527dc0)
- [x] Remove these texts
![CleanShot 2023-05-11 at 13 34 08](https://github.com/webb-tools/webb-dapp/assets/53374218/d26a70da-1bbd-419f-afe8-85298f6dc79d)
![CleanShot 2023-05-11 at 13 33 15](https://github.com/webb-tools/webb-dapp/assets/53374218/45bba7bd-a78a-4de1-8ab2-6f94dcb85c7c)
![CleanShot 2023-05-11 at 13 32 57](https://github.com/webb-tools/webb-dapp/assets/53374218/145e6b8c-ead3-4fa7-82ec-e00a4bda218b)
- [x] Proposal status is not showing as removed.
![CleanShot 2023-05-11 at 13 47 03](https://github.com/webb-tools/webb-dapp/assets/53374218/a717b2dd-dd84-460b-b8d7-e36b7725d5f6)
- [x] Font size too big
![CleanShot 2023-05-12 at 10 03 46](https://github.com/webb-tools/webb-dapp/assets/53374218/b04834ec-ed78-4157-a66c-6481a6c9f882)
- [x] Fix filter font size.
![CleanShot 2023-05-11 at 13 06 22](https://github.com/webb-tools/webb-dapp/assets/53374218/04b2242b-8ec9-4e6f-96bd-4a6b4408dd07)

**Comment by devpavan04** [comment]
Closing in favour of #1144 #1149 #1154 #1206 #1224 #1247 #1266
