### ISSUE TITLE
[CHECKLIST] Hubble bridge improvements 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1183]
## Overview

We have received a lot of good feedback on the Hubble bridge that we want to action with improvements. 

### Task Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/1124
- [x] https://github.com/webb-tools/webb-dapp/issues/732
- [ ] https://github.com/webb-tools/webb-dapp/issues/1180
- [x] https://github.com/webb-tools/webb-dapp/issues/1181
- [x] https://github.com/webb-tools/webb-dapp/issues/1182

**Comment by AtelyPham** [comment]
Moved remaining tasks to https://github.com/webb-tools/webb-dapp/issues/1620.
