### ISSUE TITLE
[FEAT] Add Side Navigation Component to Unify Webb dApps

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1241]
## Overview

As Webb Products continues to expand, there is a need to introduce a side navigation component to create a unified navigation experience across the product ecosystem. This issue aims to provide the necessary information and assets for developing the side navigation component.

### Information Hierarchy

- **Ecosystem:** this section displays and centralizes all Webb’s tools, features, support, and documentation. We could also introduce the vision and value proposition for the Webb Ecosystem here.
- **Account:** this section allows users to manage their "Webb Account," including their account info (public key), shielded balances (available spend notes), address book, help and support, and account settings (including the option to purge account).
- **Hubble:**
    - **Bridge:** private cross-chain asset bridging.
    - **Wrap/Unwrap:** convert webb assets into native assets. 
    - **Explorer:** view shielded pools & data across networks.
    - **Faucet:** access testnet tokens to learn & experiment with Hubble.
- **Tangle Network:**
    - **Faucet:** access tangle testnet tokens,
    - **DKG explorer:** view DKG network status. ****
    - **Homepage:** learn about Tangle network via landing page.

### Tasks

- [x] Review updated design system to access side navigation component & familiarize with different states/variants
- [x] Remove top navigation component in favor of side navigation component on webb dapps (will link updated component in a separate issue)
- [x] Add side navigation components to webb UI kit

### Figma Link (Design System)
https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=5073%3A137026&t=uHKCFH4FOLsP12kS-1

### Screenshots
<img width="1698" alt="Screenshot 2023-06-09 at 9 40 34 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/730954dc-50dc-4a13-be60-650b62b163d9">

![Image](https://github.com/webb-tools/webb-experiences/assets/109539270/78aa354c-7ce2-4df2-8ce5-f45df082165a)

### Notes
For more information on this task, feel free to access the notion doc below:
https://www.notion.so/hicommonwealth/DOC-Side-Navigation-Evaluation-187a5d958b0746f4b332c5e19e0328bf?pvs=4
