### ISSUE TITLE
[FEAT] Enable users to request refund in Transfer

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1244]
## Handoff

Based on discussion with @AtelyPham (see [thread](https://hicommonwealth.slack.com/archives/C03LMM80SVA/p1683836910646129?thread_ts=1683835671.118019&cid=C03LMM80SVA)) on requesting refund in transfer flow on Hubble Bridge, we need to enable the [refund feature](https://www.notion.so/hicommonwealth/Feature-12-Refund-Support-85614959ab5d438393184e02ef555f01?pvs=4).

The proposed design follows the logic of requesting refund flow in withdrawal, but with an additional input field rendered upon checking the 'request refund' checkbox. This input field allows users to input the wallet address of the refund recipient.

### Tasks & Screenshots [Transfer]

- [ ] Add `checkbox` component in to allow users to enable refund. Similar to withdrawal flow, the component should remain disabled until user has selected a relayer. 
- [ ] Add `input field` component to allow users to input receiver's wallet address **after** user has enabled refund by selecting checkbox
- [ ] Display refund receiver's wallet address in confirmation screen.

![Image](https://github.com/webb-tools/webb-experiences/assets/109539270/65c974b8-b83b-4987-96e5-ab0e034c9ba7)

- [ ] Add `tooltip` component to inform users about refund recipient input field

![Image](https://github.com/webb-tools/webb-experiences/assets/109539270/8f0e8c4f-fc1f-4b44-9ed8-f45d79f294d5)

- [ ] Add `tooltip` component to allow users to review the conversion rate of the refund amount

![Image](https://github.com/webb-tools/webb-experiences/assets/109539270/166de187-9611-4c3c-b621-60981efcdb0a)

### Figma Access:
Please refer to below file for the added refund feature in transfer flow. (see light theme)
https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?type=design&node-id=3570%3A374226&t=AtIQbV2ZKR1xr6U0-1

Note that the purpose of shipping this UI is to test out the implementation, as we push for the V2 Hubble Bridge release, the refund flow UI may change to accommodate for the bridge card update, but logic should remain the same.

**Comment by monaiuu** [comment]
@drewstone 

Please review this issue and assign the priority level for shipping this feature.

**Comment by drewstone** [comment]
Awesome sounds great. Let’s meet tomorrow and go over this more in depth
too. One thing to note is the refund recipient would be a 20 byte address
for EVM chains and 32 byte account for substrate. We’ll want error states
if we don’t have for that as well.

Since refunds are also primarily geared towards funding new accounts we can
do a query to the chain to check whether an address has any prior tx
history. Warning states for these things could be useful, such as “the
address you’re refunding to has a TX history… be aware this could improve
linkability…”

**Comment by monaiuu** [comment]
### Note

This issue is _**on-hold*_* until we launch the V2 Bridge Cards display.
