### ISSUE TITLE
[TASK] Create the Shielded Assets table with filter functionality

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1303]
## Description
This feature will enable users to view and filter shielded assets based on specific criteria. The task involves developing the necessary frontend and backend components to implement the table and its associated filtering capabilities.

![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/20f2c040-20d1-4ad3-aa0e-2a024a5e1d79)

### Tasks:
- [ ] Implement table header components for Shielded Assets, Pool Type, Composition, 24H Deposits, TVL, and Chains.
- [ ] Implement table row component to display the above details (this should be using table row component from webb UI kit)
- [ ] All items within table rows should also be using components from webb UI kit if applicable (chip, token icon, chain icon)
- [ ] Implement pagination component
- [ ] Implement filter button and dropdown component (default state: display all) (user can uncheck specific networks to filter through which assets to display)
- [ ] Develop the backend API endpoints to retrieve the shielded asset data and support filtering based on user-selected criteria.

Note: At current state, all pool type will be 'single asset', 'multi asset' chip will be applicable once we have MASPs (multi assets shielded pools) deployed. 

If any additional tasks may be involved in implementing this table, please mention them below. 

Figma Link:
https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=814%3A128188&mode=dev

**Comment by drewstone** [comment]
Linked to: [#1058](https://github.com/webb-tools/webb-dapp/issues/1058)

**Comment by vutuanlinh2k2** [comment]
@monaiuu, in the composition column, is the content of each row the list of token icons?

**Comment by vutuanlinh2k2** [comment]
Close this since this is duplicate with #1306

**Comment by vutuanlinh2k2** [comment]
Close this since this is duplicate with #1306
