### ISSUE TITLE
[TASK] Create the Shielded pools table with filter functionality

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1304]

**Comment by drewstone** [comment]
Linked to: [#1058](https://github.com/webb-tools/webb-dapp/issues/1058)

**Comment by monaiuu** [comment]
## Description
<img width="1160" alt="Screenshot 2023-06-05 at 9 58 12 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/d44e9374-d299-4d1a-b7b6-44aca03585db">

This feature will enable users to view and filter shielded assets based on specific criteria. The task involves developing the necessary frontend and backend components to implement the table and its associated filtering capabilities.

### Tasks:
- [ ] Implement table header components for Shielded Assets, Pool Type, Composition, 24H Deposits, TVL, and Chains.
- [ ] Implement table row component to display the above details (this should be using table row component from webb UI kit)
- [ ] All items within table rows should also be using components from webb UI kit if applicable (chip, token icon, chain icon)
- [ ] Implement pagination component
- [ ] Implement filter button and dropdown component (default state: display all) (user can uncheck specific networks to filter through which assets to display)
- [ ] Develop the backend API endpoints to retrieve the shielded asset data and support filtering based on user-selected criteria.

Note: At current state, all pool type will be 'single asset', 'multi asset' chip will be applicable once we have MASPs (multi assets shielded pools). 

If any additional tasks may be involved in implementing this table, please mention them below.
