### ISSUE TITLE
[TASK] Create the Shielded pools table with filter functionality

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1306]
## Description

This task is similar to https://github.com/webb-tools/webb-dapp/issues/1303 This will enable users to view and filter shielded pools based on specific criteria. The task involves developing the necessary frontend and backend components to implement the table and its associated filtering capabilities.

<img width="734" alt="Screenshot 2023-06-05 at 10 26 07 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a2f6b259-3712-4e5d-9510-0be5d8781f68">

### Tasks:
- [ ] Implement table header components for Shielded Pools, Pool Type, Token #, 24H Deposits, TVL, and Chains.
- [ ] Implement table row component to display the above details (this should be using table row component from webb UI kit)
- [ ] All items within table rows should also be using components from webb UI kit if applicable (chip, token icon, chain icon)
- [ ] Implement pagination component
- [ ] Implement filter button and dropdown component (default state: display all) (user can uncheck specific networks to filter through which assets to display)
- [ ] Develop the backend API endpoints to retrieve the shielded pools data and support filtering based on user-selected criteria.

Note: At current state, all pool type will be 'single asset', 'multi asset' chip will be applicable once we have MASPs (multi assets shielded pools) deployed. 

If any additional tasks may be involved in implementing this table, please mention them below.
