### ISSUE TITLE
[TASK] Update Token Config and Deploy the Faucet UI

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1318]
### Overview

We need to setup a public domain and the new deployment for the faucet UI on Netlify. Also updating the supported tokens on the faucet app config to interact with the faucet backend.

### Task checklist

- [x] Update the supported tokens and chains in the faucet app to interact with the faucet backend
- [x] Create a basic CI/lints for the faucet app
- [x] Update Netlify config for new domain and environment variables.
- [x] Test everything once it is done.

**Comment by AtelyPham** [comment]
Once this https://github.com/webb-tools/webb-faucet/issues/11 is resolved, we need to assign the faucet backend url in the environment variable, right now, it is default to `http://127.0.0.1:8000`
