### ISSUE TITLE
[CHECKLIST] Update Stats Dapp to Accommodate Batched Proposals

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1337]
## Description
The proposal signing process is being modified to support batched signing, where a signed proposal batch can include more than one proposal. As a result, it is necessary to modify the table items in the Stats Dapp to display batched proposals. 

To accommodate for the above change, please update the DKG stats page based on the following tasks:

# Proposals Page
![Image](https://user-images.githubusercontent.com/109539270/245239889-797dd5d8-bd2d-4f2c-bb4d-79aefe7537d5.png)

### Tasks
- [x] #1438
- [x] #1439
- [x] #1440
![Image](https://user-images.githubusercontent.com/109539270/245239289-37be2b8a-8557-4467-89bc-74d59c9192b2.png)
- [x] Display stacked badges to display multiple proposals in table rows
- [x] Update any appropriate color legends to the stacked graphs above 
<img width="283" alt="Screenshot 2023-06-12 at 8 56 17 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a46c5c4d-1e0f-44ed-81d6-e2403b9e8f01">

--

# Proposal Details Page
![Image](https://user-images.githubusercontent.com/109539270/245240262-74563a6a-3a92-457b-b2a1-bd1f3450d587.png)

### Tasks
- [ ] Display various kinds of proposals and render the # of proposals accordingly
- [ ] Add the display of BatchID, and use chip component to display #
- [ ] Add proposal kind & signature next to 'Proposal Details' to identify each proposal in the batch
- [ ] Add the ability for users to toggle between different proposals details within the batch and view their respective details by selecting prev & next buttons. 
- [ ] Ensure the updates above are applied appropriately on the side panel view <img width="464" alt="Screenshot 2023-06-12 at 8 48 38 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/b1dee355-43ab-4a99-9628-961b970a0a60">

### Notes

- The figma wireframes for DKG stats in both light and dark themes have been updated to accommodate for the latest changes, please reference accordingly:
https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?type=design&node-id=1152%3A113488&t=iHSAWtUfXHrb3R9h-1
- Note: while batches may contain multiple proposals, they will not include `RefreshVote` or `ProposerSetUpdate` proposals.

**Comment by monaiuu** [comment]
@devpavan04 Here's the dev mode link 
https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?type=design&node-id=1213%3A229739&mode=dev

**Comment by drewstone** [comment]
Basic blocker for merging these completed tasks to `master/main` is that we need the stats backend/graphQL updated as well.

**Comment by AtelyPham** [comment]
The remaining tasks are moved into https://github.com/webb-tools/webb-dapp/issues/1441.
