### ISSUE TITLE
[CHECKLIST] Implement the end-to-end flows of Hubble Bridge V2

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1400]
## Overview

The Hubble Bridge V2 is ready for handoff. For all components update and implementation, see this [issue](https://github.com/webb-tools/webb-dapp/issues/1398) for handoff. This current issue outlines the significant feature updates that are part of the migration from Hubble Bridge V1 to V2. These updates go beyond cosmetic and visual enhancements, introducing new functionalities and improvements to the user experience.

For the general usage for Hubble Bridge V2, please refer to this [Usage Guide](https://www.notion.so/hicommonwealth/Hubble-Bridge-V2-Usage-Guides-ee63d256f196486ea480b01083a14429?pvs=4). 

## Checklist
- [x] #1519
- [x] #1402
- [x] #1401
- [x] #1418
- [x] #1404
- [ ] #1409
- [ ] #1425
- [x] #1417
- [ ] #1449
- [x] [TASK] Update shielded balance display in transfer & withdrawal
- [x] [TASK] Indicate remaining shielded balance of connected chain
- [x] [TASK] Implement end-to-end deposit flow
- [x] [TASK] Implement end-to-end transfer flow
- [x] [TASK] Implement end-to-end withdrawal flow

**Comment by AtelyPham** [comment]
I've assigned 8 points to the tasks that aren't considered issues, as they were resolved when migrating to V2. I'm going to close and unpin this checklist since we have the remaining tasks identified as open issues and have successfully migrated to V2.
