### ISSUE TITLE
[CHECKLIST] DKG Stats Improvements

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1552]
## Checklist
Please reference below for the list of UI improvements required for Tangle Explorer/DKG stats. The UI audit was conducted via this link: https://www.stats-dev.webb.tools/#/keys

### **Keys Overview & Details Page**
- [x] Update copy `See Full Details` to `View Details` (so that it is consistent with `View History` in authorities page)
![Image](https://user-images.githubusercontent.com/109539270/261608613-9d09d6f8-8866-4434-b087-5ff53bc9eb29.png)
- [x] Remove green (+) cursor pointer when hovering over avatars 
- [x] Update placement of the copy button, should be horizontal to`Compressed Key` label ([keycard](https://webb-tools.github.io/webb-dapp/?path=/docs/design-system-organisms-keycard--docs) component)

### **Authorities Overview & Details Page**

- [x] Update tooltip copy for `Network Thresholds` shown below; remove tooltips for `Keygen` and `Signature`. 
![Image](https://user-images.githubusercontent.com/109539270/261624119-414187a5-1f2b-4cc8-a985-52da2005f0dc.png)

- [x] No label next to `0x02f33...f1943`; add `Key:` label or key icon so users know what this is.
![Image](https://user-images.githubusercontent.com/109539270/261625129-d5c2fb3e-e947-4bd5-ad34-077f996f75cc.png)

- [x] Excessive decimal places; keep them reasonable to 1 or 2 decimal places. 
![Image](https://user-images.githubusercontent.com/109539270/261609378-8a39ec4c-9a93-49f6-893c-250b955ab7c1.png)

### **Proposals Overview & Details Page**

- [x] Update tooltip copy to `Proposals Status` shown below; remove tooltips required for `Proposal Threshold` & `Proposers`. 
![Image](https://user-images.githubusercontent.com/109539270/261636567-b634483c-a442-463e-a866-7709ce78c6a9.png)

### **General**
- [x] Update background color for all filter dropdown in dark theme to `monochrome/180` for consistency with top nav dropdown component
![Image](https://user-images.githubusercontent.com/109539270/261626635-d8dbc9f7-506d-4388-9324-a57753d90d55.png)
- [x] Update all tooltips text size to `Body/03` so it is not overly large and distracting.
- [x] Update Documentation link to [ Stats dApp doc site](https://docs.webb.tools/docs/projects/stats-dapp/overview/) rather than the general doc site; so that users do not have to look within the doc site to learn about the DKG stats dapp.
![Image](https://user-images.githubusercontent.com/109539270/261632374-72f1c706-2c07-4223-8e05-d366d929c170.png)
