### ISSUE TITLE
[CHECKLIST] QA Hubble Bridge

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1619]
### Overview
This checklist enumerates issues encountered on the `Hubble Bridge dApp` as part of a QA process starting on September 13, 2023.

### Notes:

- When reporting an issue, please create it as a checklist item and refrain from converting it into an issue immediately. If the issue can be justified, the appropriate developer will comment on it below, and discussions can take place before marking it as resolved, if necessary.
- Please create an issue under your respective section (using your username) for easy tracking of the number of issues identified by each team member.
- Please add necessary screenshots and screen recordings for easy understanding.
- Ensure that when reporting an issue, it has not already been logged.
- If an issue can be resolved by making changes in the `webb-graphql` repository, please provide a link to that PR here before marking the item as completed.

### By Tin (@AtelyPham)

- [ ] https://github.com/webb-tools/webb-dapp/issues/1653
- [ ] https://github.com/webb-tools/webb-dapp/issues/1180

### By Pavan (@devpavan04)

- [x] #1668 
- [x] #1670 

### By Linh (@vutuanlinh2k2)

- [x] https://github.com/webb-tools/webb-dapp/issues/1645

### By Shady (@shekohex)

- [ ] https://github.com/webb-tools/webb-dapp/issues/1657
- [x] https://github.com/webb-tools/webb-dapp/issues/1658
- [x] https://github.com/webb-tools/webb-dapp/issues/1659
- [x] https://github.com/webb-tools/webb-dapp/issues/1660
- [x] #1692
- [x] #1693

### By Mona (@monaiuu)
- [x] https://github.com/webb-tools/webb-dapp/issues/1674
- [x] https://github.com/webb-tools/webb-experiences/issues/206
- [x] https://github.com/webb-tools/webb-dapp/issues/1699
- [x] https://github.com/webb-tools/webb-dapp/issues/1700
- [x] https://github.com/webb-tools/webb-dapp/issues/1710
- [x] https://github.com/webb-tools/webb-dapp/issues/1711
- [x] https://github.com/webb-tools/webb-dapp/issues/1727

### By Drew (@drewstone)
- [x] https://github.com/webb-tools/webb-dapp/issues/1690
- [ ] https://github.com/webb-tools/webb-dapp/issues/1683

**Comment by monaiuu** [comment]
Above issue has been created here: https://github.com/webb-tools/webb-dapp/issues/1615

**Comment by AtelyPham** [comment]
### Linh (@vutuanlinh2k2)

- [ ] https://github.com/webb-tools/webb-dapp/issues/1645

**Comment by AtelyPham** [comment]
- [ ] Should the default chain with the active chain when users click `Connect Wallet`
- [ ] Switching account does not change note account on the dApp
- [ ] Hide the gear setting button
- [ ] Chip for token and address shouldn’t be uppercase

**Comment by drewstone** [comment]
@AtelyPham can we also add a task here for moving the current tx confirmation dropdown to the right to be on the left of the hamburger menu?
