### ISSUE TITLE
[CHECKLIST] EVM Staking UI

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1671]
# Overview
The EVM users do not have a UI to interact with the staking system. This would be the first step to building it. It should be fairly straightforward. We need to:
- Display the list of validators similar to Polkadot Apps.
- Display a nomination page (also called "Accounts" on Polkadot Apps)
- Allow users to click create nominator accounts (and stash accounts generally).
- Allow users to select validators to nominate and bond funds.
- Execute all transactions through the EVM. 

The implementor of the tasks in this checklist MUST go through the flows on Polkadot Apps. If you haven't done so before, **_please do that_**. It's pointless to have you implement without spending the 5 minutes necessary to actually use the existing functionality so you get a feel for it.

## Example UIs
- https://polkadot.js.org/apps/?rpc=wss://rpc.tangle.tools#/staking
- https://www.dtmb.xyz/moonbeam/collators

## Checklist
- [x] #1677 
- [x] #1776
- [x] #1678 
- [x] #1766
- [x] #1764
- [x] #1763
- [x] #1680
- [x] #1679  
- [x] https://github.com/webb-tools/webb-dapp/issues/1895
- [x] https://github.com/webb-tools/webb-dapp/issues/1900
- [x] #1681
- [x] https://github.com/webb-tools/webb-dapp/issues/1896
- [x] https://github.com/webb-tools/webb-dapp/issues/1910
- [ ]  https://github.com/webb-tools/webb-dapp/issues/1907
- [x] #1926
- [x] #1927

### Thoughts on components to add and reusability.
The components here should mostly exist in our library. Some things that might not exist are the validator selection in the nominator flow, which is like a 2 panel multi-selection.

Otherwise, there is a lot of redundancy. Every action on Apps UI usually ends with an "authorize transaction"/"submit transaction" panel, we could add this but its not totally necessary (we can go directly to submission).
