### ISSUE TITLE
[TASK] Create validator list in tangle-app staking page

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1676]
# Overview
In order to provide simple staking functionality to EVM users, we must list the validators they can nominate. This is the first step.

## Tasks
- [ ] Use the polkadot API to get all possible validators.
- [ ] For each validator, identify if they are active (in current session), pending (in next session), inactive (not in active session).
- [ ] For each validator, grab their commission.
- [ ] For each validator, grab their total stake, own stake, and nominated stake.
- [ ] For each validator, grab their last block.
- [ ] Display the validator list and in each row display the validator's data.

![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/49824e98-a85c-4934-9aa2-f10eeb214c6f)

**Comment by monaiuu** [comment]
This issue has been created here: https://github.com/webb-tools/webb-dapp/issues/1766

**Comment by devpavan04** [comment]
@monaiuu @AtelyPham Closing this as we have another issue created for this here - #1766 
Yes I'm currently working on the validator tables.
