### ISSUE TITLE
[TASK] List active nominations and add nomination re-setting

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1681]
# Overview
The nominations should be listed in the Accounts page. From there I should see some data about my nomination, such as the validators I am nominating, the controller account, the reward destination, and the amount bonded.

I should also be able to _stop_ my nomination and update the settings of my nomination shown below.

## Tasks
- [ ] Create a list for my current nomination.
- [ ] Add the stop button
- [ ] Add hamburger menu to row item for extra configuration

### Nomination list
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/2a17fde2-e18d-48f8-bea8-92bff2c265b8)

### Stop button
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/05bf67ed-3c62-4d2f-b3d0-9444b9733b28)

### Extra configuration settings (hamburger menu)
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/be7ac567-b5bb-4a11-afbc-c1f1b03a24c6)

### Bond more funds
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/2210ca76-d16f-4e4a-b0ad-c99c92fb05f7)

### Unbond funds
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/04209d69-8575-4944-868e-c7f1977e0079)

### Change reward destination
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/c9876abe-49e3-4964-8c56-f5c9303e3af5)

### Reset nominees (nominate new validators)
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/b7871123-427e-45e2-99eb-59644de71c78)

### Notes / Consideration
Since we are doing this for the EVM the table will very likely have only 1 row in it. We can potentially ditch the row design and choose something to fill the page more (comment below with ideas/discuss with @drewstone).

**Comment by monaiuu** [comment]
## Handoff
(to do: add details & screenshots)

Actions Settings:

- [ ] Add Stake: Allow users to add more tokens to their existing stake. This should open a modal where they can specify the amount and confirm the action.
- [ ] Unbond Funds: Provide an option for users to start the unbonding process for a portion or all of their staked tokens. This would have a waiting period associated.
- [ ] Remove Stake: Allow users to remove their stake from a validator.
- [ ] Change Reward Destination: Let users specify a different address where their staking rewards should be sent.
- [ ] Update Validator: If users wish to change their validator preference, provide an option to do so. Involvea choosing a new validator and potentially re-staking or moving their stake.

### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Governance?type=design&node-id=1333%3A143596&mode=dev)

### Screenshot
