### ISSUE TITLE
[TASK] Update faucet SEO metadata & container texts

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1783]
## Description
With the latest update to faucet, enhance brand consistency by updating the SEO metadata and container texts in the faucet UI. 

### Tasks:
**SEO Metadata Updates:**
- [ ] Favicon: Replace the current favicon with the Tangle favicon.
- [ ] Title Tag: Change the title tag from 'Webb Faucet' to 'Tangle Network Faucet'.
- [ ] Meta Description: Update the meta description to: 

> Receive Test Tokens on Devnet and Testnet supported by Tangle Network and Webb Protocol for development and experimental purposes.

**Container Text Updates:**

- [ ] Faucet Title: Update the faucet title from 'Hubble Bridge Faucet' to 'Tangle Network Faucet'.
- [ ] Description Text: Replace the current description with the following:
> Receive Test Tokens on Devnet and Testnet supported by Tangle Network and Webb Protocol for development and experimental purposes. Follow @webbprotocol on Twitter and authenticate yourself by clicking the 'Login with Twitter' below to start the process. *You can claim faucet every 24 hours on each network.
