### ISSUE TITLE
[TASK] Add ability for users to update projects/circuits with additional details

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#1905]
## Tasks
- [ ] Provide users with the option to enrich circuit data with additional descriptions, number of constraints, inputs, outputs, and other pertinent details.
- [ ] Have fields for users to input or edit further project details such as the official website, documentation link, social media handles, and tagging for categorization.
- [ ] Make API call(s), as well as backend API route to be able to update changes on the backend
- [ ] This can only be done by authenticated users; and they must be the creators of the project/circuit entry that they are trying to edit

**Additional notes**
* Need to consider how to mitigate users with malicious intent, who might provide false information (websites, social media handles, etc.) and associate them with official projects, perhaps by having some sort of 'report' action.
