### ISSUE TITLE
[CHECKLIST] Fixes to Leaderboard

### ISSUE THREAD

**Issue by thomivy** [webb-tools/webb-dapp#1956]
- [ ] Match top nav to tangle.tools.
- [ ] Remove Request Points BTN
- [ ] Update Footer Link for Twitter to `https://twitter.com/tangle_network`
- [ ] Update Documentation link to `https://docs.tangle.tools`
- [ ] Update Source Code Link to `https://github.com/webb-tools/tangle`
- [ ] Update Whitepaper Link to `https://github.com/webb-tools/tangle/blob/main/Tangle_Network_Whitepaper_V1.pdf`
- [ ] Update Brand Kit Link to `https://www.tangle.tools/press-kit`
- [ ] Do the same for the visual icon social buttons at bottom.
