### ISSUE TITLE
[CHECKLIST] Implement Tangle Network Service Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1975]
## Objective
The Tangle Network Service Dashboard serves as a centralized page for users to view and understand the full scope of Multi-Party Computation (MPC) services offered by Tangle Network. The page should display a variety of information including the distribution of MPC roles, protocol earnings over time, current era data, and the list of active services and participants. Additionally, this page will act as a starting point for validators to engage in restaking activities.

### Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/1978
- [x] https://github.com/webb-tools/webb-dapp/issues/1982
- [x] https://github.com/webb-tools/webb-dapp/issues/1983
- [x] https://github.com/webb-tools/webb-dapp/issues/2031
- [x] https://github.com/webb-tools/webb-dapp/issues/2060

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/4b821e23-1118-4e2a-bed6-4f4ff692b929)
