### ISSUE TITLE
[CHECKLIST] Implement Tangle Network Service Details Page

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1977]
## Description
Implement Service Details Page for Tangle Network's Phase 1 services. This page will allow users to delve into each service and explore the associated Phase 2 jobs. The page should provide comprehensive details including the service's start and end times, the keys used, the list of jobs, the signing rules, and the participant list.

### Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/1979
- [x] https://github.com/webb-tools/webb-dapp/issues/1980
- [x] https://github.com/webb-tools/webb-dapp/issues/1981
- [x] https://github.com/webb-tools/webb-dapp/issues/2047

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/0856f955-f885-4475-ba9b-4212a641381d)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/806cd267-5f64-4f7b-9f26-6cfdb1377850)

### Dependency:
https://github.com/webb-tools/webb-dapp/issues/1975

**Comment by vutuanlinh2k2** [comment]
All tasks have been done
