### ISSUE TITLE
[CHECKLIST] End-to-End Flows for Restaking UI in Tangle Network

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1986]
## Overview
The Restake UI for Tangle Network allows validators to opt into various service roles, either through an Independent or Shared Restake Profile. The UI should facilitate profile setup, updates, and provide clear information about restaking activities, especially regarding active roles, services and restake amount adjustments. 

## Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/1987
- [x] https://github.com/webb-tools/webb-dapp/issues/1990
- [x] https://github.com/webb-tools/webb-dapp/issues/1988
- [x] https://github.com/webb-tools/webb-dapp/issues/1989
- [x] https://github.com/webb-tools/webb-dapp/issues/1991
- [x] https://github.com/webb-tools/webb-dapp/issues/1993
- [ ] #1994
- [ ] #1995
- [ ] Create/update profile modal: `What's the difference?` button needs a link: https://docs.tangle.tools/docs/services/service-provider/#independent-vs-shared-restaking

**Comment by yurixander** [comment]
@vutuanlinh2k2 @monaiuu Do we have some issues tracking the implementation of the logic for the restaking dashboard? I can't seem to find them. If we do, it would be a good idea to include them on this checklist.

**Comment by monaiuu** [comment]
> @vutuanlinh2k2 @monaiuu Do we have some issues tracking the implementation of the _logic_ for the restaking dashboard? I can't seem to find them. If we do, it would be a good idea to include them on this checklist, or create a checklist for them.

I do not believe so, will be good to do as suggested.
