### ISSUE TITLE
[CHECKLIST] Tangle Account Page UI Audit

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2021]
## Checklist
Below are the checklist items based on audit session with @yurixander for https://app.tangle.tools/account
- [x] Update Account Summary Card Logo:
  - [x] Replace the current account card logo with the new version.
  - [x] Ensure the logo adapts for the light theme appropriately.

- [x] Account Summary Card Layout:
  - [x] Implement a minimum width of approximately 755px (tbd) to ensure card size responsiveness view.
  - [x] Below this width, stack components vertically and expand them to fill the space.

- [x] Manage Balances Table:
  - [x] Hide balances in Manage Balances Table to match the total balance's hidden state.
  - [x] Replace local chips with Webb UI's chip (specifically, use purple chips).
  - [x] Increase padding at the top table row items to align with Figma designs in locked balances container.

- [x] Payouts Button Functionality:
  - [x] Enhance the 'Payouts' button to navigate to the 'EVM Staking' page and automatically select the 'Payouts' tab.
