### ISSUE TITLE
[CHECKLIST] Tangle Airdrop Claims Page UI Audit

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2023]
## Checklist
Below are the UI checklist items based on audit session with @yurixander and sprint kickoff meeting feedback for https://app.tangle.tools/claim for Tangle's Airdrop Claim Page.

- [x] UI bug when changing claiming account, remove flicker.

- [x] Claim Container:
  - [x] Apply GlassCard's gradient background styling to the entire Claim Airdrop container.
  - [x] Adjust padding within containers for consistency, especially on mobile viewports.

- [x] Recipient Input Fields:
  - Fix text overflow in recipient inputs on mobile breakpoints.

- [x] Improve error alert and display
  - Remove `Requested resource not available` alert display when on EVM, should be consistent to Substrate where a dropdown displays rather alert component. 
  ![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/91386692-db9a-451e-af0b-6f1475d23e4f)
  ![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/96cda0dd-ef6e-468e-9719-8255b6631f49)

- [x] Change`Try Again` button to `Try Another Account`
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/bba535e3-b627-4c0f-8688-83736f572704)
 

- [x] Copy: 
  - Correct and update the FAQ section content. @monaiuu 
  - Improve the copy for the entire Airdrop Claims page (remove redundancies) @monaiuu 
  - Delete all mention of 'crowdloan'

**Comment by yurixander** [comment]
>  Pop up connect wallet modal when selecting Try Again button, currently selecting the button does not render anything.

I think the purpose of the `Try Again` is to re-check eligibility, instead of popping up a modal (at least in the current implementation). The reason why nothing happens, is because eligibility doesn't change even after re-checking (as expected).

I think we have two options here:
1. Remove the functionality to re-check, as I believe that Airdrop eligibility does not change after genesis (ie. never changes).
2. Change the button to actually open a switch wallet modal, and make the button's label something like `Try with another account`

Thoughts? @monaiuu

**Comment by yurixander** [comment]
> Remove Requested resource not available alert display when on EVM, should be consistent to Substrate where a dropdown displays rather alert component.

This doesn't seem to be happening to me. Maybe the error was occurring because the local node wasn't running? @monaiuu

**Comment by monaiuu** [comment]
> > Pop up connect wallet modal when selecting Try Again button, currently selecting the button does not render anything.
> 
> I've checked the code, and the purpose of the `Try Again` is to re-check eligibility, instead of popping up a modal (at least in the current implementation). The reason why nothing happens, is because eligibility doesn't change even after re-checking (as expected).
> 
> I think we have two options here:
> 
> 1. Remove the functionality to re-check, as I believe that Airdrop eligibility does not change after genesis (ie. never changes).
> 2. Change the button to actually open a switch wallet modal, and make the button's label something like `Try with another account`
> 
> Thoughts? @monaiuu
> 
> ![Screenshot @Visual Studio Code](https://private-user-images.githubusercontent.com/101931215/305680032-1d37c93a-9b8a-4674-b976-86331364e686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA5MjUsIm5iZiI6MTcwODQ0MDYyNSwicGF0aCI6Ii8xMDE5MzEyMTUvMzA1NjgwMDMyLTFkMzdjOTNhLTliOGEtNDY3NC1iOTc2LTg2MzMxMzY0ZTY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNDUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGQ3Mzk5ODExZGRjMTgyNWVmZjdhNDdjNzI4ZWY4ZmZjZmYyYjU0ZTA2MjY1MDE1NmI3YWM3MTA2OWMxNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lGqcfCzMvDcWDkJnfM96eC9Iy0ZAxxFBqQufrJVHm3o)

Yes I agree, let's go with `Try Another Account` to open a switch wallet modal.
