### ISSUE TITLE
[TASK] Improve modal positioning in mobile breakpoints

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2082]
Currently they are always centered on the screen, but for mobile breakpoints we could place them at the bottom and set a max-height + scroll for them, to give a better "[Bottom-sheet](https://www.google.com/search?q=bottom+sheet&tbm=isch)" mobile-like experience.

### Tasks
- [ ] On mobile breakpoints, place all modals to be attach to the bottom of the screen.
- [ ] Consider adding a `max-height` to prevent the modal from taking up the entire screen, and allowing the user to scroll.
- [ ] Check all modals for responsiveness, and ensure they properly handle mobile breakpoints.

### Preview
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/190dee7c-9bed-48ac-8318-a4e0b095cbe4)

**Comment by yurixander** [comment]
Not as relevant, closing for now.
