### ISSUE TITLE
[CHECKLIST] 🚀 Pre-launch QA audit

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2111]
### Checklist
- [x] https://github.com/webb-tools/webb-dapp/issues/2112
- [x] #2149
- [x] #2146
- [x] https://github.com/webb-tools/webb-dapp/issues/2113
- [x] https://github.com/webb-tools/webb-dapp/issues/2114
- [x] https://github.com/webb-tools/webb-dapp/issues/2115
- [x] #2123
- [x] #2124
- [x] #2125
- [x] #2126
- [x] #2144
- [x] #2127
- [x] https://github.com/webb-tools/webb-dapp/issues/2105
- [x] https://github.com/webb-tools/webb-dapp/issues/2096
- [x] https://github.com/webb-tools/webb-dapp/issues/2110
- [x] #2140
- [x] #2143 
- [x] #2103
- [x] #2148
- [x] #2153 
- [x] #2170 
- [x] #2174 
- [x] #2180 
- [x] #2182 
- [x] #2183
- [x] #2156 
- [x] #2167 
- [x] https://github.com/webb-tools/webb-dapp/issues/2155
- [x] #2200

**Comment by drewstone** [comment]
CC @devpavan04 @vutuanlinh2k2 @AtelyPham I added some new items to the board here. They are high priority!
