### ISSUE TITLE
[TASK] Update validator profile card w/ actual data

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2136]
### Tasks
- [ ] Remove dummy data
- [ ] Pass values as props (nominations, commission, etc.)
- [ ] Add socials properly if identity exists
- [ ] Hide components where no data exists (or not ready yet).

**Comment by vutuanlinh2k2** [comment]
Additional things I will do in this task:
- Update Validator table so that users can navigate to the validator's account page on block explorer
- Handling loading state for this component
