### ISSUE TITLE
[CHECKLIST] Fixed Substrate Anchor integration into the dApp

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#224]
# check list

- [x] #301
- [x] <del> #313 </del>.
- [ ] Integrations
    - [x] #318 
    - [x] #314 
    - [x] #315
    - [x] #321
    - [x] #310  
    - [ ] Update the UI to fit subsrate
    	- [x] Perfrom deposit & withdraw.
    	- [ ] Chain switching if the chain from note isn't the same as active chain
