### ISSUE TITLE
[CHECKLIST] 🔧 Post-launch audit

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2251]
Bug fixes, and improvements needed to get the app in a 'stable' state such that we are adding new features instead of fixing existing functionality.

### Checklist
- [x] #2152
- [x] #2179
- [x] #2186
- [ ] https://github.com/webb-tools/webb-dapp/issues/2250
- [x] https://github.com/webb-tools/webb-dapp/issues/2249
- [x] https://github.com/webb-tools/webb-dapp/issues/2248
- [x] https://github.com/webb-tools/webb-dapp/issues/2247
- [x] https://github.com/webb-tools/webb-dapp/issues/2246
- [x] https://github.com/webb-tools/webb-dapp/issues/2245
- [x] https://github.com/webb-tools/webb-dapp/issues/2244
- [x] https://github.com/webb-tools/webb-dapp/issues/2215
- [x] https://github.com/webb-tools/webb-dapp/issues/2252
- [ ] https://github.com/webb-tools/webb-dapp/issues/1339
- [x] #2253
- [x] https://github.com/webb-tools/webb-dapp/issues/2172
- [x] https://github.com/webb-tools/webb-dapp/issues/2164
- [x] https://github.com/webb-tools/webb-dapp/issues/2268
- [x] https://github.com/webb-tools/webb-dapp/issues/2267
