### ISSUE TITLE
[TASK] Migrate Applications and Libraries to ESM Format

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2312]
We need to migrate all apps and libs to the ESM format as most libraries, including wagmi, now only support ESM.

Continuing to use the CommonJS (CJS) format prevents us from upgrading dependencies to newer versions, which may include bug fixes, new features, and other improvements.

While it is possible to use CJS libraries in ESM modules, ESM libraries cannot be imported into CJS modules. Therefore, upgrading is necessary to use ESM-only libraries.

### Task

- [x] Upgrade all @nx/* packages to version 19 (latest version as of now).
- [x] Migrate all libraries to the ESM format.
- [x] Migrate all applications to the ESM format.
- [x] Upgrade all dependencies to latest versions.

### Resources

- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- https://nx.dev/features/automate-updating-dependencies
