### ISSUE TITLE
[CHECKLIST] Asset Delegation / Restaking UI

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2318]
# Overview
On Tangle, the asset delegation / restaking UI is the main place users will restake tokens by delegating them to operators. The main purpose of this UI is to delegate non-native assets such as `tgDOT` and other assets from other ecosystems (ETH, DOT, ETH L2s) into Tangle's restaking system.

## Delegation UI
- [x] Designs: https://github.com/webb-tools/webb-experiences/issues/268
- [x] https://github.com/webb-tools/webb-dapp/issues/2367
- [x] #2404
- [x] https://github.com/webb-tools/webb-dapp/issues/2418
- [x] #2407
- [x] https://github.com/webb-tools/webb-dapp/issues/2470
- [x] #2408
- [x] #2409

### Reference 
https://github.com/webb-tools/tangle/issues/650

**Comment by monaiuu** [comment]
For reference, here is the Restaking usage guide draft:
https://www.notion.so/webbtools/Restaking-Usage-Guide-e1da8a0ecb3f4320bb941f9ef7bf05c1?pvs=4
