### ISSUE TITLE
[TASK] Add A Method to Fetch Asset Prices for TVL Calculations.

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This task relates to the restaking feature, but the price API can also be utilized for other features that require asset pricing. 

Our system supports multiple assets, necessitating a method to fetch their prices for a unified value, such as in USD.

### Describe the solution you'd like

Use one of the APIs from https://github.com/CoinQuanta/awesome-crypto-api to fetch the asset price.

### Describe alternatives you've considered

Nope

## Tasks

- [x] Implement a method to fetch asset prices for one or multiple assets simultaneously.

### Restake Overview

- [x] Calculate the total restaking value in USD.
- [x] Calculate the self-restaking value in USD.
- [x] Calculate the TVL in USD for each vault on the restake vaults tab.
- [x] Calculate the TVL in USD for each asset in a vault on the restake vaults tab.
- [x] Calculate the operator's concentration based on the values of restaked assets on the operators tab.
- [x] Calculate the TVL in USD for each operator on the operators tab.
- [x] Calculate the TVL of each asset restaked into an operator on the operators tab.
