### ISSUE TITLE
[CHECKLIST] Tangle Cloud Console [V1]

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2546]
## Checklist
General
- [ ] [TASK] Set Up New URL and DNS for Tangle Cloud Console
- [ ] [SPEC] Evaluate User Onboarding Flow Options
- [ ] [TASK] RBAC for Features Access 
- [ ] [TASK] Blueprint Categories Creation / Filter
- [ ] [TASK] Cloud Console Views without Sign-In

Operator
- [ ] [TASK] Create Blueprint Marketplace Display for Operators
- [ ] [TASK] Enable Operators to Select and Register Blueprints
- [ ] [TASK] Operator Pricing Configuration Setup
- [ ] [TASK] Blueprint Registration Custom Configuration
- [ ] [TASK] Display Registered Blueprint(s)
- [ ] [TASK] Display Running Blueprint Instances
- [ ] [TASK] Display Pending Blueprint Instances and Management

Instance Deployer
- [ ] [TASK] Create Blueprint Marketplace Display for Deployers
- [ ] [TASK] Blueprint Instance Deployment Selection 
- [ ] [TASK] Instance Parameters Inputs 
- [ ] [TASK] Instance Deployment Operators Display/Selection
- [ ] [TASK] Instance Deployment Assets Display/Selection
- [ ] [TASK] View and Manage Running Instances
- [ ] [TASK] View and Manage Pending Instances

-----

To dos (designs pending):
Operators
- [ ] [TASK] Blueprint Unregistration Flow
- [ ] [TASK] Performance Metrics Tracking
- [ ] [TASK] Blueprints Payouts

Customers
- [ ] [TASK] Running Instance TTL Extension
- [ ] [TASK] Running Instance Termination
- [ ] [TASK] Running Instance Operators Management
- [ ] [TASK] Running Instance Operators Performance Tracking
- [ ] [TASk] Customers Billing Features

Blueprint Developers (considerations)
- [ ] [FEAT] Enable Updating Blueprint metadata / configurations
- [ ] [FEAT] Viewing / Managing Distribution Rewards to Operators
- [ ] [FEAT] Blueprint Version Controlling
- [ ] [FEAT] No-Code Blueprint Deployment Flow (?)

**Comment by drewstone** [comment]
@monaiuu some items here say pending designs are they implemented or can you describe which existing designs can be used to model these new components?

**Comment by drewstone** [comment]
Most important things the cloud does firstly
- **List the blueprints**
- **Registering for blueprints/joining the operator set**
- **Requesting a service**
- **Approve and reject requests**
- List the running instances
- Control over instances

**Comment by yuri-xyz** [comment]
Note on #2555 & #2982: It seems that I am unable to test these flows due to `Token.FundsUnavailable` error when accepting/rejecting requests. I believe this was something that the node team was working on fixing? @danielbui12 

I can see the pending instances though.
