### ISSUE TITLE
[CHECKLIST] Mobile-Specific UI Updates

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb-dapp#305]
### UI Components

- [x] Sticky footer for wallet selection for mobile
- [ ] Accommodate tabular components with horizontal and vertical scrolling on small screens
- [ ] Update wallet selection to only show WalletConnect for mobile
- [x] Hamburger menu in NavBar
