### ISSUE TITLE
[TASK] Governance Page

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb-dapp#308]
# Overview
The goal of this checklist is to outline the definition of done for implementing the updated Governance designs.

### General UI Components
- [ ] Implement Governance tab in the sidebar

### Application State
- [ ] Implement a Proposal class
- [ ] Implement useDKG hook for queries to the DKG.
- [ ] Implement routing for detailed proposal view: '/substrate/:proposal_id'

### Proposal Overview Card
- [ ] Implement All | Active tab  
- [ ] Implement list view of proposals with the following data
          - Proposers address (e.g. By 0x...)
          - Title of proposal 
          - Proposal status (e.g. Active, Executed, Defeated)
          - Elapsed time to vote (e.g. Voting ends 1hr) 

### Detailed Proposal View 
- [ ]  On-click takes the user to detailed proposal view
- [ ] Implement back button to return the user to main proposal view
- [ ] Detailed proposal header should contain the following data
          - Proposers address (e.g. By 0x...)
          - Title of proposal 
          - Proposal status (e.g. Active)
          - Elapsed time to vote (e.g. Voting ends 1hr) 
- [ ] Implement Vote Casting section for **Active** proposals 
- [ ] User may select Yes || No and submit their vote via 'Vote' button
- [ ] Implement **Description** section outlining the Proposal explanation
- [ ] Implement a table listing all participating addresses, and their vote  

### Proposal Finality View
- [ ] Implement a detailed view of the vote result on proposals that have been **Executed**
- [ ] Implement back button to return the user to main proposal view
- [ ] Detailed proposal header should contain the following data
          - Proposers address (e.g. By 0x...)
          - Title of proposal 
          - Proposal status (Executed)
          - Time voting period ended (e.g. Ended Mar 3) 
- [ ] Implement Vote Results section showing a horizontal bar graph of the Yes and No votes 
- [ ] Implement **Description** section outlining the Proposal explanation
- [ ] Implement a table listing all participating addresses, and their vote  

## Relevant Links
- You can view the current spec for the governance page [here](https://www.notion.so/hicommonwealth/e6012ca196ad4c8cbd125667b4ff2ed1?v=9e8cd3feda0b4ec394827ffafe193491).
