### ISSUE TITLE
[CHECKLIST] Update Note with new ChainID type

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#322]
# Overview 

Update note to include new ChainID type, and integrate into dAPP 

- [x] https://github.com/webb-tools/webb.js/issues/134
- [x] https://github.com/webb-tools/webb.js/issues/167
- [ ] https://github.com/webb-tools/webb.js/issues/123

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/webb-tools/webb.js/issues/123
