### ISSUE TITLE
[CHECKLIST] Collection of BUGS that require investigation, refactoring and fixes

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#323]
# Overview 

This checklist serves as tracker for current, and future dApp bugs, refactoring, maintenances and chores that require investigation and fixes. 

## Tasks

- [x] https://github.com/webb-tools/webb-dapp/issues/276
- [x] https://github.com/webb-tools/webb.js/issues/165
- [x] https://github.com/webb-tools/webb-dapp/issues/251
- [x] https://github.com/webb-tools/webb-dapp/issues/237
- [x] https://github.com/webb-tools/webb-dapp/issues/241
- [x] https://github.com/webb-tools/webb-dapp/issues/242
- [ ] https://github.com/webb-tools/webb-dapp/issues/243
- [x] https://github.com/webb-tools/webb.js/issues/145
- [ ] https://github.com/webb-tools/webb-dapp/issues/291
- [ ] https://github.com/webb-tools/webb-dapp/issues/239
- [ ] https://github.com/webb-tools/webb-dapp/issues/245
