### ISSUE TITLE
[CHECKLIST] Finalize Mixer requirements

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#364]
# Overview

The goal of this checklist is to outline the remaining requirements for finalizing the mixer grant.

## Documentation

- [x] Ensure proper license(s) are in place for [relayer](https://github.com/webb-tools/relayer/blob/main/LICENSE), [webb-dapp](https://github.com/webb-tools/webb-dapp/blob/master/LICENSE), [webb.js](https://github.com/webb-tools/webb.js/blob/master/LICENSE)
- [x] Add inline and external documentation for each associated repo [relayer](https://github.com/webb-tools/relayer/main), [webb-dapp](https://github.com/webb-tools/webb-dapp), [webb.js](https://github.com/webb-tools/webb.js/master)
- [x] Add instructions and description to [package](https://github.com/webb-tools/webb.js/tree/master/packages/wasm-utils)
- [x] Add usage examples to webb.js
- [x] Provide instruction on how to test UI Support: Multi-Asset support

## Relevant Issues / PRs
- [x] https://github.com/webb-tools/webb.js/pull/181
- [x] https://github.com/webb-tools/webb-dapp/pull/369
- [x] https://github.com/webb-tools/relayer/issues/107
- [x] https://github.com/webb-tools/webb-dapp/issues/345
- [x] https://github.com/webb-tools/webb.js/pull/197
- [x] https://github.com/webb-tools/webb.js/pull/200
- [x] https://github.com/webb-tools/webb.js/issues/202
- [x] https://github.com/webb-tools/webb-dapp/issues/382

The main deliverable is to demonstrate a working example of the mixer through the DApp interface, include well documented instructions on the steps to replicate success.

**Comment by dutterbutter** [comment]
For context: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Webb-Mixer-Extended_2_alxs.md

**Comment by dutterbutter** [comment]
@nepoche @AhmedKorim @drewstone @dutterbutter 

Below I have outlined a checklist that should ensure we have met the grant requirements, and improves the documentation / usage of each component.  

## Checklist for grant completion 

- [ ] E2E demonstration of mixer with thorough guideline for others to follow

### Relayer
- [ ] Check and ensure proper license(s) is in place for [relayer](https://github.com/webb-tools/relayer)
- [ ] Relayer README updated with adequate instruction
- [ ] Adequate inline/implementation documentation  
- [ ] Adequate external documentation  
- [ ] Updated preset configurations for easy startup - mixer

### Webb Dapp
- [ ] Check and ensure proper license is in place for [webb-dapp](https://github.com/webb-tools/webb-dapp)
- [ ] Webb-dapp README updated with adequate instruction
- [ ] Adequate inline/implementation documentation  
- [ ] Adequate external documentation
- [ ] Updated to support node v16

### Webb.js
- [ ] Check and ensure proper license(s) are in place for [webb.js](https://github.com/webb-tools/webb.js)
- [ ] Webb.js README updated with adequate instruction
- [ ] Adequate inline/implementation documentation  
- [ ] Adequate external documentation
- [ ] wasm-bindings is documented, includes a readme with instruction and runs correctly 
- [ ] UI Support: Multi-Asset support
- [ ] Updated to support node v16
- [ ] @webb-tools/types disclosure and credit for copied code
- [ ] Detailed API usage examples with documentation
