### ISSUE TITLE
[CHECKLIST] Design spec differentials 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#366]
# Overview 

The purpose of this checklist is to track the differences between the current implementation and design specifications. 

- [ ] Sidebar parent item is not highlighted / Slider indicator is not present.
- [ ] Line in mixer group select to connect options does not exist.
- [ ] Tornado deposit field does not have a 'chain' section.
- [ ] Checkboxes aren't properly styled for light theme.
- [ ] Align the close button in the wallet selection
- [ ] Fancy Circles in wallet design
- [ ] Ellipsed addresses are done at the end rather than the middle

**Generic site-wide component sizing:**

- [ ] Component sizes in the design are absolute - the dapp uses flex.
- [ ] Breakpoints for 'desktop' -> 'mobile' layout probably need to change with respect to the appbar and child components.
- [ ] The 'Content' section of each page (deposit/withdraw component) should be enlarged on desktop / responsive sizing
