### ISSUE TITLE
[CHECKLIST] UI design updates and improvements

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#374]
# Overview

The purpose of this checklist is to track UI specific enhancements, specifically for alignment, sizing/spacing, and asset related tasks. 

### Alignment 
- [ ] Line up header with logo 
 
### Sizing/Spacing 
- [ ] Consistent text sizing and font 
- [ ] Responsively enlarge main container on larger screens 
- [ ] Increase space of header from vertical/side nav
- [ ] Increase space between chain selection on smaller screens 
- [ ] Increase spacing between IP address and sidebar items 
- [x] https://github.com/webb-tools/webb-dapp/issues/367

### Assets 
- [ ] Make use of Ethereum logo for testnets 
- [ ] Update Wrapped Webb token logo
- [ ] Make SVG for social links visible on iPhone 
- [ ] Add dropdown arrow on wallet-chain selection
