### ISSUE TITLE
[TASK] VAnchor utxo and note management 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#379]
# Overview

Currently, the user is expected to copy, download, and manage deposit notes by themselves. To improve the user experience, we should manage notes and implement safeguards for the user in the dApp.

Safeguards to implement for the user:
- Managing the 'NotesKey' which is a randomly-generated keypair used for creating notes and used for generating proofs that a user is eligible to spend a note, if they possess the private key of the keypair used for generation.

UX Improvements to implement for the user:
- Store output notes as encrypted before performing any actions on-chain, in case the user loses their copy.
- Remove automatic download of the note.
- Remove the need for a user to copy/paste notes to withdraw.

#### Storage
- Note storage should be indexed upon the public key of the note account.
- Stored notes should be encrypted with the note account public key before storing.
- The Stored notes will be decrypted on NoteManager initialization(?)

![NoteManagerInitialization](https://user-images.githubusercontent.com/16654909/182947298-60e12af9-2334-4539-8df1-dc52b8037e9e.png)

#### UI
- Users will require a UI which displays notes, note balances, login / logout functionality of a NoteAccount.
- Current withdraw page infers the desired token from the first pasted note.  If notes are automatically managed for the user, there needs to be some input for the user to select the desired token to withdraw. 

<img width="927" alt="NoteManagerNotesSelection" src="https://user-images.githubusercontent.com/16654909/182947822-664eaa88-c75a-410a-9676-63aba8eb5e37.png">

#### Page Interactions

- Before transactions are submitted on-chain, store notes in localStorage (prevent user catastrophic errors).

<img width="999" alt="NoteManagerDepositApiInteractions" src="https://user-images.githubusercontent.com/16654909/182952012-adabcd22-87dc-40dd-9c7a-8e039b40bb89.png">

<img width="767" alt="NoteManagerWithdrawApiInteractions" src="https://user-images.githubusercontent.com/16654909/182952589-35193509-29f6-4ebd-a1a4-3c918ea12d97.png">

### Tasks

- [ ] Create a `NoteAccount` component, which functions similarly to the wallet component, to be interacted with in the AppBar.
- [ ] Encrypt any DepositNotes / ChangeNotes with the logged-in `NoteAccount` before storing in localStorage.
- [ ] User should be able to supply a `NoteAccountString` (private key in keypair) to login to `NoteAccount`.

**Comment by dutterbutter** [comment]
@nepoche please add any relevant context to this issue or remove outdated points.

**Comment by dutterbutter** [comment]
Closed in #494
