### ISSUE TITLE
[SPEC] Crowdloan integration into dApp

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#420]
## Overview

This issue outlines a potential approach to integrate the crowdloan into the dApp, and follow issue #419. 

## Tasks

- [ ] Create `Crowdloan<T>` interface in `react-environment/src/webb-context/` and add to `WebbMethods<T>`
- [ ] Add `PolkadotCrowdloan` to the `webb-polkadot-provider` , empty and disabled for `webb-web3-provider`

```
export abstract class Crowdloan<T> extends EventBus<CrowdloanEvents> {

	constructor(protected inner: T) {}

	async getBalance(){}

	async getContributions() {}

	async contribute(amount: number) {}
}
```

```
export class PolkadotCrowdloan implements CrowdLoan<WebbPolkadot> {

	const PARA_ID = XXX;

	async getBalance() {
		this.inner.api.query.crowdloan.funds(PARA_ID)
		// then parse for total balance
	}

	async getContributions() {
		this.inner.api.derive.crowdloan.contributions()
	}

	async contribute(amount: number) {
		this.inner.txBuilder.build(
			{
				section: 'crowdloan',
				method: 'contribute',
			}
			{
				PARA_ID,
				amount,
			}
		);
	}
}
 ```
 
 #### Missing inputs

- We currently do not have a secured long term parachain id (`PARA_ID`)

### Testing

- [ ] Test crowdloan using Rococo / Westend
