### ISSUE TITLE
[TASK] Update chain names and chain button size in header

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#429]
## Overview 

The chain button in the header is currently dynamic in size relative to the chain name. We should make this a fixed size for consistent viewing. We will also need to update the following chain names:

| Current chain name | Expected chain name |
|---|---|
| Hermes localnet | Hermes |
| Athena localnet | Athena |
| Demeter localnet | Demeter  |
| Protocol Substrate Development | Substrate |
| Webb Eggnet | Eggnet |
| Polygon Testnet | Mumbai |
| Arbitrum Testnet | Arbitrum |
| Optimism Testnet | Optimism |
| Kusama Relay Chain | Kusama |
| Polkadot Relay Chain | Polkadot |

**Note:** Given the network manager is divided between 'Live', 'Test', and 'Dev'. I think it is reasonable to drop the "Testnet" portion of Arbitrum and Optimism. 

### Tasks

- [ ] Update chain names 
- [ ] Have the chain button in the header be consistent in size for all supported chains
- [ ] Ensure logos for each chain are the same size 
- [ ] Update logos for [Kusama](https://github.com/paritytech/polkadot-staking-dashboard/blob/master/src/img/kusama_icon.svg) and [Polkadot](https://github.com/paritytech/polkadot-staking-dashboard/blob/master/src/img/polkadot_icon.svg) chains with their respected logos
- [ ] Ensure the chain button is the same size as the wallet manager button

### Current Behaviour 

The below screenshots displays the chain button for two different chains. The size differences are noticeable. Let's try to be consistent. 

<img width="172" alt="Screen Shot 2022-06-15 at 2 42 02 PM" src="https://user-images.githubusercontent.com/29983536/173911707-ebb17ffe-5df7-4a1d-9a58-3046b66bd32e.png">
<img width="289" alt="Screen Shot 2022-06-15 at 2 41 47 PM" src="https://user-images.githubusercontent.com/29983536/173911763-fb46a264-a4f5-4acb-a4e6-96c878632600.png">
