### ISSUE TITLE
[TASK] Update font sizes for added consistency to UI

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#430]
## Overview 

The current dApp has some font inconsistencies that should be remedied. 

### Tasks

- [ ] Update font size between 'Token' and 'Wrap Assets' to be the same
- [ ] Update font size for 'Your Balance' to be consistent with 'Amount', and remove the 'Your' it should just read 'Balance'
- [ ] Go through each page (e.g. Mixer, Bridge etc) and ensure consistent font sizing

### Current Behaviour 
Different font sizes (Token and Wrap Assets):
<img width="400" alt="bridge-page" src="https://user-images.githubusercontent.com/29983536/173914297-cd4c956e-cda9-45da-8351-d6d90c6f008f.png">

Different font sizes (Your Balance):
<img width="412" alt="Screen Shot 2022-06-15 at 2 52 30 PM" src="https://user-images.githubusercontent.com/29983536/173915100-9c367104-7cd0-4c63-8aa7-c6e94bab0fce.png">

### Expected Behaviour 

**Typography Requirements**
font-family: [Work Sans](https://fonts.google.com/specimen/Work+Sans);
font-size: 16px;
line-height: 20px;
letter-spacing: 0.02em;
