### ISSUE TITLE
[TASK] Update wallet button in header 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#431]
## Overview

Our current wallet button in the header has inconsistent sizing, and displays unneeded information to the user. 

## Tasks

- [ ] Remove balances from wallet button in header
- [ ] Update format for MetaMask accounts to be displayed as `MetaMask logo - Account - First 4 digits of address (removing 0x)` (see Expected Behaviour - MetaMask below)
- [ ] Update format for Polkadot.js accounts to be displayed as `Polkadot logo - Account Name` (up to 12 characters)
- [ ] Ensure Logo sizes are consistent between Polkadot.js and MetaMask
- [ ] Ensure Logo sizes are consistent between chain logos and wallet logos

### Current Behaviour - MetaMask

The image below shows the users full balance to the decimal and good portion of the full address. Depending on the users balance the button changes size accordingly. 

<img width="257" alt="Screen Shot 2022-06-15 at 3 00 54 PM" src="https://user-images.githubusercontent.com/29983536/173916559-ace60807-151a-495f-93e3-bd15740efc0c.png">

### Expected Behaviour - MetaMask

Instead the button should simply display the MetaMask logo - Account - First 4 digits of address (removing 0x). See the below image for an example. The user's balance will be displayed in each of the pages (e.g. Mixer, Bridge), and the user can simply click the button to view the account balance, so I do not think it's required to display again in the header. 

<img width="213" alt="Screen Shot 2022-06-15 at 3 03 03 PM" src="https://user-images.githubusercontent.com/29983536/173916857-77b6faf7-07b8-4396-aeeb-ead64e454aa5.png">

### Current Behaviour - Polkadot.js

The image below shows the users full balance to the decimal and the account name. Depending on the users balance and name the button changes size accordingly. 

<img width="231" alt="Screen Shot 2022-06-15 at 3 11 43 PM" src="https://user-images.githubusercontent.com/29983536/173918256-c2127375-bf7b-4187-8ff3-dd707a356dda.png">

### Expected Behaviour - Polkadot.js

Instead the button should display the Polkadot logo - Account Name. The account name can be truncated to the same amount of characters as the MetaMask total - 12 characters. For most account names that should suffice and will keep the button looking consistent between MetaMask accounts and Polkadot accounts.
