### ISSUE TITLE
[TASK] Move theme button to header and fix social spacing/sizing

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#432]
## Overview

The current placement of the theme button seems out of place as it sits separately on its own plain. We should move the theme button to the header. 

## Tasks

- [ ] Move theme button to header
- [ ] Ensure sizing is consistent in height as wallet and chain buttons
- [ ] Fix spacing between social icons to be consistent 
- [ ] Ensure icons are relatively same size for consistent view

### Current Behaviour 
**Note:** Theme buttons appears out of place where it currently is and there are some spacing/sizing issues between the social icons that can be fixed.

<img width="190" alt="Screen Shot 2022-06-15 at 3 21 35 PM" src="https://user-images.githubusercontent.com/29983536/173921313-bdea4df5-75dd-41df-abb9-70e0e59b480a.png">

### Expected Behaviour 
An example of theme button placement in header:
<img width="466" alt="Screen Shot 2022-06-15 at 3 26 38 PM" src="https://user-images.githubusercontent.com/29983536/173920792-8c62f12e-8bcf-46c6-84e6-7ff93b7a9e4f.png">
