### ISSUE TITLE
[TASK] Create a mockup for DKG / Eggnet Statistics Page 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#434]
## Overview

Prior to launch it would great if we can create a page that displays key statistics regarding the dkg protocol and chain data from eggnet. This task will be related to #306 and there are currently some form of mockup / examples to get started with which can viewed [here](https://www.notion.so/hicommonwealth/DKG-Egg-net-UI-93a01eb86b584c2e84deb8a1d7f57def).

This task will likely be completed in phases, starting with using dummy data to setup the UI correctly and organize the data as we see fit. Then, move to how we want to fetch, and manage real data for the statistics page. 

### Tasks - Phase 1

- [x] Create a statistics page directory 
- [x] Create dummy placeholder data that is similar to what data should be expected, see [here](https://www.notion.so/hicommonwealth/DKG-Egg-net-Implementation-f92bdb8598444c18a1dee03dcb304bf2) for additional details.
- [x] Layout the data and create UI elements / components as depicted [here](https://www.notion.so/hicommonwealth/DKG-Egg-net-UI-93a01eb86b584c2e84deb8a1d7f57def)
