### ISSUE TITLE
[TASK] Inconsistent paddings and tabs style

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#436]
## Overview

**On the small screen**, paddings of tabs and content are inconsistent between pages and tabs. The `border-radius` and tabs style is inconsistent between pages too (see the screenshots below). We should update all pages and tabs to match the style of the `Bridge` page.

## Tasks

- [ ] Update `Mixers` padding on small screen (both `Withdraw` and `Deposit` tabs) and the `border-radius` on `Withdraw` tab.
- [ ] Update `VBridge` padding on small screen and  the `border-radius` (both `Withdraw` and `Deposit` tabs).
- [ ] Update `Wrap/Unwrap` tab style and the padding on small screen.
- [ ] Update `Crowdloan` `border-radius`.

#### Mixer Page

| Deposit | Withdraw |
| :------: | :-------: |
| <img width="320" alt="CleanShot 2022-06-18 at 18 54 05@2x" src="https://user-images.githubusercontent.com/60747384/174436327-ed2d1bb9-7a73-4b0d-bb30-11e6a28890d8.png" /> | <img width="384" alt="CleanShot 2022-06-18 at 18 56 07@2x" src="https://user-images.githubusercontent.com/60747384/174436416-867a0365-1bd6-4a5e-af75-d9376bcda1b9.png" /> |

#### VBridge Page

<img width="384" alt="CleanShot 2022-06-18 at 18 58 42@2x" src="https://user-images.githubusercontent.com/60747384/174436530-e8375ec6-880e-4170-b2a6-81d5e2ced0b8.png" />

#### Wrap/Unwrap Page

<img width="532" alt="CleanShot 2022-06-18 at 19 00 21@2x" src="https://user-images.githubusercontent.com/60747384/174436550-de5c87c0-6790-4955-b248-6f75e8c35982.png">

### Expected Behaviour

All page styles should match the `Bridge` Page style.

https://user-images.githubusercontent.com/60747384/174436919-e84645f5-6f75-4747-b692-9a91f98fc707.mp4
