### ISSUE TITLE
[TASK] Wearetalisman, Subwallet wallet integration & documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#479]
## Overview

There are cool Polkadot wallets on the block: [Wearetalisman](https://talisman.xyz/) and [Subwallet](https://subwallet.app/). We want to integrate these wallets for Polkadot / Substrate networks as well as document the process for integrating new wallets (for when we get to Cosmos wallet solutions and more).

## Task Checklist

- [x]  Integrate both wallets as an option besides PolkadotJS Extension
- [x]  Testing bridge flows with it to ensure the txes work (provide videos)
- [x]  Switching between wallets works (provide videos)
- [ ]  Demo at engineering meeting
- [x]  Document wallet integration steps
