### ISSUE TITLE
[TASK] ECDSA Claims Interface

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#480]
## Overview

We have integrated a `Claims` pallet that allows us to set up a genesis distribution for Ethereum address holders. The basic mechanism is that a valid Ethereum address would generate a signature of their Substrate address to receive the distribution. We run the following check on-chain:

1. Is the Ethereum address in the set of recipients
2. Is the signature valid for that address
3. If so, send vested/unvested tokens to the target Substrate address

## Task Checklist

- [x]  Create a UI that takes as input a Substrate address raw 32-bytes public key (to be checked against the pallet)
- [x]  The first step in the process should be to sign the Substrate address through MetaMask with your valid Ethereum key
- [x]  The second step should be to submit this signature and tx to the Substrate network claims pallet.
- [ ]  The third step should be to show confirmation and a tx hash.
