### ISSUE TITLE
[TASK] Implement Substrate wrap/unwrap flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#481]
## Overview

We don’t have a tested wrap/unwrap flow for tokens on the dApp. We haven’t tested this thoroughly either. We need to investigate and implement this as far as we can and work on speccing and collaborating with runtime developers like Stanly to identify missing functionality for a successful demo of this.

## Task Checklist

- [ ]  Ensure tokens appear for Substrate networks
- [ ]  Ensure wrappable tokens are dynamically pulled from the runtime
- [ ]  Add wrap/unwrap flows for our Substrate networks
- [ ]  Demo on Wednesday eng. session

## Relevant Links

- [https://github.com/webb-tools/protocol-substrate/blob/a8ef0d0fcbf060fd62ab4ad683cb7c810885a3ea/pallets/asset-registry/src/lib.rs#L494](https://github.com/webb-tools/protocol-substrate/blob/a8ef0d0fcbf060fd62ab4ad683cb7c810885a3ea/pallets/asset-registry/src/lib.rs#L494)
- [https://github.com/webb-tools/protocol-substrate/blob/a8ef0d0fcbf060fd62ab4ad683cb7c810885a3ea/pallets/token-wrapper/src/lib.rs#L175](https://github.com/webb-tools/protocol-substrate/blob/a8ef0d0fcbf060fd62ab4ad683cb7c810885a3ea/pallets/token-wrapper/src/lib.rs#L175)
