### ISSUE TITLE
[CHECKLIST] Establish and implement Webb UI kit 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#502]
## Overview 

The goal of this checklist is to create a comprehensive list of UI components to be implemented that collectively make up the Webb UI Kit. The Webb UI kit will be used throughout the product and will exist as a sub package in the current webb-dapp repo. 

The below divides up the design system into various component types that will be translated into generalized reusable components to be used within Webb applications. The advantages of creating a Webb UI kit include:

- Ship faster
- Beautiful by default
- Developer engagement
- Improved component reusability and code deduplication 

It should be as easy as:

```
import * as React from 'react';
import Button from '@webb/Button';

function App() {
  return <Button type="primary">Hello World</Button>;
}
```

## Suggestions 

@nepoche @AhmedKorim @AtelyPham please come to an agreement on how the following items should be handled. 

- Use [Radix-UI](https://www.radix-ui.com/) for component library instead of MaterialUI 
     - It should enable the same speed of dev as MUI without the lock-in of how MUI styles its components and the theme.
- Use tailwind as a styling library instead of styled-components.

### Open Questions

- How should we handle the theming (dark mode) if not using MUI theming? It likely should not be a prop passed to each component listed below.
- Do we need to spec for Theme/UI provider?
    - Pass global values to components
    - Update/Switch the theme.

## Tasks Checklist

**NOTE:** These components should be implemented incrementally and PR'd / merged accordingly. We should be implementing, opening PR, reviewing, and merging the below listed components frequently and never contain too much code. 

- [x] Create `webb-ui-components` directory; this will contain all the exportable components
- [x] Include readme that outlines how to make use of the component library
- [x] Ensure each component is well documented

### Atoms

- [x] #503 
- [x] #504 
- [x] #505 
- [x] #506 

### Molecules 

- [x] #507 
- [x] #508 
- [x] #509 
- [x] #510 
- [x] #511 
- [x] #512 
- [x] #513 
- [x] #514 
- [x] #515 

### Organisms 

- [x] #519 
- [x] #531 
- [x] #516 
- [x] #517 
- [x] #518 

### Relevant Links

- [Figma guide for developers](https://www.notion.so/hicommonwealth/Figma-Guide-for-Developers-21744fc512ba4d51aefe91d00985026d)

**Comment by dutterbutter** [comment]
Github seemed to glitch for me and did not link all the issues in the checklist 🤔

**Comment by AtelyPham** [comment]
Did you use this button?

<img width="903" alt="CleanShot 2022-08-20 at 02 57 24@2x" src="https://user-images.githubusercontent.com/60747384/185697626-8e2cf5ba-d6f8-496a-9ee7-31a581824660.png">

**Comment by dutterbutter** [comment]
Yes @AtelyPham

**Comment by AtelyPham** [comment]
The checklist is done ✅ 🔥

**Comment by dutterbutter** [comment]
Closed in #563
