### ISSUE TITLE
[TASK] Add relevant icons to UI kit

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#504]
## Task Description

The purpose of this task is to add relevant icons into the webb UI kit for easy and quick use. 

## Task Deliverable

- [ ]  Create a folder `webb-icons`
- [ ]  Add all relevant icons from design system [here](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=163%3A3996)
- [ ]  Icons added should each follow a strict naming convention (e.g. `name-size`)
- [ ]  Ensure the icons reflects the intended design
- [ ]  Ensure icons are exportable

**Component properties:**

- type="btc";
- size="large";
- darkmode=false;

**Example usage:**

```bash
import { BTCTokenIcon } from '@webb/icons';

<BTCTokenIcon type="btc" size="large" dark-mode="off" />
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=163%3A3996)

**Comment by dutterbutter** [comment]
Closed in #536
