### ISSUE TITLE
[TASK] Implement reusable Typography component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#505]
## Task Description

The purpose of this task is to implement a reusable Typography component that can be exported for external use. The Typography component makes it easy to apply a default set of font weights and sizes in your application.

## Task Deliverable

- [x]  Create a folder `Typography`
- [x]  Implement a `Typography` component with the below mentioned props
- [x]  Upload relevant font files
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example

**Component properties:**

- variant="h1 | h2 | h3 | h4  | h5 | body";
- size="large | medium | small";
- align = “center | inherit | justify | left | right”
- dark-mode= on|off;

**Example usage:**

```bash
import { Typography } from '@webb/typography';

<Typography variant="h1" size="medium" align="left" darkmode="off">
 Hello 
</Typography>;
```

**Typography snippet:**

```bash
/* Font Family Breeze Sans */

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans.eot'), url('fonts/BreezeSans.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans-Medium.eot'), url('fonts/BreezeSans-Medium.ttf') format('truetype');
    font-weight: 600;
    font-style: normal;
}

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans-Bold.eot'), url('fonts/BreezeSans-Bold.ttf') format('truetype');
    font-weight: 800;
    font-style: normal;
}

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans-Italic.eot'), url('fonts/BreezeSans-Italic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans-Medium-Italic.eot'), url('fonts/BreezeSans-Medium-Italic.ttf') format('truetype');
    font-weight: 600;
    font-style: italic;
}

@font-face {
    font-family: 'BreezeSans';
    src: url('fonts/BreezeSans-Bold-Italic.eot'), url('fonts/BreezeSans-Bold-Italic.ttf') format('truetype');
    font-weight: 800;
    font-style: italic;
}

html, body, h1, h2, h3, h4, h5, p, table, ol, ul, li {
    font-family: 'BreezeSans', Arial, sans-serif;
}

h1 {
    font-size: 64px;
}

h2 {
    font-size: 48px;
}

h3 {
    font-size: 36px;
}

h4 {
    font-size: 24px;
}

h5 {
    font-size: 18px;
}

p {
    font-size: 16px;
}

p.small {
    font-size: 14px;
}

p.x-small {
    font-size: 10px;
    text-transform: uppercase;
}

@media screen and (max-width: 800px) {
    h1 {
        font-size: 46px;
    }

    h2 {
        font-size: 34px;
    }

    h3 {
        font-size: 24px;
    }

    h4 {
        font-size: 20px;
    }

    h5 {
        font-size: 15px;
    }

    p {
        font-size: 13px;
    }
    
    p.small {
        font-size: 11px;
    }

    p.x-small {
        font-size: 9px;
        text-transform: uppercase;
    }
}
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=163%3A3892)
