### ISSUE TITLE
[TASK] Implement reusable Webb Logo component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#506]
## Task Description

The purpose of this task is to implement a reusable `Logo` component that can be exported for external use. The `Logo` component makes it easy to add Webb specific logo into the application.

## Task Deliverable

- [x]  Create a folder `Logo` folder
- [x]  Implement a `Logo` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example

**Component properties:**

- size="large | medium | small";
- align = “center | inherit | justify | left | right”
- dark-mode= on|off;

**Example usage:**

```bash
import { Logo } from '@webb/Logo';

<Logo size="medium" align="left" darkmode="off" />
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A12587)

**Comment by dutterbutter** [comment]
Closed in #540
