### ISSUE TITLE
[TASK] Implement reusable Avatar component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#507]
## Task Description

The purpose of this task is to implement a reusable Avatar component that can be exported for external use.  Avatars can be used throughout the dapp to represent entities and specifically Avatars are used to display validators and authority sets.

**Note:** used in conjunction with user ID or in table; should not be used itself without supplementary content.

## Task Deliverable

- [x]  Create a folder `Avatar`
- [x]  Implement the `Avatar` component with the applicable props
- [x]  Create a folder `AvatarGroup`
- [x]  Implement the `AvatarGroup` component with the applicable props
- [x]  Implement both dark and light variations
- [x]  Document each component with an example
- [x]  Ensure component is exportable

**Component properties:**

- size="small | regular";
- type="single | stacked";
- dark mode="off | on";

### Sizes

You should be able to change the size of the avatar with the `height`and `width`CSS properties. However the default sizes should be as followed:

- small: 24x24
- regular: 48x48

**Example:**

```bash
<Avatar
  alt="Webb Logo"
  src="webblogo.png"
  sx={{ width: 24, height: 24 }}
/>
```

### Stacked

`AvatarGroup`renders its children as a stack. Use the `max`prop to limit the number of avatars. If you need to control the total number of avatars not shown, you can use the `total` prop. This would add the total number of avatars not shown. See Figma designs for example. 

**Example:**

```bash
<AvatarGroup max={4}>
  <Avatar alt="Authority1" src="/static/images/avatar/1.jpg" />
  <Avatar alt="Authority2" src="/static/images/avatar/2.jpg" />
  <Avatar alt="Authority3" src="/static/images/avatar/3.jpg" />
</AvatarGroup>
```

## Relevant links

- [Figma Avatar Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=164%3A4553)

**Comment by dutterbutter** [comment]
Closed in #541
