### ISSUE TITLE
[TASK] Implement reusable Button component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#508]
## Task Description

The purpose of this task is to implement a reusable Button component that can be exported for external use. Buttons help users carry out an action. 

**Note:** write button text in clear, concise language; make use of the variety of buttons to make sure the most important action on the page takes precedent and the less important appear less prominent.

## Task Deliverable

- [ ]  Create a folder `Button`
- [ ]  Implement a Button component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable

### Button Component

The are variant types of Button that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the Button design system link at the bottom to view each different button type that are made up in this component. 

**Component properties:**

- Extrinsic properties passed by props
    - size="regular | small";
    - color=””;
- type="primary | secondary | utility | link ";
- size="regular | small";
- state="default | hover | pressed | disabled";
- icon="no-icon | icon-left | icon-right";
- dark mode="off | on";

**Example usage:**

```bash
< Button
  type="primary"
  dark-mode="off"
  icon="no-icon"
  state="default"
  size="regular" 
/>

```

```tsx
< Button
	size="regular"
	leftIcon?=<jsx element>
	rightIcon?=<jsx element>
>
   Text
</Button>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=164%3A4027)
