### ISSUE TITLE
[TASK] Implement reusable Chip component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#509]
## Task Description

The purpose of this task is to implement a reusable Chip component that can be exported for external use. Chips are compact elements that represent a state, attribute, or action.

## Task Deliverable

- [x]  Create a folder `Chip`
- [x]  Implement a Chip component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Chip Component

The are variant types of `Chip` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Chip` design system link at the bottom to view each different chip type that are made up in this component. 

**Component properties:**

- color="green | blue | purple | yellow | red";
- state="default | disabled";
- dark mode="off | on";

**Example usage:**

```bash
<Chip
  color="green"
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=164%3A4609)
