### ISSUE TITLE
[TASK] Implement reusable Checkbox component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#510]
## Task Description

The purpose of this task is to implement a reusable `Checkbox` component that can be exported for external use. `Checkbox` are compact elements that represent a state, attribute, or action.

## Task Deliverable

- [x]  Create a folder `Checkbox`
- [x]  Implement a `Checkbox` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Checkbox Component

The are variant types of `Checkbox` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Checkbox` design system link at the bottom to view each different `Checkbox` type that are made up in this component. 

**Component properties:**

- state="unchecked | checked | hover | disabled";
- dark mode="off | on";
- label=”string” | disabled
- size

**Example usage:**

```bash
<Checkbox
  state="unchecked"
  dark-mode="off"
  label="Wrap Assets?"
  size="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=164%3A4880)
