### ISSUE TITLE
[TASK] Implement reusable Input component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#511]
## Task Description

The purpose of this task is to implement a reusable `Input` component that can be exported for external use. Input fields allow users to enter values, or data that fulfills an operation.

## Task Deliverable

- [x]  Create a folder `Input`
- [x]  Implement a `Input` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Input Component

The are variant types of `Input` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Input` design system link at the bottom to view each different `Input` type that are made up in this component. 

**Component properties:**

- Type="text | text-large | search | dropdown";
- State="default | hover | active | error";
- Darkmode="off | on";
- icon="off | on";

**Example usage:**

```bash
<Input
  type="text"
  dark-mode="off"
  icon="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A7579)

**Comment by dutterbutter** [comment]
Closed in #546
