### ISSUE TITLE
[TASK] Implement reusable Slider component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#512]
## Task Description

The purpose of this task is to implement a reusable `Slider` component that can be exported for external use. Sliders depict certain state or weight. 

## Task Deliverable

- [x]  Create a folder `Slider`
- [x]  Implement a `Slider` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Slider` Component

The are variant types of `Slider` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Slider` design system link at the bottom to view each different `Slider` type that are made up in this component. 

**Component properties:**

- type="default | range | range-label";
- dark mode="off | on";

**Example usage:**

```bash
<Slider
  type="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A10134)

**Comment by dutterbutter** [comment]
Closed in #549
