### ISSUE TITLE
[TASK] Implement reusable Tooltip component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#513]
## Task Description

The purpose of this task is to implement a reusable `Tooltip` component that can be exported for external use. 

**Uses:**

- Provide tooltips for unlabeled icons.
- Position tooltips so they don’t block related content.
- For readability purposes, max length of tooltips is 300px.
- Users should be able to exit the tooltip by tapping outside the tooltip.

## Task Deliverable

- [x]  Create a folder `Tooltip`
- [x]  Implement a `Tooltip` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Tooltip Component

The are variant types of `Tooltip` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Tooltip` design system link at the bottom to view each different `Tooltip` type that are made up in this component. 

**Component properties:**

- type="text-only | text-title | title-text-button | text-only-copy";
- position="bottom-m | top-m | ";
- dark mode="off";

**Example usage:**

```bash
<Tooltip
  type="text-only"
  dark-mode="off"
  position="top-m"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A7429)

**Comment by dutterbutter** [comment]
Closed in #552
