### ISSUE TITLE
[TASK] Implement reusable MenuItems component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#514]
## Task Description

The purpose of this task is to implement a reusable `MenuItem` component that can be exported for external use. Overlay menu allows users to pick from a list of action or items, like a filter or bulk action.

## Task Deliverable

- [x]  Create a folder `MenuItem`
- [x]  Implement a `MenuItem` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `MenuItem` Component

The are variant types of `MenuItem` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `MenuItem` design system link at the bottom to view each different `MenuItem` type that are made up in this component. 

**Component properties:**

- state="default | hover | active | disabled";
- icon="off | on";
- dark-mode=on | off;

**Example usage:**

```bash
<MenuItem
  state="default"
  dark-mode="off"
  icon="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A5080)
