### ISSUE TITLE
[TASK] Implement reusable Progress component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#515]
## Task Description

The purpose of this task is to implement a reusable `Progress` component that can be exported for external use. Overlay menu allows users to pick from a list of action or items, like a filter or bulk action.

## Task Deliverable

- [x]  Create a folder `Progress`
- [x]  Implement a `Progress` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Progress` Component

The are variant types of `Progress` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Progress` design system link at the bottom to view each different `Progress` type that are made up in this component. 

**Component properties:**

- size="small | default | large";
- dark-mode="off | on";

**Example usage:**

```bash
<Progress
  size="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.notion.so/TASK-Implement-reusable-Progress-component-a5ea98f1fa744c33909a37ef2e580cb6)

**Comment by dutterbutter** [comment]
Closed in #553
