### ISSUE TITLE
[TASK] Implement reusable Pagination component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#516]
## Task Description

The purpose of this task is to implement a reusable `Pagination` component that can be exported for external use. The `Pagination` component enables the user to select a specific page from a range of pages.

## Task Deliverable

- [x]  Create a folder `Pagination`
- [x]  Implement a `Pagination` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Pagination` Component

The are variant types of `Pagination` that are dictated by the props passed in. Below is a list of the components properties that are required. 

**Component properties:**

- state="active | inactive";
- dark mode="off | on";

**Example usage:**

```bash
<Pagination
  state="active"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A6857)

**Comment by dutterbutter** [comment]
Closed in #559
