### ISSUE TITLE
[TASK] Implement reusable Timeline component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#517]
## Task Description

The purpose of this task is to implement a reusable `Timeline` component that can be exported for external use. The timeline displays a list of events in chronological order.

## Task Deliverable

- [x]  Create a folder `Timeline`
- [x]  Implement a `Timeline` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Timeline` Component

The are variant types of `Timeline` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Timeline` design system link at the bottom to view each different `Timeline` type that are made up in this component. 

**Component properties:**

- Type="proposals | key";
- State="complete | in-progress";
- Dark Mode="off | on";

**Example usage:**

```bash
<Timeline
  type="proposals"
	state="complete"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A6195)
