### ISSUE TITLE
[TASK] Implement reusable FilterMenu component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#518]
## Task Description

The purpose of this task is to implement a reusable `FilterMenu` component that can be exported for external use. Overlay menu allows users to pick from a list of action or items, like a filter or bulk action.

## Task Deliverable

- [x]  Create a folder `FilterMenu`
- [x]  Implement a `FilterMenu` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `FilterMenu` Component

The are variant types of `FilterMenu` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `FilterMenu` design system link at the bottom to view each different `FilterMenu` type that are made up in this component. 

**Component properties:**

- state="default | uptime | reputation | location";
- dark-mode=on | off;
- type="collapsed | expanded-1 | expanded-2 | expanded-3";

**Example usage:**

```bash
<Timeline
  size="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=168%3A2401)

**Comment by dutterbutter** [comment]
Closed in #560
