### ISSUE TITLE
[TASK] Implement reusable Card component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#519]
## Task Description

The purpose of this task is to implement a reusable `Card` component that can be exported for external use. The Progress card is for surfacing progress status for the chain data (key status/network threshold)

## Task Deliverable

- [x]  Create a folder `Card`
- [x]  Implement a `Card` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Card` Component

The are variant types of `Card` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Card` design system link at the bottom to view each different `Card` type that are made up in this component. 

**Component properties:**

- type="key-status | network-threshold";
- dark mode="off | on";

**Example usage:**

```bash
<Card
  type="key-status"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A7065)
