### ISSUE TITLE
[TASK] Implement reusable Table component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#531]
## Task Description

The purpose of this task is to implement a reusable `Table` component that can be exported for external use. The `Table` component displays information in a grid-like format of rows and columns. They organize information in a way that’s easy to scan so that users can look for patterns and develop insights from data.

## Task Deliverable

- [x]  Create a folder `Table`
- [x]  Implement a `Table` component with the below mentioned props
- [x] Implement a `TableHeader` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### `Table` Component

The are variant types of `Table` that are dictated by the props passed in. Below is a list of the components properties that are required. 

**Component properties:**

- type="keygen | proposals | proposals-collapsed | ";
- state="default | hover | active";

### `TableHeader` Component

The are variant types of `Table` that are dictated by the props passed in. Below is a list of the components properties that are required. 

**Component properties:**

- property="proposals | keygen | participants";

**Example usage:**

```bash
<Table
  state="default"
  type="proposals"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A8668)

**Comment by dutterbutter** [comment]
Closed in #559
