### ISSUE TITLE
[FEAT] Implement account dashboard for improved user viewing experience  

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#538]
## User Story

> As a user, I want to be able to view my account data so that I can manage my secret notes in an easy and accessible manner.
> 

> As a user, I want to be able to view my note balances so that I easily recall the withdrawal-able balances on the respected destination chain.
> 

---

## Feature Details

The account dashboard will enable users to view their registered account details and for the first iteration will focus on expressing account balances and management of secret notes. In the future iterations this account dashboard may evolve to include deposits in the pool, total rewards and other protocol specific details related to the registered account. 

### Initial Feature List

- Display note account key
- Display note account balance
    - Total balance across all notes
    - Balance per destination chain
- Load and decrypt all of your private notes with NoteAccount key
    - Can only do this for the currently connected chain
- Remove account info from current browser session
- Download raw private notes
- Display MetaMask public address used to create NoteAccount

### Data Required

The data required to display the note account consist of:

- The users NoteAccount
- Address used for account derivation
- Parsed secret notes

### Task Checklist

**NOTE:** UI implementation of dashboard should be considered primitive until appropriate designs are prepared. 

- [ ]  Create NoteAccount Page
- [ ]  Fetch Notes on button click
    - [ ]  Query the chain for all encrypted commitments emitted on `transact`
    - [ ]  Attempt to decrypt each commitment with the configured `NoteAccount`
    - [ ]  If successful, store in the `NoteAccount`
- [ ]  Remove account info from browser session
    - [ ]  Add a button for ‘purge account’ in addition to ‘logout account’
    - [ ]  On purge account click, logout and remove from `localStorage`
- [ ]  Display NoteAccount Balance
    - [ ]  Iterate over loaded notes in the `NoteAccount`, display the total balance grouped first by destination chain, then by asset.
        - [ ]  Some overall across all chains balance for webb tokens
