### ISSUE TITLE
[TASK] Add storybook for UI documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#572]
## Overview

Given we will have a comprehensive webb-ui-kit that includes reusable components for our various applications (e.g. bridge, stats) we should provide adequate documentation. A number of people have suggested [Storybook](https://storybook.js.org/) to utilize. Storybook does a lot more than just documenting react components but also assists with visual testing and QA. **Note:** this task only requires component documentation and not testing requirements, although you may review how Storybook enables visual testing [here](url).

The only tradeoff I see in utilizing Storybook is that it would be a separately hosted site specifically for component documentation which fragments itself from the existing Webb docs site. I tend to think this tradeoff is fine, and we would certainly reference / link to it from the Webb doc site. 

## Task Checklist 

- [x] [Install storybook](https://storybook.js.org/docs/ember/get-started/install) into the webb-dapp monorepo 
- [x] Setup stories for documentation, see below list
- [x] Setup Github pages with Webb domain
- [ ] Add reference to documentation in Webb docs site

### Stories checklist

- [x] Add story and written documentation for Avatar component 
- [x] Add story and written documentation for AvatarGroup component 
- [x] Add story and written documentation for Button component 
- [x] Add story and written documentation for Card component 
- [x] Add story and written documentation for CardTable component 
- [x] Add story and written documentation for Checkbox component 
- [x] Add story and written documentation for Chip component 
- [x] Add story and written documentation for Collapsible component 
- [x] Add story and written documentation for Tooltip component 
- [x] Add story and written documentation for Dropdown component 
- [x] Add story and written documentation for Filter component 
- [x] Add story and written documentation for Inputs component 
- [x] Add story and written documentation for KeyCard component 
- [x] Add story and written documentation for KeyCardStatus component 
- [x] Add story and written documentation for Label component 
- [x] Add story and written documentation for Logo component 
- [x] Add story and written documentation for MenuItem component 
- [x] Add story and written documentation for NetworkThresholdCard component 
- [x] Add story and written documentation for Pagination component 
- [x] Add story and written documentation for Progress component 
- [x] Add story and written documentation for Slider component 
- [ ] Add story and written documentation for Table component 
- [x] Add story and written documentation for ThemeSwitcher component 
- [x] Add story and written documentation for Timeline component 
- [x] Add story and written documentation for TimeProgress component 
- [x] Add story and written documentation for Title component 
- [ ] Add story and written documentation for Colors

### Other TODOs:
- [ ] Production optimization webpack build 
- [ ] Introduction copy
- [ ] Documentation for Introduction page (e.g. styling, configuration)
- [ ] Add to `README.md`

### Relevant links

- Writing stories for components [docs](https://storybook.js.org/docs/ember/get-started/setup)
- Writing [documentation](https://storybook.js.org/docs/ember/writing-docs/introduction) for components

**Comment by dutterbutter** [comment]
Preview storybook here: https://webb-tools.github.io/webb-dapp/
