### ISSUE TITLE
[TASK] Add Bridge UI components to Webb UI kit

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#587]
## Overview 

The goal of this checklist is to create a comprehensive list of UI components to be implemented that collectively make up the Bridge UI. The Webb UI kit will be used throughout the product and will exist as a sub package in the current `webb-dapp` repo. 

The below divides up the design system into various component types that will be translated into generalized reusable components to be used within the Bridge. 

It should be as easy as:

```
import * as React from 'react';
import Button from '@webb-ui-kit/Switch';

function App() {
  return <Switch state="default"/>
}
```

## Tasks Checklist

**NOTE:** These components should be implemented incrementally and PR'd / merged accordingly. We should be implementing, opening PR, reviewing, and merging the below listed components frequently and never contain too much code. 

- [ ] Ensure each component is well documented

### Molecules 

- [ ] [TASK] Implement reusable Input component for bridge
- [ ] [TASK] Implement reusable Switch component
- [ ] [TASK] Implement reusable ScrollBar component
- [ ] [TASK] Implement reusable TokenSelector component

### Organisms 

- [ ] [TASK] Implement reusable ListCards component 
- [ ] [TASK] Implement reusable BridgeControlCards component 
- [ ] [TASK] Implement reusable ConfirmationCards component 
- [ ] [TASK] Implement reusable WalletConnectionCard component
- [ ] [TASK] Implement reusable TransactionDetailsCard component 
- [ ] [TASK] Implement reusable ControlMenu component 
- [ ] [TASK] Implement reusable AmountMenu component 

### Relevant Links

- [Figma guide for developers](https://www.notion.so/hicommonwealth/Figma-Guide-for-Developers-21744fc512ba4d51aefe91d00985026d)
- [Bridge Prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=573%3A49893&scaling=min-zoom&page-id=573%3A49358&starting-point-node-id=573%3A49635&show-proto-sidebar=1)
