### ISSUE TITLE
[TASK] Implement reusable Input component for bridge

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#588]
## Task Description

The purpose of this task is to implement a reusable `Input` component that can be exported for external use. Input fields allow users to enter values, or data that fulfills an operation.

## Task Deliverable

- [x]  Implement a `Input` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Input Component

The are variant types of `Input` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `Input` design system link at the bottom to view each different `Input` type that are made up in this component. 

**Component properties:**
Recipient
- Type="bridge | token | destination | amount | custom-amount | fixed-amount | recipient | shielded | relayer`";
- State="unfilled | filled | active ";
- Darkmode="off | on";

**Example usage:**

```bash
<Input
  type="bridge"
  dark-mode="off"
  state="active"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=167%3A7579)
