### ISSUE TITLE
[TASK] Implement reusable Switch component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#589]
## Task Description

The purpose of this task is to implement a reusable `Switch` component that can be exported for external use. Switches indicate an intended action or boolean value (e.g. enable or disable). 

## Task Deliverable

- [x]  Create a folder `switch`
- [x]  Implement a `switch` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### Switch Component

**Component properties:**

- State="default | hover | checked | disabled";
- Darkmode="off | on";

**Example usage:**

```bash
<Switch
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1132%3A10449)
