### ISSUE TITLE
[TASK] Implement reusable ScrollBar component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#590]
## Task Description

The purpose of this task is to implement a reusable `ScrollBar` component that can be exported for external use. ScrollBars allow users to view additional items in a drop down list. 

## Task Deliverable

- [x]  Create a folder `ScrollBar`
- [x]  Implement a `ScrollBar` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### ScrollBar Component

**Component properties:**

- Position="top | middle | bottom";
- Darkmode="off | on";

**Example usage:**

```bash
<ScrollBar
  position="top"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1341%3A40425)
