### ISSUE TITLE
[TASK] Implement reusable TokenSelector component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#591]
## Task Description

The purpose of this task is to implement a reusable `TokenSelector ` component that can be exported for external use. TokenSelector allows users to select varying token assets. 

## Task Deliverable

- [x]  Create a folder `TokenSelector `
- [x]  Implement a `TokenSelector ` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### TokenSelector Component

**Component properties:**

- State="default | selected | hover";
- Darkmode="off | on";

**Example usage:**

```bash
<TokenSelector
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A21351)
