### ISSUE TITLE
[TASK] Implement reusable ListCards component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#592]
## Task Description

The purpose of this task is to implement a reusable `ListCards ` component that can be exported for external use. Input fields allow users to enter values, or data that fulfills an operation.

## Task Deliverable

- [x]  Create a folder `ListCards `
- [x]  Implement a `ListCards ` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### ListCards Component

The are variant types of `ListCards` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `ListCards` design system link at the bottom to view each different `ListCards` type that are made up in this component. 

**Component properties:**

- Type="source | destination | search | deposit";
- State="default | active | search | hover | disconnected ";
- Darkmode="off | on";

**Example usage:**

```bash
<ListCard
  type="source"
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A22678)
