### ISSUE TITLE
[TASK] Implement reusable BridgeControlCards component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#593]
## Task Description

The purpose of this task is to implement a reusable `BridgeControlCards ` component that can be exported for external use. 

## Task Deliverable

- [x]  Create a folder `BridgeControlCards `
- [x]  Implement a `BridgeControlCards` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

**There are three BridgeControlCards included in this task:**
- [x] Transfer card
- [x] Withdraw card
- [x] Deposit card

### BridgeControlCards Component

The are variant types of `BridgeControlCards` that are dictated by the props passed in. Please refer to the `BridgeControlCards` design system link at the bottom to view each different `BridgeControlCards ` type that are made up in this component. 

**Example usage:**

```bash
<BridgeControlCards
  state="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A31293)

**Comment by dutterbutter** [comment]
Closed in #655
