### ISSUE TITLE
[TASK] Implement reusable ConfirmationCards component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#594]
## Task Description

The purpose of this task is to implement a reusable `ConfirmationCards ` component that can be exported for external use. 

## Task Deliverable

- [x]  Create a folder `ConfirmationCards `
- [x]  Implement a `ConfirmationCards ` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable

### ConfirmationCards Component

The are variant types of `ConfirmationCards` that are dictated by the props passed in. Please refer to the `ConfirmationCards` design system link at the bottom to view each different `ConfirmationCards` type that are made up in this component. 

**Example usage:**

```bash
<ConfirmationCards
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A29476)
