### ISSUE TITLE
[TASK] Implement reusable WalletConnectionCard component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#595]
## Task Description

The purpose of this task is to implement a reusable `WalletConnectionCard ` component that can be exported for external use.

## Task Deliverable

- [x]  Create a folder `WalletConnectionCard `
- [x]  Implement a `WalletConnectionCard ` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable
- [x] Add component documentation to `/stories` dir

### WalletConnectionCard Component

The are variant types of `WalletConnectionCard ` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `WalletConnectionCard ` design system link at the bottom to view each different `WalletConnectionCard ` type that are made up in this component. 

**Component properties:**

- State="default | pending | failed ";
- Darkmode="off | on";

**Example usage:**

```bash
< WalletConnectionCard
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A25438)
