### ISSUE TITLE
[TASK] Implement reusable TransactionProgressCard component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#596]
## Task Description

The purpose of this task is to implement a reusable `TransactionProgressCard ` component that can be exported for external use. 

## Task Deliverable

- [x]  Create a folder `TransactionProgressCard `
- [x]  Implement a `TransactionProgressCard ` component with the below mentioned props
- [x]  Ensure the implementation reflects the intended design
- [x]  Document each component with an example
- [x]  Ensure component is exportable
- [x] Add component documentation to `/stories` dir

### TransactionProgressCard Component

The are variant types of `TransactionProgressCard ` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `TransactionProgressCard ` design system link at the bottom to view each different `TransactionProgressCard ` type that are made up in this component. 

**Component properties:**

- Type="in-progress | warning | completed ";
- State="default | collapsed | expanded";
- Darkmode="off | on";

**Example usage:**

```bash
<TransactionProgressCard
  type="completed"
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A22610)
