### ISSUE TITLE
[TASK] Implement reusable ControlMenu component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#597]
## Task Description

The purpose of this task is to implement a reusable `ControlMenu ` component that can be exported for external use. 

## Task Deliverable

- [ ]  Create a folder `ControlMenu `
- [ ]  Implement a `ControlMenu` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable

### ControlMenu Component

The are variant types of `ControlMenu` that are dictated by the props passed in. Below is a list of the components properties that are required. Please refer to the `ControlMenu` design system link at the bottom to view each different `ControlMenu` type that are made up in this component. 

**Component properties:**

- State="collapsed | expanded ";
- Darkmode="off | on";
- icon="right | left";

**Example usage:**

```bash
<ControlMenu
  dark-mode="off"
  icon="right"
  state="collapsed"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A21368)
