### ISSUE TITLE
[TASK] Implement reusable AmountMenu component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#598]
## Task Description

The purpose of this task is to implement a reusable `AmountMenu ` component that can be exported for external use. 

## Task Deliverable

- [ ]  Create a folder `AmountMenu `
- [ ]  Implement a `AmountMenu ` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable

### AmountMenu Component

The are variant types of `AmountMenu` that are dictated by the props passed in. Please refer to the `AmountMenu` design system link at the bottom to view each different `AmountMenu` type that are made up in this component. 

**Example usage:**

```bash
<AmountMenu
  dark-mode="off"
  state="default"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1341%3A40712)
