### ISSUE TITLE
[CHECKLIST] Fixes and design improvements to stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#619]
## Overview
Below is a list of items that were identified during an initial qa of the stats page. 

## Task Checklist

- [ ] Increase and be more consistent with font size 
- [ ] Add txhashes where applicable 
- [ ] Header of authorities detail page needs to be larger and legible (e.g. show full id)
- [ ] Remove pending table row from authorities detail page
- [ ] Ensure all tables are sorted by latest 
- [ ] Fix any routing issues navigating between pages 
- [ ] Add more descriptive languages when presenting threshold and validator counts in details page 

@monaiuu @seeddisperser It would be great if you two can assist with updating designs to reflect element changes (e.g. header of authority detail page)

**Comment by monaiuu** [comment]
Authorities UI Updates:
* removed pending table row from the authorities detail page
* increased margins for header of authorities detail page in side panel view
* display full ID 
<img width="1792" alt="Screen Shot 2022-09-29 at 12 19 21 PM" src="https://user-images.githubusercontent.com/109539270/193123096-af1d61ba-ff12-4b4b-ac44-75075fc1869d.png">

Please review and provide feedback. Will implement updates in the figma file once approved.

*note: font sizes in table rows has not been updated, will look into it w/ @seeddisperser

**Comment by dutterbutter** [comment]
@seeddisperser please review all font sizes and the consistency throughout the stats page. You can view a live version [here](https://www.stats-dev.webb.tools/#/proposals). Note you may see a page error upon a key transition, please just refresh the page - its currently being fixed.

**Comment by seeddisperser** [comment]
### Please see [update type scale](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?node-id=2%3A62) implemented across the stats page designs.

Response to the linked implementation:
- all chips need to be `text-transform: uppercase`
- on network threshold, the "view history" link should lead to the [network threshold data visualization](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?node-id=328%3A111009). (Or if this isn't being included in this sprint, that button should be removed).
- The "Upcoming Thresholds" table has the table head elements in the wrong font-size (should be `body 01 bold`). 
- the active tabs/links/pagination should be `cursor: pointer;`. A user should be able to click on the tab even if they are on it. 
- filters on the key page need some attention. there are some css issues.

**Comment by dutterbutter** [comment]
@AtelyPham please review @seeddisperser comments regarding type scale and implement the corresponding changes please.

**Comment by monaiuu** [comment]
**Quick UI Fixes for dev team:**

- [ ] matching proposal tags colours (green: for, red: against, blue: abstain)
- [ ] default to active state for 'all' tab 

<img width="747" alt="Screen Shot 2022-09-30 at 11 33 39 AM" src="https://user-images.githubusercontent.com/109539270/193335221-92eeb861-f280-4cbc-8350-8d2648fd3618.png">
<img width="1145" alt="Screen Shot 2022-09-30 at 11 33 58 AM" src="https://user-images.githubusercontent.com/109539270/193335650-c412166d-ff02-4164-9a9f-dfafdda6f698.png">

**Fixes required for design team:**

- [ ] hover state for table rows is coinciding w/chip
<img width="1189" alt="Screen Shot 2022-09-30 at 11 31 03 AM" src="https://user-images.githubusercontent.com/109539270/193336275-8b904229-88a5-49d8-8e1e-115776753c7b.png">

**Comment by monaiuu** [comment]
**Quick fix for Dev Team:**

- [ ] Reverse chevron arrow direction during dropdown (https://mui.com/material-ui/react-select/)
<img width="148" alt="Screen Shot 2022-10-04 at 5 03 25 PM" src="https://user-images.githubusercontent.com/109539270/193952167-e0dc9b95-7008-4f3b-81d2-d21da83591fe.png">
<img width="213" alt="Screen Shot 2022-10-04 at 5 03 32 PM" src="https://user-images.githubusercontent.com/109539270/193952144-53a2a981-8449-4f6b-bae6-cdb184b86f4e.png">

**Comment by monaiuu** [comment]
**UI Fixes Required for Design Team** (@seeddisperser @monaiuu)

- [ ] Work on loading states during data rendering
<img width="580" alt="Screen Shot 2022-10-04 at 4 56 46 PM" src="https://user-images.githubusercontent.com/109539270/193952511-3e0d971f-6cb8-4d0b-942e-8c189aed6803.png">

- [ ] Improve top navigation items states
<img width="580" alt="Screen Shot 2022-10-04 at 5 10 37 PM" src="https://user-images.githubusercontent.com/109539270/193952819-ce92768f-d42a-44dc-beef-556b50614049.png">

- [ ] Create better error screens & messages (discussion required on possible error messages)
<img width="1321" alt="Screen Shot 2022-10-04 at 4 56 33 PM" src="https://user-images.githubusercontent.com/109539270/193953008-24a4f6e6-5b7e-402a-901b-bb481379bbfa.png">

**Comment by dutterbutter** [comment]
Additional small fixes that need to be addressed: 

- [ ] Remove ";" from loading spinner (see below image)
<img width="79" alt="Screen Shot 2022-10-13 at 9 56 46 AM" src="https://user-images.githubusercontent.com/29983536/196201514-b6efa69e-0983-41fb-8dfc-c62137cf8d88.png">

---

- [ ] Remove blank box from authorities detail page (see image below)
![Screen Shot 2022-10-17 at 9 16 18 AM](https://user-images.githubusercontent.com/29983536/196201807-ef8755f8-0eb3-4fb8-8750-6040b4681934.png)

---

- [ ] Remove dead link from keys detail page (see image below)
![Screen Shot 2022-10-17 at 9 16 54 AM](https://user-images.githubusercontent.com/29983536/196202071-ee35d308-cb77-48a3-bad8-5cedd106092d.png)

---

- [ ] Populate proposer identities in Proposal details page (see image below)
![Screen Shot 2022-10-17 at 9 16 05 AM](https://user-images.githubusercontent.com/29983536/196202322-7c8d53d1-c0cd-4522-bbd7-7a220bda5d5c.png)

---

- [ ] Add empty donut chart state when zero proposals have been signed in duration on Proposal page 
![Screen Shot 2022-10-17 at 9 15 50 AM](https://user-images.githubusercontent.com/29983536/196202674-6c7aa6f0-f448-4cca-bc41-c701a95212ed.png)

**Comment by AtelyPham** [comment]
The chain does not match between table data and detail. @AhmedKorim 

https://user-images.githubusercontent.com/60747384/200587838-01709319-6a72-4e0f-b914-4e9d8bd27820.mp4
