### ISSUE TITLE
[TASK] Implement reusable AccountControl component(s)

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#640]
## Task Description

The purpose of this task is to implement a reusable `AccountControl ` components that can be exported for external use. The below components are used to control user’s account, with features that allow users to sync notes, clear data, switch wallet/account, and disconnect.

## Task Deliverable

- [ ]  Create a folder `AccountControl `
- [ ]  Implement a `AccountControl` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable
- [ ] Add component documentation to `/stories` dir

### AccountControl Component

**Example usage:**

```bash
<AccountControl
  state="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1834%3A18286)

**Comment by dutterbutter** [comment]
Included in #671
