### ISSUE TITLE
[TASK] Implement reusable WalletConnection component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#641]
## Task Description

The purpose of this task is to implement a reusable `WalletConnection` components that can be exported for external use. 

## Task Deliverable

- [ ]  Create a folder `WalletConnection`
- [ ]  Implement a `WalletConnection` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable

### WalletConnection Component

**Example usage:**

```bash
< WalletConnection
  state="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1936%3A25618)

**Comment by dutterbutter** [comment]
Duplicate of #595
