### ISSUE TITLE
[TASK] Implement reusable DialogModal component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#642]
## Task Description

The purpose of this task is to implement a reusable `DialogModal ` components that can be exported for external use. A modal dialog is a dialog that appears on top of the main content and moves the system into a special mode requiring user interaction. This dialog disables the main content until the user explicitly interacts with the modal dialog.

## Task Deliverable

- [ ]  Create a folder `DialogModal `
- [ ]  Implement a `DialogModal` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable
- [ ] Add component documentation to `/stories` dir

### DialogModal Component

**Example usage:**

```bash
< DialogModal
  state="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=170%3A1875)

**Comment by dutterbutter** [comment]
Included in #671
