### ISSUE TITLE
[TASK] Implement reusable NotesTable component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#643]
## Task Description

The purpose of this task is to implement a reusable `NotesTable ` components that can be exported for external use. The below tables display user’s available spend notes within local storage for easy access and management. The [No Data] variant is displayed by default for users without spend notes.

Sorting behavior: https://mui.com/x/react-data-grid/sorting/

## Task Deliverable

- [ ]  Create a folder `NotesTable `
- [ ]  Implement a `NotesTable ` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable
- [ ] Add component documentation to `/stories` dir

### NotesTable Component

**Example usage:**

```bash
< NotesTable
  type="spend | shielded"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1927%3A26061)

**Comment by dutterbutter** [comment]
Included in #671
