### ISSUE TITLE
[TASK] Implement reusable UploadNotesModal component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#644]
## Task Description

The purpose of this task is to implement a reusable `UploadNotesModal` components that can be exported for external use. The below fields are used to upload user’s spend notes so that users can easily manage and view their available spend notes on the Webb dApp. 

## Task Deliverable

- [ ]  Create a folder `UploadNotesModal`
- [ ]  Implement a `UploadNotesModal` component with the below mentioned props
- [ ]  Ensure the implementation reflects the intended design
- [ ]  Document each component with an example
- [ ]  Ensure component is exportable
- [ ] Add component documentation to `/stories` dir

### UploadNotesModal Component

**Props:**

Type="upload" | "paste";
State="loading" | "default" | "filled" | "success" | "error" | "stacked";
dark mode=false;

**Example usage:**

```bash
< UploadNotesModal
  type="upload"
  state="default"
  dark-mode="off"
/>
```

## Relevant links

- [Figma Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1860%3A18714)

**Comment by dutterbutter** [comment]
Included in #671
