### ISSUE TITLE
[TASK] Implement reusable Alert component

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#674]
## Overview
The goal is to implement the reusable `Alert` organisms component 

## Task Deliverable
- [x] Implement the component under `Alert`
- [x] Add a provider for the toast notifications with a programmatic interface
    - [x] `useAlert` hook 
- [x] Support toast/notification stacking 
- [x] Add story book with examples for the component
- [x] Document each component with examples

```jsx

<AlertProvider>
..
<Alert
varaint="success"
message="The address was copied"
/>
..
<AlertProvider/>
```

**Links**
- [Alert component figma desgin](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1834%3A16653&viewport=-2077%2C-415%2C0.39)
- https://tailwindcss-radix.vercel.app/#toast

**Comment by AtelyPham** [comment]
Closes in PR https://github.com/webb-tools/webb-dapp/pull/694
