### ISSUE TITLE
[TASK] Adding reusable Accordion component

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#676]
## Overview 
Similar to the Collablsable it's required to add an Accordion component to allow only one content to be displayed at once

## Task Deliverable

- [x]  Implement the organisms component under the `Accordaion`
- [x]  Add story book with examples of the component
- [x]  Document each component with examples

**Related links**
- https://www.radix-ui.com/docs/primitives/components/accordion

**Comment by AhmedKorim** [comment]
This component is required for the filter component for the stats @dutterbutter

**Comment by dutterbutter** [comment]
Closed in #677
