### ISSUE TITLE
[TASK] Use polkadotAPI to retrieve values when SubQuery is disrupted

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#681]
### Overview

On occasion the SubQuery backend is disrupted or fails to serve data to the front end to be displayed causing the dApp to crash or display non-values. We need to add a fallback mechanism to ensure when that happens we rely on the polkadotAPI for those values to ensure the persistence of the stats dApp. 

Below is table of API calls for specific data points. Although not entirely complete we can add to it accordingly. 

Metric | RPC / chain state call | Desc
-- | -- | --
Keygen threshold | api.query.dkg.keygenThreshold(); | Returns the current keygen threshold
Next Keygen threshold | api.query.dkg.nextKeygenThreshold(); | Returns the next keygen threshold
Signature threshold | api.query.dkg.signatureThreshold(); | Returns the current signature threshold
Next Keygen threshold | api.query.dkg.nextSignatureThreshold(); | Returns the next signature threshold
Current authority set | api.query.dkg.authorities | Returns the current authority set
Next authority set | api.query.dkg.nextAuthorities() | Returns the next authority set
Proposer threshold | api.query.dkgProposals.proposerThreshold() | Returns the current proposer threshold
Block number | api.query.system.number(); | Returns the current block number
Active key | api.query.dkg.dkgPublicKey() | Returns the active dkg public key
Number of participants | api.query.dkg.authorities() | Returns the current authority set
Number of proposers | api.query.dkgProposals.proposerCount() | Returns the number of proposers
Time until next rotation |   |  
Sign attempts |   |  
Number of signed proposals by type | api.query.dkgProposalHandler.signedProposals() | Returns a collection of signed proposals
Number of unsigned proposals in queue by type | api.query.dkgProposalHandler.unsignedProposalQueue() | Returns a collection of unsigned proposals in queue
  |   |  

### Task Checklist

- [ ] Create conditional to use polkadotAPI when SubQuery backend fails 
- [ ] Identify all data points and endpoints required 
- [ ] Test to ensure when the SubQuery backend goes down data is still served to the frontend

**Comment by dutterbutter** [comment]
Closed in #687
