### ISSUE TITLE
[QA] Checklist of fixes required for stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#687]
## Overview

Below is a list of items that were identified during a QA of the stats page. Items will iteratively added here throughout QA session review. 

### Task Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/669
- [x] #698 
- [x] https://github.com/webb-tools/webb-dapp/issues/685
- [x] https://github.com/webb-tools/webb-dapp/issues/684
- [x] https://github.com/webb-tools/webb-dapp/issues/686
- [x] #651
- [x] https://github.com/webb-tools/webb-dapp/issues/688
