### ISSUE TITLE
[TASK] Account Creation Flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#689]
## Overview

In order for users to manage their notes they first need to create a note-account prior to depositing. 

### Account Creation Flow

1. User selects 'Create account' 
2. User selects 'Get Started'
3. User Signs message with MetaMask
4. User can proceed to deposit 

The one flow that needs to be considered, is if a user has already created their account, leaves the dApp and comes back how should we handle that case? Given the user can login to the dApp using the same MetaMask address they created the account with, it would be ideal if this is also the login flow. 

### Task Checklist

- [ ] Create Note Account modal 

The 'Learn More' links will navigate a user to the appropriate section on the docs site. This section will be provided. 

- [ ] Prompts user to sign message with MetaMask 
- [ ] Post-signature Account Modal 

The content of this modal that is displayed in the below Figma files is slightly inaccurate and will require updating. That content will be provided to you. Again the 'Learn More' link will navigate a user to the appropriate section on the docs site. This section will be provided. 

### [Figma Prototype](https://www.figma.com/proto/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?page-id=562%3A149221&node-id=664%3A139038&viewport=-8102%2C3148%2C1.19&scaling=scale-down&starting-point-node-id=664%3A140053&show-proto-sidebar=1)

**Comment by dutterbutter** [comment]
Included in #671
