### ISSUE TITLE
[TASK] Tangle stats design improvement

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#693]
## Overview

The intended goal of the new design elements are to provide additional network data (e.g. best / finalized block) to users, and provide more intuitive navigation within the dApp. 

### Task Checklist 

- [ ] Add `Chips` highlighting Finalized, Best and Session 
- [ ] Add page navigation breadcrum 
- [ ] Remove 'Next Key' component and have 'Active Key' full width
- [ ] Added signed proposal stamps on Key progress bar & legend
- [ ] Proposal stamp on the progress bar opens up the Proposal Details view
- [ ] Remove donut chart and open proposal table in favour of stacked area chart of signed proposals filtered over time
- [ ] Added proposal type legends, with hover tooltips to educate each proposal type 

### [Figma Prototype](https://www.figma.com/proto/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?page-id=979%3A60395&node-id=1068%3A100212&viewport=-51562%2C-22409%2C1.62&scaling=scale-down&starting-point-node-id=1068%3A100212&show-proto-sidebar=1)
