### ISSUE TITLE
[TASK] Remove deprecated network RPC's, and update to latest testnet RPC's

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#704]
## Overview 

Since the eth2 merge testnets have become deprecated. Our dApp is still interacting with these deprecated testnets and should remove them, and switch over to their updated counterpart. 

### Task Checklist 

- [x] Remove / update deprecated chains / testnet configurations in [WebbProvider](https://github.com/webb-tools/webb-dapp/blob/develop/libs/api-provider-environment/src/WebbProvider.tsx) 
- [x] Remove / update deprecated chains / testnet configurations in [dapp-config](https://github.com/webb-tools/webb-dapp/blob/develop/libs/dapp-config/src/chains/evm/index.tsx)
- [x] Test each chain to ensure dApp connects to each available network 

### Relevant Links 

- For a list of testnet chain configurations please review testnet list [here](https://www.notion.so/hicommonwealth/Bridge-Testnet-Deployments-Options-846bbf7802154d97bad79ea745f458a1).
