### ISSUE TITLE
[TASK] Add wrap and deposit flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#705]
## Overview 

Currently the deposit flow does not contain the wrap and deposit flow. A user should be able to select an asset (e.g. `ETH`) from the token selection, and then the dApp should detect that selection and move to a wrap and deposit form (see image below). If the user selects a bridged asset (e.g. `webbETH`) to deposit into the bridge, then we do not need to show the wrap and deposit form as that asset can be deposited directly into the bridge. The figma link below illustrates how the flow should look. 

<img width="367" alt="Screen Shot 2022-11-21 at 4 04 16 PM" src="https://user-images.githubusercontent.com/29983536/203167270-677c3c44-b181-4a01-bbbc-d2b26a4fc989.png">

### Task Checklist 

- [x] Correctly detect non-wrapped asset 
- [x] Display wrap UI form showing the bridged asset
- [ ] Test wrap and deposit flow for each chain
- [ ] Test deposit flow for bridged asset
