### ISSUE TITLE
[TASK] Populate account table with applicable account data / notes

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#710]
## Overview 

When a user makes a deposit, transfer or withdraw we should be able to update their account table with the relevant note changes. We will need to fetch / store user notes based on their note account, and decode note data accordingly to display the proposed data in the account table.

### Task Checklist 

**Shielded Assets Tab** - This section aggregates a users notes by shielded asset and displays a summarized view 
- [ ] Display in a tabular form a summary of users shielded assets 
- [ ] Allow a user to have quick actions on those shielded assets (e.g. transfer, withdraw) 
- [ ] Display the chain, shielded asset (e.g. bridged asset), composition (e.g. `ETH`), available balance, number of notes to the user
 <img width="690" alt="Screen Shot 2022-11-21 at 4 14 41 PM" src="https://user-images.githubusercontent.com/29983536/203170132-45ea56b2-f667-4735-bf4f-620dfb5fe120.png">

**Available Spend Notes** - This section displays each individual note owned by the note account 
- [ ] Display in a tabular form a detailed view of each note stored by the note account
- [ ] Allow users to have quick actions for each of those notes (e.g. transfer, withdraw) 
- [ ] Display the chain, shielded asset (e.g. bridged asset), composition (e.g. `ETH`), balance, created date / time, subsequent deposits (e.g. the number of deposits placed after their own), the note itself 

<img width="689" alt="Screen Shot 2022-11-21 at 4 14 47 PM" src="https://user-images.githubusercontent.com/29983536/203170125-1e48d4a2-c30b-4c55-b06e-e937902da392.png">
