### ISSUE TITLE
[CHECKLIST] Implement successful deposit flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#711]
## Overview 

The goal of this checklist is to create a comprehensive list of tasks that collectively make up the successful and unsuccessful deposit flow for dApp users. 

### Deposit Flow

**Note:** Assumes a user has already connected their wallet and created their note account. 

**Deposit Scene-1 | Data Input** 
1. Selects token to deposit into bridge - if non-bridged asset (e.g. `webbETH`) then force deposit and wrap flow
2. Select destination chain 
3. Select amount to deposit 

<img width="389" alt="Screen Shot 2022-11-21 at 4 32 15 PM" src="https://user-images.githubusercontent.com/29983536/203171374-8f4fd457-3eac-4e59-95b1-257770a830cf.png">

**Deposit Scene-2 | Confirmation**
1. User confirms they have copied the new spend note 
2. User selects 'Deposit' 

<img width="393" alt="Screen Shot 2022-11-21 at 4 33 31 PM" src="https://user-images.githubusercontent.com/29983536/203171556-84a6dad2-362a-4e13-be5f-10bc6c1cbbbf.png">

**Deposit Scene-3 | Deposit In-progress**
1. Display the progress of the deposit 
2. User can select 'New Transaction' that will move progress view into accordion component to the right side and display deposit scene-1 

<img width="383" alt="Screen Shot 2022-11-21 at 4 34 36 PM" src="https://user-images.githubusercontent.com/29983536/203171895-dafa527a-45be-454c-9390-e16d7283e34d.png">

**Right-sided component**
<img width="278" alt="Screen Shot 2022-11-21 at 4 34 44 PM" src="https://user-images.githubusercontent.com/29983536/203171996-b7487f02-e4ea-49aa-9fdc-c2e9ebb13911.png">

### Task Checklist 

- [x] https://github.com/webb-tools/webb-dapp/issues/705
- [ ] https://github.com/webb-tools/webb-dapp/issues/717
- [ ] [TASK] Fix notification card for deposits and wrap and deposit 
- [ ] [TASK] Validating deposit inputs (e.g. balance)
- [x] [TASK] Improve leaf fetching and fix caching 
- [x] Implement _Deposit Scene-1 | Data Input_
- [x] Implement _Deposit Scene-2 | Confirmation_
- [x] Implement _Deposit Scene-3 | Deposit In-progress_
- [x] Implement successful Deposit transaction 
- [x] Test deposits for each chain with bridged asset
- [x] Test deposits for each chain with non-bridged asset (e.g. deposit and wrap flow)

**Comment by dutterbutter** [comment]
Closed in #719
