### ISSUE TITLE
[CHECKLIST] Implement successful withdraw flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#712]
## Overview 

The goal of this checklist is to create a comprehensive list of tasks that collectively make up the successful and unsuccessful withdraw flow for dApp users. 

### Withdraw Flow

**Note:** Assumes a user has already connected their wallet, created their note account, and made a deposit.

**Withdraw Scene-1 | Data Input** 
1. Selects token to withdraw from bridge
2. Select amount to be withdrawn 
3. Select relayer from relayer selection modal 
4. Input or paste recipient address 

There are additional flows to be considered for Withdraw. User can select 'Unwrap' using a toggle. The toggle should be disabled if there is no liquidity of the underlying asset to unwrap into, and enabled if there is liquidity to unwrap into. We will need to make a liquidity check during this operation. 

The other flow is the user can also, although not recommended entirely, to enter a variable amount to be withdrawn rather than a fixed amount. 

<img width="377" alt="Screen Shot 2022-11-21 at 4 46 21 PM" src="https://user-images.githubusercontent.com/29983536/203173341-a76920fb-056d-489c-b069-f9bf9ec6a1f8.png">

**Withdraw Scene-2 | Confirmation**
1. User confirms they have copied the new spend note 
2. User selects 'Withdraw' 

There is a case, where users do not have a new spend note generated, as they have withdraw the entire balance (e.g. spent all their notes). We need to account for this case here. 

<img width="377" alt="Screen Shot 2022-11-21 at 4 48 18 PM" src="https://user-images.githubusercontent.com/29983536/203173535-b7c2613c-a126-4165-bc8b-f6b04c1a4bd8.png">

**Withdraw Scene-3 | Withdraw In-progress**
1. Display the progress of the withdraw operations 
2. User can select 'New Transaction' that will move progress view into accordion component to the right side and display withdraw scene-1 

<img width="384" alt="Screen Shot 2022-11-21 at 4 50 06 PM" src="https://user-images.githubusercontent.com/29983536/203173838-7e1f7521-d5eb-467b-a788-9469c9b441e3.png">

**Right-sided component** - It should read Withdraw in the chip component not deposit.
<img width="283" alt="Screen Shot 2022-11-21 at 4 50 28 PM" src="https://user-images.githubusercontent.com/29983536/203173856-6b531a14-8385-4a20-adda-3b16d6498c86.png">

### Task Checklist 

- [x] Implement _Withdraw Scene-1 | Data Input_
- [x] Implement _Withdraw Scene-2 | Confirmation_
- [x] Implement _Withdraw Scene-3 | Withdraw In-progress_
- [x] Implement successful withdraw transaction 
- [x] Test withdrawals for each chain with bridged asset
- [x] Test withdrawals for each chain with non-bridged asset (e.g. withdraw and unwrap flow) 

### [Wireframe File](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=940%3A139772&t=wfB9FgWRDQn8ogP3-0)
