### ISSUE TITLE
[CHECKLIST] Implement successful transfer flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#713]
## Overview 

The goal of this checklist is to create a comprehensive list of tasks that collectively make up the successful and unsuccessful transfer flow for dApp users. 

### Transfer Flow

**Note:** Assumes a user has already connected their wallet, created their note account, and made a deposit.

**Transfer Scene-1 | Data Input** 
1. Selects bridged asset to transfer from bridge
2. Selects destination chain
3. Select amount to be transferred  
4. Select relayer from relayer selection modal 
5. Input or paste recipient address 
6. Selects 'Transfer'

<img width="387" alt="Screen Shot 2022-11-21 at 4 54 35 PM" src="https://user-images.githubusercontent.com/29983536/203174438-4c78236a-8aa1-4254-83c8-dfc74f3bd0aa.png">

**Transfer Scene-2 | Confirmation**
1. User confirms they have copied the new spend note 
2. User selects 'Transfer' 

There is a case, where users do not have a new spend note generated, as they have withdraw the entire balance (e.g. spent all their notes). We need to account for this case here. 

<img width="386" alt="Screen Shot 2022-11-21 at 4 56 19 PM" src="https://user-images.githubusercontent.com/29983536/203174517-86f59318-8eee-4c94-a4ea-a2389325e67e.png">

**Transfer Scene-3 | Transfer In-progress**
1. Display the progress of the transfer operations 
2. User can select 'New Transaction' that will move progress view into accordion component to the right side and display transfer scene-1 

<img width="393" alt="Screen Shot 2022-11-21 at 4 57 08 PM" src="https://user-images.githubusercontent.com/29983536/203174685-83ec2217-9628-43c5-944c-af21ebeb5fa2.png">

**Right-sided component** - It should read Transfer in the chip component not deposit.
<img width="283" alt="Screen Shot 2022-11-21 at 4 50 28 PM" src="https://user-images.githubusercontent.com/29983536/203173856-6b531a14-8385-4a20-adda-3b16d6498c86.png">

### Task Checklist 

- [x] Implement _Transfer Scene-1 | Data Input_
- [x] Implement _Transfer Scene-2 | Confirmation_
- [x] Implement _Transfer Scene-3 | _Transfer In-progress_
- [x] Implement successful Transfer transaction 
- [x] Test transfer for each chain pairing

### [Wireframe File](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=940%3A139772&t=wfB9FgWRDQn8ogP3-0)
