### ISSUE TITLE
[BUG] Stats dApp crashed on 'Authorities' during early sync

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#720]
## Overview

During an initial sync, when selecting the 'Authorities' tab the dApp crashes. We need to handle these cases so dApp is more resilient. It doesn't seem to be a backend issue as the data is present.

### Task Checklist 

- [ ] Investigate Authorities crash and determine root cause
- [ ] Fix dApp crash to read properties correctly during sync states  
- [ ] Test locally with networks on initial sync 

#### Screenshot

![Screen Shot 2022-11-24 at 3 37 09 PM](https://user-images.githubusercontent.com/29983536/203866829-2e0a4a0d-c1f3-4e57-86ed-2701fcd8720b.png)

**Comment by dutterbutter** [comment]
Resolved in #813
