### ISSUE TITLE
Adding tooltips and dropdown for data row on the dapp

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#724]
**Is your UI update related to a problem? Please describe.**
Right now, a user can check his/her shielded assets along with spend notes on the account tables. But on the **_chain column_**, it might have the same icon (e.g. Goerli and Sepolia have the same `ETH` icon) so it might confuse users, this also applied to the composition column.

For the action column, we should have a tooltip for letting users know the functionality of a button, check the screenshots below.

**Describe the solution you'd like (include image or link to prototype)**
We should have the tooltips and dropdown menu to provide more information for the users. Check the screenshots below.

### Task Checklist

- [ ] Adding _tooltips_ for the **chain column** on the **shielded assets** table
- [ ] Adding _tooltips_ for the **chain column** on the **spend note** table
- [ ] Adding _tooltips_ for the **composition column** on the **shielded asset** table
- [ ] Adding _tooltips_ for the **composition column** on the **spend note** table
- [ ] Adding _tooltips_ for the **action column** on the **shielded asset** table
- [ ] Adding _dropdown menu_ for the **action column** on the **spend note** table

### Screen recording

https://user-images.githubusercontent.com/60747384/204494049-4776675c-d2cf-4e91-b7b8-f317593323b4.mp4
