### ISSUE TITLE
[FEAT] Filter feature for the note account table

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#725]
**Is your feature request related to a problem? Please describe.**
We need a filter button for filtering out data on the note account table.

**Describe the solution you'd like**
Check the filter feature implementation on the `stats-dapp` for reference.

### Task Checklist

- [x] Adding filter button on the header of note account tables
- [x] Adding the filter functionality for the shielded asset table
- [x] Adding the filter functionality for the spend note table
- [x] Make sure the filter functionality will behave correctly corresponding to the selected table.

### Relevant links

- [Figma deisgn](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1866%3A17295&viewport=-1072%2C636%2C0.59&t=7mJUk76d72AYrjNM-11)
- [Authorities Filter on the Stats Dapp](https://github.com/webb-tools/webb-dapp/blob/a235af49f4080373eeda8491616eae94c01d4ced/apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx#L219-L272)

### Screenshots

![CleanShot 2022-11-29 at 16 44 53@2x](https://user-images.githubusercontent.com/60747384/204496280-ea19e2d1-9b4b-434a-8229-5e1a1b47b6c0.png)

![CleanShot 2022-11-29 at 16 46 18@2x](https://user-images.githubusercontent.com/60747384/204496290-3f22b1b6-2b6b-4b47-be30-1b015c9efe44.png)
