### ISSUE TITLE
[CHECKLIST] Webb Marketing Site Landing Page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#766]
## Overview 

The purpose of this checklist is to outline the requirements to implement Webb's new marketing landing page. The below tasks are broken down and should be worked on in small chunks followed by a review from the design team. The expected deliverable includes both **desktop** and **mobile** implementations. All design elements are linked below and categorized by section.

Any design questions please reach out to @seeddisperser, for implementation questions ping @dutterbutter. 

### Section Breakdown

The landing page can be broken down into 7 sections are described below:
- Hero section
- Future of privacy is connected
- Future of privacy scales
- Applications and infrastructure 
- Shielded protocols in Action
- Research & development
- Community call to action (CTA)

Within the above sections there are 3 places of animation, of which we intend to export each frame as a `svg` for animation. @seeddisperser suggests that all of the animation can be accomplished with `SVGs` and a simple `@keyframes`  method. A more powerful framework like [Lottie](https://lottiereact.com/) could also be used if it becomes cumbersome to manage. List of section animations required:
- Hero page animation frames
- Future of privacy is connected (graphic illustration)
- Future of privacy scales (graphic illustration)

#### Type Sytem

- [Figma Type System](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1033%3A42676&t=rU8cWE1yl6HRTLzR-1)

### Task Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/758
- [x] https://github.com/webb-tools/webb-dapp/issues/759
- [x] https://github.com/webb-tools/webb-dapp/issues/760
- [x] https://github.com/webb-tools/webb-dapp/issues/761
- [x] https://github.com/webb-tools/webb-dapp/issues/762
- [x] https://github.com/webb-tools/webb-dapp/issues/763
- [x] https://github.com/webb-tools/webb-dapp/issues/764
- [x] https://github.com/webb-tools/webb-dapp/issues/765
- [x] https://github.com/webb-tools/webb-dapp/issues/809
- [x] https://github.com/webb-tools/webb-dapp/issues/810
- [x] https://github.com/webb-tools/webb-dapp/issues/811
- [x] https://github.com/webb-tools/webb-dapp/issues/816
- [x] [TASK] Animated background for hero section on the marketing page

### Video Walkthrough 

https://user-images.githubusercontent.com/29983536/205180578-4dd1e92a-e146-41ce-8fab-c04535c0539d.mov

**Comment by dutterbutter** [comment]
closed in #849
