### ISSUE TITLE
[TASK] Add sendinblue integration for marketing newsletter 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#816]
## Overview 

As part of https://github.com/webb-tools/webb-dapp/issues/765 there is a CTA for email addresses to be added to our mailing lists. We have decided to make use of [SendinBlue](https://www.sendinblue.com/) for email marketing. 

### Task Checklist

- [ ] Integrate SendinBlue API into marketing site to add user email addresses to mailing list
- [ ] We should just need to send a request to API with user email address using our API key
- [ ] Test sendinBlue integration to ensure email address is added to contacts list 

### Relevant docs 

- [SendinBlue requests](https://developers.sendinblue.com/docs/how-it-works#requests)

@dutterbutter will provide API key when issue is being worked on.
