### ISSUE TITLE
[CHECKLIST] Implement remaining marketing site pages

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#847]
## Overview 

With the landing page completed, we now need to implement the remaining pages to conclude v2 of Webbs marketing site. Any design questions please reach out to @seeddisperser, for implementation questions ping @dutterbutter. 

### Pages

Pages to be implemented:

- [ ] Shielded Pool Protocols
- [x] Community
- [x] Blog Landing
- [x] Blog Post
- [x] 404

### [Animated components](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?t=o3TRtvh0HChB3uSG-0)
- Note the [onscroll navbar animation](https://www.figma.com/proto/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?page-id=1028%3A32474&node-id=1422%3A49573&viewport=43%2C695%2C0.06&scaling=scale-down&starting-point-node-id=1422%3A49099&show-proto-sidebar=1)

### [Mobile Figma Files](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1033%3A40962&t=R6sBIgXaP3W5n7vW-1)

**Comment by dutterbutter** [comment]
Starting this order: @devpavan04  

- [ ] Community
- [ ] Add Docs link
- [ ] 404
- [ ] Blog
- [ ] Protocol pages (wait for approval here)

**Comment by dutterbutter** [comment]
Related: https://github.com/webb-tools/webb-dapp/pull/1016, https://github.com/webb-tools/webb-dapp/pull/996, and https://github.com/webb-tools/webb-dapp/pull/991

**Comment by vutuanlinh2k2** [comment]
Hi @monaiuu. I find that the design for mobile and desktop for the Shielded Pool Protocols page is not consistent at the moment, can you address on that? In **Use cases** and **Extensions** sections, there are some texts on mobile but not on desktop. 

**Mobile (with texts):** 
<img width="244" alt="Screenshot 2023-06-07 at 15 50 23" src="https://github.com/webb-tools/webb-dapp/assets/69841784/4554852c-efeb-48a2-85f7-08500859b3e9">
<img width="241" alt="Screenshot 2023-06-07 at 15 50 36" src="https://github.com/webb-tools/webb-dapp/assets/69841784/253f434f-c21d-4e41-afb0-37d8834b9a18">

**Desktop (no texts):**
<img width="624" alt="Screenshot 2023-06-07 at 15 51 24" src="https://github.com/webb-tools/webb-dapp/assets/69841784/e7561444-e2fc-4482-9d67-c2bf06afb46e">
<img width="560" alt="Screenshot 2023-06-07 at 15 51 35" src="https://github.com/webb-tools/webb-dapp/assets/69841784/db080f5b-c1ee-44a6-83b5-15e0b3edf481">

**Comment by vutuanlinh2k2** [comment]
@monaiuu can you provide me images for the **Multi-Asset Vanchor** and **Chainalysis Sanctioned Vanchor** in the **Extensions** section as well? Thank you so much 😊
