### ISSUE TITLE
[CHECKLIST] QA Reported BUGS and Design Discrepancies 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#876]
## Overview
The below checklist outlines the various BUGS and design discrepancies discovered during early QA process. These issues will need to be resolved prior to our Alpha launch of the Hubble bridge. To follow the QA test case progress view the Notion document [here](https://www.notion.so/hicommonwealth/QA-Bridge-dApp-bb1d9d674cac46a895e42bfba970f251).

### Quick to address

- [x] https://github.com/webb-tools/webb-dapp/issues/903
- [x] https://github.com/webb-tools/webb-dapp/issues/834
- [x] https://github.com/webb-tools/webb-dapp/issues/868
- [x] https://github.com/webb-tools/webb-dapp/issues/899
- [x] https://github.com/webb-tools/webb-dapp/issues/874
- [x] https://github.com/webb-tools/webb-dapp/issues/697
- [x] https://github.com/webb-tools/webb-dapp/issues/875
- [x] https://github.com/webb-tools/webb-dapp/issues/860
- [x] https://github.com/webb-tools/webb-dapp/issues/845
- [x] https://github.com/webb-tools/webb-dapp/issues/843
- [x] https://github.com/webb-tools/webb-dapp/issues/839
- [x] https://github.com/webb-tools/webb-dapp/issues/841
- [x] https://github.com/webb-tools/webb-dapp/issues/836
- [x] https://github.com/webb-tools/webb-dapp/issues/882
- [x] https://github.com/webb-tools/webb-dapp/issues/889
- [x] https://github.com/webb-tools/webb-dapp/issues/892
- [x] https://github.com/webb-tools/webb-dapp/issues/900

### Functional

- [x] https://github.com/webb-tools/webb-dapp/issues/920
- [x] https://github.com/webb-tools/webb-dapp/issues/919
- [x] https://github.com/webb-tools/webb-dapp/issues/873
- [x] https://github.com/webb-tools/webb-dapp/issues/872
- [x] https://github.com/webb-tools/webb-dapp/issues/871
- [x] https://github.com/webb-tools/webb-dapp/issues/869
- [x] https://github.com/webb-tools/webb-dapp/issues/867
- [x] https://github.com/webb-tools/webb-dapp/issues/861
- [x] https://github.com/webb-tools/webb-dapp/issues/859
- [ ] https://github.com/webb-tools/webb-dapp/issues/857
- [x] https://github.com/webb-tools/webb-dapp/issues/856
- [x] https://github.com/webb-tools/webb-dapp/issues/855
- [x] https://github.com/webb-tools/webb-dapp/issues/853
- [x] https://github.com/webb-tools/webb-dapp/issues/840
- [x] https://github.com/webb-tools/webb-dapp/issues/821
- [x] https://github.com/webb-tools/webb-dapp/issues/882
- [x] https://github.com/webb-tools/webb-dapp/issues/884
- [x] https://github.com/webb-tools/webb-dapp/issues/906

### Design 

- [x] https://github.com/webb-tools/webb-dapp/issues/904
- [x] https://github.com/webb-tools/webb-dapp/issues/890
- [x] https://github.com/webb-tools/webb-dapp/issues/870
- [x] https://github.com/webb-tools/webb-dapp/issues/902
- [x] https://github.com/webb-tools/webb-dapp/issues/863
- [x] https://github.com/webb-tools/webb-dapp/issues/858
- [x] https://github.com/webb-tools/webb-dapp/issues/851
- [x] https://github.com/webb-tools/webb-dapp/issues/838
- [x] https://github.com/webb-tools/webb-dapp/issues/883
- [x] https://github.com/webb-tools/webb-dapp/issues/887
- [x] https://github.com/webb-tools/webb-dapp/issues/949

**Comment by dutterbutter** [comment]
Closing in favour of #948
