### ISSUE TITLE
[TASK] Fix Typescript errors and add tsc check to CI

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#909]
## Overview

We need to go through and address all the Typescript errors within the `apps/` and `libs/` directories. Running a `tsc` check results in an abundance of errors. By resolving these issues it will improve the code and prevent dapp crashes. 

### Task Checklist

- [ ] Update and remove unneeded lines from `tsconfig.base.json` file
- [ ] Run `tsc` check using `tsconfig.base.json` against all `*.{js,jsx,ts,tsx}` files 
- [ ] Address each typescript error 
- [ ] Add `tsc` check to `check.yml` GH workflow to prevent future type misuse

**Comment by AhmedKorim** [comment]
@dutterbutter can you elaborate more on how did you run the `tsc`, `nx run-many --target=lint --all --verbose` returns warning no errors

**Comment by dutterbutter** [comment]
Sure! 

Running `nx run-many --target=lint --all --verbose` is for **linting** specifically and not a typescript checker. This task requires a few steps:

- [ ] Update the `tsconfig.base.json` to so that `tsc` can find all relevant files to check against (for example, changing the `include` field to `"include": [ "**/*"],` ) 
- [ ] Run `npx tsc --noEmit -p ./tsconfig.base.json` 
- [ ] Address all errors / warnings 
- [ ] Update the CI to include a `tsc` check in the `check.yml` workflow file 

We want to ensure that `tsc` is checking against ALL `{js,jsx,ts,tsx}` files in both `apps/` and `libs/` directories.
