### ISSUE TITLE
[TASK] Update and remove outdated / vulnerable dependencies 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#922]
## Overview

Being a monorepo we have to be pay close attention to our dependencies. Doing a quick review of the current state of dependencies the following table outlines all the outdated dependencies. Of those outdated dependencies, we have 54 that are considered **High** or **Critical**.

```
Severity: 11 Low | 36 Moderate | 41 High | 13 Critical
```

Relevant commands:
**Display deps vulnerabilities**
`yarn audit`

**Upgrade deps interactively**
`yarn upgrade-interactive --latest`

### Task Checklist

- [x] Address high and critical dependencies 
- [x] Update outdated deps
- [x] Remove unused deps 
- [x] Update dependabot to be more expressive and addressing incremental version bumps

| Package                                           | Current   | Wanted    | Latest   | Workspace                            | Package Type           | URL                                                                                   |
| ------------------------------------------------- | --------- | --------- | -------- | ------------------------------------ | ---------------------- | ------------------------------------------------------------------------------------- |
| @apollo/client                                    | 3.7.4     | 3.7.5     | 3.7.5    | webb-monorepo                        | dependencies           | https://www.apollographql.com/docs/react/                                             |
| @babel/core                                       | 7.18.6    | 7.18.6    | 7.20.12  | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-core                                             |
| @babel/plugin-proposal-private-property-in-object | 7.16.7    | 7.16.7    | 7.20.5   | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-plugin-proposal-private-property-in-object       |
| @babel/plugin-transform-react-jsx                 | 7.17.3    | 7.17.3    | 7.20.13  | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-plugin-transform-react-jsx                       |
| @babel/plugin-transform-runtime                   | 7.17.0    | 7.17.0    | 7.19.6   | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-plugin-transform-runtime                         |
| @babel/preset-env                                 | 7.18.6    | 7.18.6    | 7.20.2   | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-preset-env                                       |
| @babel/runtime                                    | 7.18.6    | 7.18.6    | 7.20.13  | webb-monorepo                        | devDependencies        | https://babel.dev/docs/en/next/babel-runtime                                          |
| @graphql-codegen/cli                              | 2.12.0    | 2.12.0    | 2.16.4   | webb-monorepo                        | devDependencies        | https://github.com/dotansimha/graphql-code-generator#readme                           |
| @graphql-codegen/introspection                    | 2.2.1     | 2.2.1     | 2.2.3    | webb-monorepo                        | devDependencies        | https://github.com/dotansimha/graphql-code-generator#readme                           |
| @graphql-codegen/typescript                       | 2.7.3     | 2.7.3     | 2.8.7    | webb-monorepo                        | devDependencies        | https://github.com/dotansimha/graphql-code-generator#readme                           |
| @graphql-codegen/typescript-operations            | 2.5.3     | 2.5.3     | 2.5.12   | webb-monorepo                        | devDependencies        | https://github.com/dotansimha/graphql-code-generator#readme                           |
| @graphql-codegen/typescript-react-apollo          | 3.3.3     | 3.3.3     | 3.3.7    | webb-monorepo                        | devDependencies        | https://github.com/dotansimha/graphql-code-generator-community#readme                 |
| @influxdata/influxdb-client                       | 1.33.0    | 1.33.1    | 1.33.1   | @webb-tools/react-hooks              | dependencies           | https://github.com/influxdata/influxdb-client-js                                      |
| @influxdata/influxdb-client-browser               | 1.33.0    | 1.33.1    | 1.33.1   | @webb-tools/api-provider-environment | dependencies           | https://github.com/influxdata/influxdb-client-js                                      |
| @influxdata/influxdb-client-browser               | 1.33.0    | 1.33.1    | 1.33.1   | @webb-tools/react-environment        | dependencies           | https://github.com/influxdata/influxdb-client-js                                      |
| @johanaarstein/dotlottie-player                   | 1.2.37    | 1.2.38    | 1.2.38   | webb-monorepo                        | dependencies           | https://www.aarstein.media/en/dev/dotlottie-player                                    |
| @mui/material                                     | 5.11.5    | 5.11.6    | 5.11.6   | webb-monorepo                        | dependencies           | https://mui.com/material-ui/getting-started/overview/                                 |
| @mui/styled-engine                                | 5.10.8    | 5.10.8    | 5.11.0   | webb-monorepo                        | dependencies           | https://mui.com/material-ui/guides/styled-engine/                                     |
| @netlify/plugin-nextjs                            | 4.30.0    | 4.30.2    | 4.30.2   | webb-monorepo                        | devDependencies        | https://github.com/netlify/next-runtime#readme                                        |
| @ngneat/falso                                     | 5.7.0     | 5.7.0     | 6.4.0    | @webb-tools/bridge-dapp              | dependencies           | https://github.com/ngneat/falso#readme                                                |
| @ngneat/falso                                     | 5.7.0     | 5.7.0     | 6.4.0    | @webb-tools/stats-dapp               | dependencies           | https://github.com/ngneat/falso#readme                                                |
| @nrwl/cli                                         | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/cypress                                     | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/eslint-plugin-nx                            | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/jest                                        | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/linter                                      | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/next                                        | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/react                                       | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/storybook                                   | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/web                                         | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/webpack                                     | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @nrwl/workspace                                   | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| @polkadot/api                                     | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/api#readme                    |
| @polkadot/api                                     | 9.11.3    | 9.2.4     | 9.12.1   | webb-monorepo                        | dependencies           | https://github.com/polkadot-js/api/tree/master/packages/api#readme                    |
| @polkadot/api                                     | 9.11.3    | 9.2.4     | 9.12.1   | @webb-tools/api-provider-environment | dependencies           | https://github.com/polkadot-js/api/tree/master/packages/api#readme                    |
| @polkadot/api                                     | 9.11.3    | 9.2.4     | 9.12.1   | @webb-tools/react-environment        | dependencies           | https://github.com/polkadot-js/api/tree/master/packages/api#readme                    |
| @polkadot/api                                     | 9.11.3    | 9.2.4     | 9.12.1   | @webb-tools/react-hooks              | dependencies           | https://github.com/polkadot-js/api/tree/master/packages/api#readme                    |
| @polkadot/api-augment                             | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/api-augment#readme            |
| @polkadot/api-base                                | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/api-base#readme               |
| @polkadot/api-contract                            | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/api-contract#readme           |
| @polkadot/api-derive                              | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/api-derive#readme             |
| @polkadot/dev                                     | 0.67.86   | 0.67.86   | 0.67.187 | webb-monorepo                        | devDependencies        | https://github.com/polkadot-js/dev/tree/master/packages/dev#readme                    |
| @polkadot/extension-dapp                          | 0.44.1    | 0.44.1    | 0.44.8   | webb-monorepo                        | dependencies           | https://github.com/polkadot-js/extension/tree/master/packages/extension-dapp#readme   |
| @polkadot/extension-dapp                          | 0.44.1    | 0.44.1    | 0.44.8   | @webb-tools/api-provider-environment | dependencies           | https://github.com/polkadot-js/extension/tree/master/packages/extension-dapp#readme   |
| @polkadot/extension-dapp                          | 0.44.1    | 0.44.1    | 0.44.8   | @webb-tools/react-environment        | dependencies           | https://github.com/polkadot-js/extension/tree/master/packages/extension-dapp#readme   |
| @polkadot/extension-dapp                          | 0.43.1    | 0.43.1    | 0.44.8   | @webb-tools/react-hooks              | dependencies           | https://github.com/polkadot-js/extension/tree/master/packages/extension-dapp#readme   |
| @polkadot/extension-inject                        | 0.44.1    | 0.44.1    | 0.44.8   | webb-monorepo                        | dependencies           | https://github.com/polkadot-js/extension/tree/master/packages/extension-inject#readme |
| @polkadot/rpc-augment                             | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/rpc-augment#readme            |
| @polkadot/rpc-core                                | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/rpc-core#readme               |
| @polkadot/rpc-provider                            | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/rpc-provider#readme           |
| @polkadot/types                                   | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types#readme                  |
| @polkadot/types                                   | 9.11.3    | 9.2.4     | 9.12.1   | webb-monorepo                        | dependencies           | https://github.com/polkadot-js/api/tree/master/packages/types#readme                  |
| @polkadot/types-augment                           | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types-augment#readme          |
| @polkadot/types-codec                             | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types-codec#readme            |
| @polkadot/types-create                            | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types-create#readme           |
| @polkadot/types-known                             | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types-known#readme            |
| @polkadot/types-support                           | 9.11.3    | 9.12.1    | 9.12.1   |                                      | resolutionDependencies | https://github.com/polkadot-js/api/tree/master/packages/types-support#readme          |
| @radix-ui/react-dropdown-menu                     | 1.0.0     | 1.0.0     | 2.0.2    | webb-monorepo                        | devDependencies        | https://radix-ui.com/primitives                                                       |
| @radix-ui/react-dropdown-menu                     | 1.0.0     | 1.0.0     | 2.0.2    | @webb-tools/webb-ui-components       | dependencies           | https://radix-ui.com/primitives                                                       |
| @radix-ui/react-label                             | 1.0.0     | 1.0.0     | 2.0.0    | webb-monorepo                        | devDependencies        | https://radix-ui.com/primitives                                                       |
| @radix-ui/react-label                             | 1.0.0     | 1.0.0     | 2.0.0    | @webb-tools/webb-ui-components       | dependencies           | https://radix-ui.com/primitives                                                       |
| @rollup/plugin-commonjs                           | 23.0.7    | 23.0.7    | 24.0.1   | webb-monorepo                        | dependencies           | https://github.com/rollup/plugins/tree/master/packages/commonjs/#readme               |
| @rollup/plugin-image                              | 3.0.1     | 3.0.1     | 3.0.2    | webb-monorepo                        | dependencies           | https://github.com/rollup/plugins/tree/master/packages/image/#readme                  |
| @rollup/plugin-json                               | 5.0.2     | 5.0.2     | 6.0.0    | @webb-tools/webb-ui-components       | devDependencies        | https://github.com/rollup/plugins/tree/master/packages/json#readme                    |
| @rollup/plugin-typescript                         | 9.0.2     | 9.0.2     | 11.0.0   | webb-monorepo                        | dependencies           | https://github.com/rollup/plugins/tree/master/packages/typescript/#readme             |
| @storybook/addon-a11y                             | 6.5.15    | 6.5.16    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/addons/a11y                        |
| @storybook/addon-actions                          | 6.5.15    | 6.5.16    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/addons/actions                     |
| @storybook/addon-actions                          | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/addons/actions                     |
| @storybook/addon-essentials                       | 6.5.15    | 6.5.15    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/addons/essentials                  |
| @storybook/addon-essentials                       | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/addons/essentials                  |
| @storybook/addon-interactions                     | 6.5.15    | 6.5.16    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/addons/interactions                |
| @storybook/addon-interactions                     | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/addons/interactions                |
| @storybook/addon-links                            | 6.5.15    | 6.5.16    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/addons/links                       |
| @storybook/addon-links                            | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/addons/links                       |
| @storybook/builder-webpack5                       | 6.5.15    | 6.5.15    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/lib/core                           |
| @storybook/builder-webpack5                       | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/lib/core                           |
| @storybook/core-server                            | 6.5.15    | 6.5.15    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/lib/core                           |
| @storybook/manager-webpack5                       | 6.5.15    | 6.5.15    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/lib/core                           |
| @storybook/manager-webpack5                       | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/lib/core                           |
| @storybook/react                                  | 6.5.15    | 6.5.15    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/app/react                          |
| @storybook/react                                  | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/app/react                          |
| @storybook/theming                                | 6.5.15    | 6.5.16    | 6.5.16   | webb-monorepo                        | devDependencies        | https://github.com/storybookjs/storybook/tree/main/lib/theming                        |
| @storybook/theming                                | 6.5.15    | 6.5.16    | 6.5.16   | @webb-tools/webb-ui-components       | dependencies           | https://github.com/storybookjs/storybook/tree/main/lib/theming                        |
| @svgr/rollup                                      | 6.5.0     | 6.5.0     | 6.5.1    | webb-monorepo                        | devDependencies        | https://react-svgr.com                                                                |
| @svgr/webpack                                     | 5.5.0     | 5.5.0     | 6.5.1    | webb-monorepo                        | devDependencies        | https://react-svgr.com                                                                |
| @svgr/webpack                                     | 5.5.0     | 5.5.0     | 6.5.1    | @webb-tools/bridge-dapp              | devDependencies        | https://react-svgr.com                                                                |
| @svgr/webpack                                     | 5.5.0     | 5.5.0     | 6.5.1    | @webb-tools/stats-dapp               | devDependencies        | https://react-svgr.com                                                                |
| @svgr/webpack                                     | 5.5.0     | 5.5.0     | 6.5.1    | @webb-tools/webb-ui-components       | dependencies           | https://react-svgr.com                                                                |
| @tanstack/react-table                             | 8.7.6     | 8.7.8     | 8.7.8    | webb-monorepo                        | devDependencies        | https://github.com/tanstack/table#readme                                              |
| @tanstack/react-table                             | 8.7.6     | 8.7.8     | 8.7.8    | @webb-tools/bridge-dapp              | dependencies           | https://github.com/tanstack/table#readme                                              |
| @tanstack/react-table                             | 8.7.6     | 8.7.8     | 8.7.8    | @webb-tools/stats-dapp               | dependencies           | https://github.com/tanstack/table#readme                                              |
| @tanstack/react-table                             | 8.7.6     | 8.7.8     | 8.7.8    | @webb-tools/webb-ui-components       | dependencies           | https://github.com/tanstack/table#readme                                              |
| @types/jest                                       | 28.1.1    | 28.1.1    | 29.4.0   | webb-monorepo                        | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest             |
| @types/node                                       | 16.11.7   | 16.11.7   | 18.11.18 | webb-monorepo                        | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node             |
| @types/node                                       | 17.0.45   | 17.0.45   | 18.11.18 | @webb-tools/bridge-dapp              | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node             |
| @types/node                                       | 17.0.45   | 17.0.45   | 18.11.18 | @webb-tools/stats-dapp               | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node             |
| @types/react                                      | 18.0.25   | 18.0.25   | 18.0.27  | webb-monorepo                        | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react            |
| @types/react-dom                                  | 18.0.9    | 18.0.9    | 18.0.10  | webb-monorepo                        | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom        |
| @types/tailwindcss                                | 3.0.10    | 3.0.10    | 3.1.0    | webb-monorepo                        | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tailwindcss      |
| @types/tailwindcss                                | 3.0.10    | 3.0.10    | 3.1.0    | @webb-tools/bridge-dapp              | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tailwindcss      |
| @types/tailwindcss                                | 3.0.10    | 3.0.10    | 3.1.0    | @webb-tools/stats-dapp               | devDependencies        | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tailwindcss      |
| @typescript-eslint/eslint-plugin                  | 5.48.2    | 5.49.0    | 5.49.0   | webb-monorepo                        | devDependencies        | https://github.com/typescript-eslint/typescript-eslint#readme                         |
| @typescript-eslint/parser                         | 5.48.2    | 5.49.0    | 5.49.0   | webb-monorepo                        | devDependencies        | https://github.com/typescript-eslint/typescript-eslint#readme                         |
| @webb-tools/anchors                               | 0.5.10    | 0.5.10    | 0.5.11   | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/protocol-solidity#readme                                |
| @webb-tools/api                                   | 0.1.4-119 | 0.1.4-119 | 0.1.8    | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/webb.js                                                 |
| @webb-tools/api-derive                            | 0.1.4-119 | 0.1.4-119 | 0.1.8    | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/webb.js                                                 |
| @webb-tools/app-util                              | 0.1.4-119 | 0.1.4-119 | 0.1.8    | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/webb.js#readme                                          |
| @webb-tools/contracts                             | 0.5.8     | 0.5.8     | 0.5.11   | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/protocol-solidity#readme                                |
| @webb-tools/interfaces                            | 0.5.8     | 0.5.8     | 0.5.11   | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/protocol-solidity#readme                                |
| @webb-tools/sdk-core                              | 0.1.4-119 | 0.1.4-119 | 0.1.8    | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/webb.js                                                 |
| @webb-tools/tokens                                | 0.5.10    | 0.5.10    | 0.5.11   | webb-monorepo                        | devDependencies        | https://github.com/webb-tools/protocol-solidity#readme                                |
| @webb-tools/wasm-utils                            | 0.1.4-119 | 0.1.4-119 | 0.1.8    | webb-monorepo                        | devDependencies        |                                                                                       |
| axios                                             | 0.21.4    | 0.21.4    | 1.2.5    | @webb-tools/react-hooks              | dependencies           | https://axios-http.com                                                                |
| babel-jest                                        | 28.1.1    | 28.1.1    | 29.4.1   | webb-monorepo                        | devDependencies        | https://github.com/facebook/jest#readme                                               |
| babel-loader                                      | 8.1.0     | 8.1.0     | 9.1.2    | webb-monorepo                        | devDependencies        | https://github.com/babel/babel-loader                                                 |
| babel-loader                                      | 8.3.0     | 8.3.0     | 9.1.2    | @webb-tools/bridge-dapp              | devDependencies        | https://github.com/babel/babel-loader                                                 |
| babel-loader                                      | 8.3.0     | 8.3.0     | 9.1.2    | @webb-tools/stats-dapp               | devDependencies        | https://github.com/babel/babel-loader                                                 |
| chai                                              | 4.3.6     | 4.3.6     | 4.3.7    | webb-monorepo                        | dependencies           | http://chaijs.com                                                                     |
| chart.js                                          | 3.9.1     | 3.9.1     | 4.2.0    | webb-monorepo                        | dependencies           | https://www.chartjs.org                                                               |
| chart.js                                          | 3.9.1     | 3.9.1     | 4.2.0    | @webb-tools/bridge-dapp              | dependencies           | https://www.chartjs.org                                                               |
| chart.js                                          | 3.9.1     | 3.9.1     | 4.2.0    | @webb-tools/stats-dapp               | dependencies           | https://www.chartjs.org                                                               |
| chromatic                                         | 6.14.0    | 6.15.0    | 6.15.0   | webb-monorepo                        | dependencies           | https://www.chromatic.com                                                             |
| circomlibjs                                       | 0.0.8     | 0.0.8     | 0.1.7    | webb-monorepo                        | dependencies           | https://github.com/iden3/circomlibjs#readme                                           |
| copy-webpack-plugin                               | 10.2.4    | 10.2.4    | 11.0.0   | webb-monorepo                        | devDependencies        | https://github.com/webpack-contrib/copy-webpack-plugin                                |
| core-js                                           | 3.27.1    | 3.27.2    | 3.27.2   | webb-monorepo                        | dependencies           | https://github.com/zloirock/core-js#readme                                            |
| css-loader                                        | 6.7.1     | 6.7.1     | 6.7.3    | webb-monorepo                        | devDependencies        | https://github.com/webpack-contrib/css-loader                                         |
| csv                                               | 5.5.3     | 5.5.3     | 6.2.5    | @webb-tools/react-hooks              | dependencies           | https://csv.js.org/                                                                   |
| cypress                                           | 11.2.0    | 11.2.0    | 12.4.0   | webb-monorepo                        | devDependencies        | https://github.com/cypress-io/cypress                                                 |
| dotenv                                            | 16.0.2    | 16.0.2    | 16.0.3   | webb-monorepo                        | devDependencies        | https://github.com/motdotla/dotenv#readme                                             |
| eslint                                            | 8.15.0    | 8.15.0    | 8.32.0   | webb-monorepo                        | devDependencies        | https://eslint.org                                                                    |
| eslint-config-next                                | 13.1.1    | 13.1.1    | 13.1.5   | webb-monorepo                        | devDependencies        | https://github.com/vercel/next.js#readme                                              |
| eslint-config-prettier                            | 8.1.0     | 8.1.0     | 8.6.0    | webb-monorepo                        | devDependencies        | https://github.com/prettier/eslint-config-prettier#readme                             |
| eslint-plugin-import                              | 2.26.0    | 2.26.0    | 2.27.5   | webb-monorepo                        | devDependencies        | https://github.com/import-js/eslint-plugin-import                                     |
| eslint-plugin-jsx-a11y                            | 6.6.1     | 6.6.1     | 6.7.1    | webb-monorepo                        | devDependencies        | https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#readme                           |
| eslint-plugin-react                               | 7.31.11   | 7.31.11   | 7.32.1   | webb-monorepo                        | devDependencies        | https://github.com/jsx-eslint/eslint-plugin-react                                     |
| ffjavascript                                      | 0.2.55    | 0.2.55    | 0.2.57   | webb-monorepo                        | dependencies           | https://github.com/iden3/ffjs#readme                                                  |
| framer-motion                                     | 6.5.1     | 6.5.1     | 8.5.3    | webb-monorepo                        | devDependencies        | https://github.com/framer/motion#readme                                               |
| framer-motion                                     | 6.5.1     | 6.5.1     | 8.5.3    | @webb-tools/api-provider-environment | dependencies           | https://github.com/framer/motion#readme                                               |
| framer-motion                                     | 6.5.1     | 6.5.1     | 8.5.3    | @webb-tools/react-environment        | dependencies           | https://github.com/framer/motion#readme                                               |
| gh-pages                                          | 3.2.3     | 3.2.3     | 5.0.0    | webb-monorepo                        | dependencies           | https://github.com/tschaub/gh-pages                                                   |
| gridjs                                            | 5.1.0     | 5.1.0     | 6.0.5    | webb-monorepo                        | dependencies           | https://gridjs.io                                                                     |
| gridjs                                            | 5.1.0     | 5.1.0     | 6.0.5    | @webb-tools/bridge-dapp              | dependencies           | https://gridjs.io                                                                     |
| gridjs                                            | 5.1.0     | 5.1.0     | 6.0.5    | @webb-tools/stats-dapp               | dependencies           | https://gridjs.io                                                                     |
| gridjs-react                                      | 5.1.1     | 5.1.1     | 6.0.1    | webb-monorepo                        | dependencies           | https://gridjs.io                                                                     |
| gridjs-react                                      | 5.1.1     | 5.1.1     | 6.0.1    | @webb-tools/bridge-dapp              | dependencies           | https://gridjs.io                                                                     |
| gridjs-react                                      | 5.1.1     | 5.1.1     | 6.0.1    | @webb-tools/stats-dapp               | dependencies           | https://gridjs.io                                                                     |
| html-loader                                       | 3.1.2     | 3.1.2     | 4.2.0    | webb-monorepo                        | devDependencies        | https://github.com/webpack-contrib/html-loader                                        |
| html-loader                                       | 3.1.2     | 3.1.2     | 4.2.0    | @webb-tools/bridge-dapp              | devDependencies        | https://github.com/webpack-contrib/html-loader                                        |
| html-loader                                       | 3.1.2     | 3.1.2     | 4.2.0    | @webb-tools/stats-dapp               | devDependencies        | https://github.com/webpack-contrib/html-loader                                        |
| ip-regex                                          | 2.1.0     | 2.1.0     | 5.0.0    | webb-monorepo                        | dependencies           | https://github.com/sindresorhus/ip-regex#readme                                       |
| jest                                              | 28.1.1    | 28.1.1    | 29.4.1   | webb-monorepo                        | devDependencies        | https://jestjs.io/                                                                    |
| jest-environment-jsdom                            | 28.1.1    | 28.1.1    | 29.4.1   | webb-monorepo                        | devDependencies        | https://github.com/facebook/jest#readme                                               |
| next                                              | 13.0.0    | 13.0.0    | 13.1.5   | webb-monorepo                        | dependencies           | https://nextjs.org                                                                    |
| nx                                                | 15.4.5    | 15.4.5    | 15.6.2   | webb-monorepo                        | devDependencies        | https://nx.dev                                                                        |
| postcss                                           | 8.4.19    | 8.4.19    | 8.4.21   | webb-monorepo                        | devDependencies        | https://postcss.org/                                                                  |
| react-chartjs-2                                   | 4.3.1     | 4.3.1     | 5.2.0    | webb-monorepo                        | dependencies           | https://github.com/reactchartjs/react-chartjs-2                                       |
| react-chartjs-2                                   | 4.3.1     | 4.3.1     | 5.2.0    | @webb-tools/bridge-dapp              | dependencies           | https://github.com/reactchartjs/react-chartjs-2                                       |
| react-chartjs-2                                   | 4.3.1     | 4.3.1     | 5.2.0    | @webb-tools/stats-dapp               | dependencies           | https://github.com/reactchartjs/react-chartjs-2                                       |
| react-router                                      | 6.4.2     | 6.4.2     | 6.8.0    | webb-monorepo                        | dependencies           | https://github.com/remix-run/react-router#readme                                      |
| react-router-dom                                  | 6.4.1     | 6.4.1     | 6.8.0    | webb-monorepo                        | dependencies           | https://github.com/remix-run/react-router#readme                                      |
| regenerator-runtime                               | 0.13.7    | 0.13.7    | 0.13.11  | webb-monorepo                        | dependencies           | https://github.com/facebook/regenerator/tree/master#readme                            |
| rollup                                            | 3.10.0    | 3.11.0    | 3.11.0   | webb-monorepo                        | dependencies           | https://rollupjs.org/                                                                 |
| rxjs                                              | 7.5.2     | 7.5.2     | 7.8.0    | webb-monorepo                        | dependencies           | https://rxjs.dev                                                                      |
| snarkjs                                           | 0.4.22    | 0.4.22    | 0.5.0    | webb-monorepo                        | dependencies           | https://github.com/iden3/snarkjs#readme                                               |
| ts-jest                                           | 28.0.5    | 28.0.5    | 29.0.5   | webb-monorepo                        | devDependencies        | https://kulshekhar.github.io/ts-jest                                                  |
| tslib                                             | 2.4.1     | 2.5.0     | 2.5.0    | webb-monorepo                        | dependencies           | https://www.typescriptlang.org/                                                       |
| url-loader                                        | 3.0.0     | 3.0.0     | 4.1.1    | webb-monorepo                        | devDependencies        | https://github.com/webpack-contrib/url-loader                                         |
| webpack-cli                                       | 4.10.0    | 4.10.0    | 5.0.1    | webb-monorepo                        | devDependencies        | https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli               |
| webpack-cli                                       | 4.10.0    | 4.10.0    | 5.0.1    | @webb-tools/bridge-dapp              | devDependencies        | https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli               |
| webpack-cli                                       | 4.10.0    | 4.10.0    | 5.0.1    | @webb-tools/stats-dapp               | devDependencies        | https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli               |

**Comment by dutterbutter** [comment]
We should also remove the redundant Notion libs being used as per this [comment](https://github.com/webb-tools/webb-dapp/pull/1016#discussion_r1123101004) from @AtelyPham

**Comment by AtelyPham** [comment]
I think we can do it in another task because right now, we need `@notion/client` for the blog pages and `notion-client` for the Privacy and Term pages. We used a lib named `react-notion-x` to render the content but the lib is only compatible with the `notion-client` API (compatible I mean no need for any calculations on the response, we can directly pass the response into `react-notion-x` to render the UI). So we need to update the code itself to remove one of these 2 libs, not only remove the dependency. Let me know if something is unclear here.
