### ISSUE TITLE
[CHECKLIST] QA second phase BUGS and Design Discrepancies

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#948]
## Overview

The below checklist outlines the various BUGS and design discrepancies discovered during second phase of QA. These issues will need to be resolved prior to our Alpha launch of the Hubble bridge. To follow the QA test case progress view the Notion document [here](https://www.notion.so/hicommonwealth/QA-Bridge-dApp-bb1d9d674cac46a895e42bfba970f251).

### UI Specific

- [ ] https://github.com/webb-tools/webb-dapp/issues/926
- [ ] https://github.com/webb-tools/webb-dapp/issues/1007
- [x] https://github.com/webb-tools/webb-dapp/issues/949
- [x] https://github.com/webb-tools/webb-dapp/issues/929
- [x] https://github.com/webb-tools/webb-dapp/issues/930
- [x] https://github.com/webb-tools/webb-dapp/issues/932
- [ ] https://github.com/webb-tools/webb-dapp/issues/936
- [x] https://github.com/webb-tools/webb-dapp/issues/942
- [x] https://github.com/webb-tools/webb-dapp/issues/943
- [x] https://github.com/webb-tools/webb-dapp/issues/944
- [x] https://github.com/webb-tools/webb-dapp/issues/946
- [x] https://github.com/webb-tools/webb-dapp/issues/947
- [x] https://github.com/webb-tools/webb-dapp/issues/928

### Functional

- [x] https://github.com/webb-tools/webb-dapp/issues/941
- [x] https://github.com/webb-tools/webb-dapp/issues/940
- [x] https://github.com/webb-tools/webb-dapp/issues/939
- [x] https://github.com/webb-tools/webb-dapp/issues/937
- [x] https://github.com/webb-tools/webb-dapp/issues/935
- [x] https://github.com/webb-tools/webb-dapp/issues/934
- [x] https://github.com/webb-tools/webb-dapp/issues/933
- [x] https://github.com/webb-tools/webb-dapp/issues/931
- [ ] https://github.com/webb-tools/webb-dapp/issues/922
- [x] https://github.com/webb-tools/webb-dapp/issues/950
