### ISSUE TITLE
[TASK] Update education component for bridge

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#979]
## Overview

This tasks scope includes the design improvement and the logic changes required for the Hubble bridge. 

### Expected Behaviour 

When a user is on the 'Deposit' view the education component links should be relevant to the Deposit operation (e.g. usage guide link for deposit will differ than the usage guide links for withdraw). 

The links for the education component should include:
- **Usage guide:** This would link to the docs site for the given operation (e.g. [Deposit usage guide](https://docs.webb.tools/docs/dapps/hubble-bridge/usage-guide/deposit/))
- **FAQ:** This would link to the FAQ section for the Hubble Bridge
- **Support:** This should link to our Telegram channel for now
- **Walkthrough:** This should link to a YouTube video of walkthrough for the given operation (e.g. Deposit, Withdraw)

### Tasks

That being said the following resources/tasks need to created:

- [ ] FAQ for each given section - @dutterbutter will add 
- [ ] Walkthrough for each given operation 
- [ ] Improved designs for education component, see: https://github.com/webb-tools/webb-experiences/issues/58
- [ ] Education component logic to point to the correct links per user operation

**Comment by seeddisperser** [comment]
Eduction card component for the current bridge configuration 

https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1341%3A41299&t=rWlfasfgIfKRaLZu-1

Currently exploring this solution as well. 
![Screenshot 2023-02-03 at 4 14 41 PM](https://user-images.githubusercontent.com/109543061/216733833-52620322-e5cd-4f43-ac2f-ef649014748b.png)
 
However, this requires rethinking how the processing transactions are surfaced. So until there is a good solution to this, the component linked above is a good stopgap improvement to the education card.

**Comment by dutterbutter** [comment]
@seeddisperser thoughts on removing the education component during processing of transactions? I think it it likely the education is best served for initial deposit / transfer / withdraw views but once a transaction is initiated I think there is less interest in having the edu component taking up screen real estate. Thoughts? 

This would allow us to proceed with the explored solution right away and have the transaction processing card sit ontop of the edu backdrop.

**Comment by seeddisperser** [comment]
I was thinking about something similar, but haven't had a chance to mock it up yet. I think this approach could also provide space to surface info about multiple bridge options while a user is choosing where to deposit.

**Comment by dutterbutter** [comment]
@seeddisperser other thing to consider is a what does dark mode look like with that back drop. If possible on your end, it would be great to get this designed and implemented so we can ship it with alpha version this week? 😄

**Comment by seeddisperser** [comment]
I already created a dark mode asset for the background image, so I can include it in a mockup no problem. :~)
<img width="1385" alt="dark mode" src="https://user-images.githubusercontent.com/109543061/217097198-3a673410-b741-4964-b5dc-94667cd66d50.png">

**Comment by dutterbutter** [comment]
@AtelyPham Additional design links:

- [default state](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=2191%3A195494&node-id=2192%3A201185&viewport=-10725%2C-45%2C0.5&scaling=min-zoom&starting-point-node-id=2192%3A201185&show-proto-sidebar=1)
- [transactions present](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=2191%3A195494&node-id=2192%3A204191&viewport=-10725%2C-45%2C0.5&scaling=min-zoom&starting-point-node-id=2192%3A204191&show-proto-sidebar=1)
- [lots of txs](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=2191%3A195494&node-id=2192%3A204693&viewport=-10725%2C-45%2C0.5&scaling=min-zoom&starting-point-node-id=2192%3A204693&show-proto-sidebar=1)
