### ISSUE TITLE
[TASK] Go through the bridge dApp to handle errors gracefully 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#994]
## Overview

Too often the result of an error causes the dApp to crash. We cannot allow this to happen. We need to go through every error case to handle errors gracefully by displaying an error message with direction rather than throwing the error. 

### Task Checklist

- [ ] Go through every error case to see how we are handling
- [ ] Handle the error by providing an informative error message to the user
- [ ] Test each case

**Comment by dutterbutter** [comment]
Completed:

- [x] Sentry inclusion and error detection 
- [x] Dedicated error component in prod environment
